### ISSUE TITLE
Standardization of OSI citation

### ISSUE THREAD

**Issue by martin-fzd** [OpenSimulationInterface/open-simulation-interface#100]
How should a standardized bibtex key look like when citing OSI? My  proposal:
 `@electronic{Hanke.2017`
`author = {Hanke, Timo and Hirsenkorn, Nils and Van-Driesten, Carlo and Gracia-Ramos, Pilar and Schiementz, Mark and Schneider, Sebastian},`
`title = {{Open Simulation Interface: A generic interface for the environment perception of automated driving functions in virtual scenarios}},`
`year = {2017},`
`howpublished = {ONLINE},`
`url = {\url{https://www.hot.ei.tum.de/en/forschung/automotive-veroeffentlichungen/}}}`

**Comment by aschaermann** [comment]
Hi, this is our proposal:

@misc{osi2017report,
	author = {Hanke, Timo and Hirsenkorn, Nils and {van~Driesten}, Carlo and {Garcia~Ramos}, Pilar and Schiementz, Mark and Schneider, Sebastian},
	year = {2017},
	title = {{Open Simulation Interface: A generic interface for the environment perception of automated driving functions in virtual scenarios.}},
	url = {http://www.hot.ei.tum.de/forschung/automotive-veroeffentlichungen/},
	note = {{Accessed: 2017-08-28}}
}

**Comment by martin-fzd** [comment]
Works for me. Shall we close this and add the citation to the readme?

**Comment by CarloVanDriestenBMW** [comment]
@martin-fzd yes please

**Comment by PhRosenberger** [comment]
Actually, it seems to me that Erwin Biebl is missing in this official citation.
Please check: https://www.hot.ei.tum.de/forschung/automotive-veroeffentlichungen/.

My proposal:
```Latex
@misc{osi.2017,
	author = {Hanke, Timo and Hirsenkorn, Nils and {van~Driesten}, Carlo and {Garcia~Ramos}, Pilar and Schiementz, Mark and Schneider, Sebastian and Biebl, Erwin},
	year = {2017},
	title = {{Open Simulation Interface: A generic interface for the environment perception of automated driving functions in virtual scenarios.}},
	url = {https://www.hot.ei.tum.de/forschung/automotive-veroeffentlichungen/},
	note = {{Accessed: 2019-11-05}}
}
```

**Comment by jdsika** [comment]
Right, just create the PR at [osi-documentaion](https://opensimulationinterface.github.io/osi-documentation/open-simulation-interface/doc/description.html)
