### ISSUE TITLE
build: unexpected error MSB4018

### ISSUE THREAD

**Issue by s5919** [OpenSimulationInterface/open-simulation-interface#102]
I followed the installation steps and everything worked until I executed the following command: 

cmake --build . --config Release

There I get this error message:

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB4018: Unerwarteter Fehler bei der CustomBuild-Aufgabe.\r [C:\Program Files\OSI\open-simulation-interface-master\build\open_simulation_interface_obj.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB4018: System.NotSupportedException: Das angegebene Pfadformat wird nicht unterstützt.\r [C:\Program Files\OSI\open-simulation-interface-master\build\open_simulation_interface_obj.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB4018:    bei System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)\r [C:\Program Files\OSI\open-simulation-interface-master\build\open_simulation_interface_obj.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB4018:    bei System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)\r [C:\Program Files\OSI\open-simulation-interface-master\build\open_simulation_interface_obj.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB4018:    bei Microsoft.Build.CPPTasks.CustomBuild.GetInputs(ITaskItem item)\r [C:\Program Files\OSI\open-simulation-interface-master\build\open_simulation_interface_obj.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB4018:    bei Microsoft.Build.CPPTasks.CustomBuild.BuildExecutionGraph()\r [C:\Program Files\OSI\open-simulation-interface-master\build\open_simulation_interface_obj.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB4018:    bei Microsoft.Build.CPPTasks.CustomBuild.GenerateCommandLineCommands()\r [C:\Program Files\OSI\open-simulation-interface-master\build\open_simulation_interface_obj.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB4018:    bei Microsoft.Build.Utilities.ToolTask.Execute()\r [C:\Program Files\OSI\open-simulation-interface-master\build\open_simulation_interface_obj.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB4018:    bei Microsoft.Build.CPPTasks.TrackedVCToolTask.Execute()\r [C:\Program Files\OSI\open-simulation-interface-master\build\open_simulation_interface_obj.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB4018:    bei Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()\r [C:\Program Files\OSI\open-simulation-interface-master\build\open_simulation_interface_obj.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB4018:    bei Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [C:\Program Files\OSI\open-simulation-interface-master\build\open_simulation_interface_obj.vcxproj]

Have you got any solutions for that problem?

**Comment by pmai** [comment]
I have never seen that error; however it might be related to you trying to run builds in the Program Files path? Does the error occur if you place the builds in a normal user-accessible directory, e.g. in your home directory? If it does, which version of VC are you using?

**Comment by s5919** [comment]
I have placed it in a "normal" directory and know the error message changed to the following:

libprotobuf.lib(common.obj) : error LNK2038: Konflikt ermittelt f³r "_ITERATOR_DEBUG_LEVEL": Der Wert "2" stimmt nicht mit dem Wert "0" in osi_version.pb.obj ³berein.

I am using Visual Studio 2010.

**Comment by CarloVanDriestenBMW** [comment]
Maybe you are trying to build with as Debug and the proto Libs are only installed as release?

**Comment by pmai** [comment]
As Carlo says, this kind of error indicates that stuff that was built as release code (i.e. your OSI stuff) is being linked against code that was built in debug mode (the proto libs you are linking against); this is not supported on Windows/Visual Studio, hence the linker error. Try to point cmake to a release build of protolib, or build osi in debug mode, either should work better.

**Comment by s5919** [comment]
Build osi in debug mode solved the problem. Thanks!
