### ISSUE TITLE
Cleanup of SensorDataGroundTruth and handling of sensor-relative "ground truth"

### ISSUE THREAD

**Issue by pmai** [OpenSimulationInterface/open-simulation-interface#106]
During the current round of prototyping, the endless recursion of Sensor Data, SensorDataGroundTruth and  GroundTruth led to us switching to just having GroundTruth as sensor input and SensorData as sensor output. For the next release I think we need a cleaner solution, where it is also possible to cleanly daisy-chain different model parts (e.g. for fault injection, or other error modelling), and where it is also possible to take advantage of certain pre-calculations that environment simulations tend to already perform, and that sensor models want to be able to use.

As such I see three different stages of data:

1. **GroundTruth**: Just as it stands now, GroundTruth is a depiction of reality that is independend of individual vehicles or sensors, both in terms of coordinates and in terms of its contents (ignoring for the time being any cone-of-interest filtering that is to be performed for performance reasons).

2. **SensorRelativeGroundTruth** (or some better name): I think we need a new representation of sensor relative ground truth data, which (in addition to being in sensor coordinates) can transport information that is sensor-relative by nature: For example all of the input data for the physical models, like ray tracing data is inherently sensor-relative, as are even some useful attributes for phenomenological models, like occlussion, etc. Ground Truth is probably the wrong term here (and in general not a very useful term), it is that which the sensor can perceive (i.e. the input to its perception function). As it stands now, the GroundTruth is the wrong place for this, IMHO, and the SensorData definitely is the wrong place, since it already talks of detected, i.e. perceived and processed, data.

3. **SensorData**: This is the output of a sensor (i.e. it talks of DetectedObjects, which only make sense after detection, i.e. after a sensor has performed its processing), as it stands now. There can be an optional facility to keep a copy of GroundTruth in there for tracing convenience, however I would prefer to not do this, since it can easily lead to confusion and performance issues.  There are safer and more efficient ways of doing tracing, IMHO.

With a split like this, it would be possible to have any number of pre-filters, that act on SRGT data and produce SRGT data, one sensor model itself that turns SRGT into SensorData, and again any number of post-filters, that take SensorData and output SensorData.

We could of course change GroundTruth to be sensor-dependent (even if not sensor relative in a coordinate way), but IMHO that would prevent us from talking about the global ground truth. SensorData itself cannot IMHO act as both input and output to a sensor at the same time, since it only talks about already perceived data...

What do people think of this issue?

**Comment by CarloVanDriestenBMW** [comment]
![grafik](https://user-images.githubusercontent.com/25304009/35435346-a66d4c6a-028a-11e8-88b8-77556eda757a.png)

@pmai something like this?

**Comment by hschoen** [comment]
I agree to the concept of splitting data as described. Maybe "SensorRelativeGroundTruth" could be named "SensorInputData" and "SensorData" could be named "SensorOutputData".

**Comment by MHerrmannIPG** [comment]
The proposed architecture by Carlo and names by Helmut make sense to me.

**Comment by CarloVanDriestenBMW** [comment]
But... IF we call it SensorOutputData it would be strange to have it has input for a trailing Sensor Model?? I actually removed that description in the beginning ^^

**Comment by pmai** [comment]
@CarloVanDriestenBMW yes, the architecture diagram makes sense to me (with the addition that obviously both cases can just be in-line FMUs without any Sender FMU stuff), and I would suspect that very many models would use the right-hand side alternative, even if they do not make use of simulation tool features like POV-related occlusion, etc., just to take advantage of the coordinate system transform ;).

The naming issue will be tricky, I guess (as they say, there are only two hard problems in computer science: naming things).

**Comment by MHerrmannIPG** [comment]
@CarloVanDriestenBMW Then I misinterpreted the draft. I thought each toolprovider will implement his custom/proprietary raytracer solution. It seems like you would like to have a generic interface - I'm not sure if this is really a necessity as long as the contents of the technology-specific interfaces and the parameterization of the raytracer from outside is possible. Has this already been discussed in depth?

**Comment by CarloVanDriestenBMW** [comment]
From my understanding we have to choose a solution which enables a tier1 like bosch to build its sensor model within the tool. Referencing this picture this would include a bosch specific raytracer using some kind of framework like Optix/Cuda/OpenCL. I must say that the solution should not restrict from using AMD grafik cards or whatever hardware. 
The simulation tool can provide their own solution for physcal sensor models using the mentioned frameworks above in the same way as they could provide Sensor Model FMUs for phenomenological sensor models?

**Comment by pmai** [comment]
FWIW I think there will be multiple ways of handling this, so both views on the architecture are correct IMHO: As a base case a sensor modeler would use the built-in ray tracing and other capabilities of the Environment Simulation, and set it up (via SensorInputConfiguration) in such a way that it is suitable as Input to the sensor model. Future versions of OSI might even allow the configuration of custom computation Fragments (cf. OpenGL/CUDA/OpenGLSL) or similar by the sensor model, but still utilizing Environment Simulation Code/Frameworks. In the final case, I think sensor models sometimes will have to include their own ray tracing or computation framework, and will only employ the GT feed to built up an internal world model and user their builtin code base to do all calculations.

OSI just has to be flexible enough to Support both, which is possible through the Input configuration and GT vs. "SensorInput" vs. "SensorData" split...

**Comment by pmai** [comment]
I have added a first draft of this (now called SensorView and transported alongside the GroundTruth inside SensorData for now) as PR #132, please take a look at this.

**Comment by AndreHildebrandt** [comment]
I also agree with @pmai regarding the splitting of the data.
I have some questions though.
1) Is the output of a sensor model always defined as SensorData? Or in other words, is it possible to put sensor models a chain, so that the modelling part gets modularized?
2) What about the SensorInputConfiguration? In which hierarchical structure is it embedded? SensorData? Is it possible to change the configuration during the simulation?

Maybe we could extend the sketch of @CarloVanDriestenBMW. Aim would be to create an overview sketch for documentation. I realized, that it is hard to explain OSI to others, since there are no up-to-date skatches available...

**Comment by pmai** [comment]
@AndreHildebrandt to answer your points as far as I can:

1. I think there is the ability to daisy-chain models, since even now models are supposed to receive SensorData (with only GroundTruth and optionally SensorView filled out) and send SensorData onward (with potentially more filled out). In this fashion one could implement e.g. pre-detection models that only enrich the GroundTruth/SensorView parts of SensorData, one (or potentially more) detection models that fill out the non-GT/SensorView parts of SensorData (the detection models), and post-detection models that modify the non-GT/SensorView parts of SensorData further (e.g. high-level fault-injection).

2. The intent is for SensorInputConfiguration to not be embedded in any of the other messages, but to be its own top-level message, in order to support exchanging SIC at different times than SensorData. It depends on the packaging standards how this is achieved. For FMU-packaging one would implement that as seperate (calculated)Parameters variables (i.e. calculatedParameter for the sensor request, Parameter for the final setup by the environment). If change during the simulation is to be supported those could be tunable, however this also needs a trigger output I think to keep the checking efficient...

I agree that more documentation of the pragmatics of OSI are needed to get other people on board...

**Comment by CarloVanDriestenBMW** [comment]
solved by #179 

@carsten-kuebler the new concept needs to be explained in the wiki - let us make a small "workshop" in order talk about the extension of the wiki etc

**Comment by carsten-kuebler** [comment]
Today :-) ?
