### ISSUE TITLE
Traffic Signs: End of minumum speed missing

### ISSUE THREAD

**Issue by ReinhardBiegelIntech** [OpenSimulationInterface/open-simulation-interface#119]
The ```enum Type``` in ```TrafficSign``` is missing an entry for "end of minimum speed". German StVO references this sign as [no. 279](https://www.dvr.de/publikationen/downloads/verkehrszeichen.html).

If there are no objections, I'd create a PR for adding this type.

**Comment by CarloVanDriestenBMW** [comment]
@carsten-kuebler if you have a pullrequst on that already @ReinhardBiegelIntech could than review and alter it?

**Comment by carsten-kuebler** [comment]
@CarloVanDriestenBMW no, there is no open pullrequest. I would propose to extend pullrequest #114 (Extended Documentation) and add the sign 279.

By the way, there are other signs which are missing (no_parking begin/end 283.1-3 286.1-3 --> additional arrows on signs). 
Or the one-way road sign is missing...

**Comment by carsten-kuebler** [comment]
@CarloVanDriestenBMW and @ReinhardBiegelIntech please comment/review pullrequest #122 .

**Comment by pmai** [comment]
Closed with PR merge.
