### ISSUE TITLE
Support for Partial Updates (e.g. of static GroundTruth data)

### ISSUE THREAD

**Issue by pmai** [OpenSimulationInterface/open-simulation-interface#126]
In various discussions the wish for less frequent updates of (fairly) static ground truth data, like e.g. lane data, has been expressed. I created this issue to keep track of this request. For 3.0.0 various measures to reduce the amount of data transferred in GroundTruth are being implemented which should lessen the need for partial updates, but the need might arise again in the future.

One possible implementation, that is fairly easy to specify and does not result in complex update logic would be to allow certain fields of GroundTruth to be empty in messages, indicating that the old data is still valid. This needs to be specified for each field, since for certain fields empty is a valid value, but for stuff like road network data it would be a possibility, since having no road network (i.e. lanes) currently has no valid meaning.

I'm not currently persuing this for 3.0.0, since other measures should lessen the need for this, and also make data like road data less static (cf. cone of interest), but it might be resurrected in the future.

**Comment by CarloVanDriestenBMW** [comment]
Thank you @pmai for keeping track of that issue - it is important in the future!
