### ISSUE TITLE
Spherical3d type missing

### ISSUE THREAD

**Issue by OsamaOthman** [OpenSimulationInterface/open-simulation-interface#135]
In osi_featuredata.proto, Message "LidarDetection", Fields of type "Spherical3d" are defined but I can't find where this type is defined or its definition is missed?

**Comment by CarloVanDriestenBMW** [comment]
open-simulation-interface/osi_common.proto
Line 166

Please have a look at the includes in each file. The basic types a mostly in osi_common.proto
