### ISSUE TITLE
Osi detected traffic signs geometry

### ISSUE THREAD

**Issue by ecazaubon** [OpenSimulationInterface/open-simulation-interface#136]
I have a question regarding the Geometry field in the DetectedTrafficSign. 
Is it really needed as the geometry is strongly linked to the type ? 
Also, is there a difference between a Danger Sign and a Yield Sign in this Geometry (also between a priority road sign and "indication" signs)? 
Anyway, it would lack octagon and variants of rectangles and arrows.

**Comment by CarloVanDriestenBMW** [comment]
@carsten-kuebler will help with that - he is currently refining the documentation for TrafficSigns and your input is much appreciated, thank you!

**Comment by carsten-kuebler** [comment]
@CarloVanDriestenBMW and @ecazaubon if a sensor detects only the traffic sign shape and not the image, the geometry field reduces data. I propose to extend the enumeration Geometry.

enum Geometry
    {
        // Geometry of the traffic sign is unknown (must not be used in ground truth).
        //    
        GEOMETRY_UNKNOWN = 0;
        
        // Geometry of the traffic sign is unspecified (but known).
        //    
        GEOMETRY_OTHER = 1;
        
        // Traffic sign has a triangular geometry pointing to the top.
        //    
        GEOMETRY_TRIANGLE_TOP = 2;
        
        //Traffic sign has a triangular geometry pointing down.
        //    
        GEOMETRY_TRIANGLE_DOWN = 3;
        
        // Traffic sign has a circular geometry.
        //    
        GEOMETRY_CIRCLE = 4;
        
        // Traffic sign has a square geometry.
        //    
        GEOMETRY_SQUARE = 5;
        
        // Traffic sign has a diamond geometry.
        //    
        GEOMETRY_DIAMOND = 6;
        
        // Traffic sign has an octagon geometry.
        //    
        GEOMETRY_OCTAGON = 7;
        
        // Traffic sign has a geomety of an arrow pointing to the left.
        //    
        GEOMETRY_ARROW_LEFT = 8;
        
        // Traffic sign has a geomety of an arrow pointing to the right.
        //    
        GEOMETRY_ARROW_RIGHT = 9;
        
        // Traffic sign has a rectangle geometry. (width is bigger than height)
        //    i.e. one-way
        GEOMETRY_RECTANGLE = 10;
        
        // Traffic sign that has a pole geometry. (height is bigger than width)
        //    i.e. pole indicating highways exit in xx m.
        GEOMETRY_POLE = 11;
        
        // Traffic sign that has an oversize rectangle geometry.
        //    i.e. direction plates on highway or city signs.
        GEOMETRY_PLATE = 12;
    }

**Comment by CarloVanDriestenBMW** [comment]
@carsten-kuebler  will you add this in #124 ? I think it should be added, if the field is part of the standardization. I suspect, that the geometry is a standard output of the camera e.g.?

**Comment by carsten-kuebler** [comment]
@CarloVanDriestenBMW no, it is not part of the pre-draft stardardization of traffic signs. Cameras will only use this, if the camera sees the backside of the traffic sign. Other sensors may see only the shape of the traffic sign. I will add this as a new PR.

**Comment by CarloVanDriestenBMW** [comment]
@ecazaubon is that solved for you?

**Comment by ecazaubon** [comment]
@CarloVanDriestenBMW For me it is.
