### ISSUE TITLE
Osi detected lanes

### ISSUE THREAD

**Issue by ecazaubon** [OpenSimulationInterface/open-simulation-interface#137]
Is there a reason for detected lane boundaries not to have tracking id ?
And for the Lane not to have a root mean square error representation ?

**Comment by CarloVanDriestenBMW** [comment]
@carsten-kuebler is there a root mean error in the ISO standardization? It must be a correlated error on all points along the line?
@ecazaubon what do you mean by "tracking iD"?

**Comment by ecazaubon** [comment]
for example in the same file there is for the detected lane (with lane center) the following field : 
```    
// Specific id of the detected lane as assigned by the sensor internally. Need not match with ground_truth_id. 
// 
optional Identifier tracking_id = 2; 
```
And you can find it in other Detected types as well. I do not know if  it makes sense for the Detected lane boundaries to have one such field but it is irregular in regard of other Detected Types

**Comment by carsten-kuebler** [comment]
@pmai @ecazaubon @CarloVanDriestenBMW DetectedLaneBoundary need also a tracking_id. The new Tracking_id and the new message DetectedLaneBoundary are from two different pull requests. @pmai could you please fix it or should I add a PR?

**Comment by CarloVanDriestenBMW** [comment]
@carsten-kuebler would be nice if you can fix it because @pmai is busy the next two days (prostep)

**Comment by carsten-kuebler** [comment]
@CarloVanDriestenBMW ok. PR added...
@pmai see you at prostep :-)

**Comment by CarloVanDriestenBMW** [comment]
@ecazaubon please review at #143
