### ISSUE TITLE
Small typo 

### ISSUE THREAD

**Issue by ecazaubon** [OpenSimulationInterface/open-simulation-interface#139]
[here](https://github.com/OpenSimulationInterface/open-simulation-interface/blob/ef2085f1a98f29fe4ef60912e01302a4a2391804/osi_featuredata.proto#L45). Probably an unwanted 'l'

**Comment by pmai** [comment]
Thanks, will be fixed in PR #140

**Comment by pmai** [comment]
Fixed in PR #140
