### ISSUE TITLE
Reference frames specified directly in coordinates

### ISSUE THREAD

**Issue by SoykaDaimler** [OpenSimulationInterface/open-simulation-interface#14]
I saw that reference frames are defined in many places in the interface. From experience I would say that   
it is very valuable to know explicitly for each coordinate in which frame it is defined.  Therefore, I proposed some code in the branch DaimlerSuggestions (see reference below). 
All frames should be documented in the Wiki as well.

**Comment by TimoHankeBMW** [comment]
Defining the reference frame as an enum that goes along with the coordinates allows the possibility of changing the reference frame for a specific message. Do we want this? You would have to check the reference frame and do possibly do a transformation at any time that you access coordinate values, which increases code complexity quite a bit.
We could specify that the reference frame must have a specific value for each message, but then I don't see the added benefit of including the enum.

**Comment by TimoHankeBMW** [comment]
Accidentaly hit close there, please ignore :-)

**Comment by nHirsenkorn** [comment]
I am of the same opinion as Timo Hanke: 
Effectively this would make me call a converter each time a protobuffer with unknown reference frame is received. If this call is forgotten, the Code might silently fail. With the current definition this conversion process is only required once, when filling the protobuffer, not each time when using it.

**Comment by SoykaDaimler** [comment]
I agree that it increases complexity. On the other hand it also increases quality assurance and safety. By explicitly defining the reference frame as part of the message people are forced to think about it. If the reference frame is 'only' defined in the comments it can be overlooked. And in the case of using a message for a new use case there's a decreased likelihood of using it in the wrong coordinate system. 

And 'bugs' that are due to a wrong reference frame are very hard to track down. Some people even go as far as defining units for a message. In that case the Vector3d message for position, velocity and acceleration would differ. 

I agree that it is more code, but it think in the long run the benefits are worth it. 

One more point in favor of including it: adding the enum would not mean that you necessarily have to change already existing code. You can still just assume that the data is in the correct reference system and treat it as before. So you can think of it as an additional optional check.

What do other people think about this issue?

**Comment by nHirsenkorn** [comment]
If decide to add coordinate system support, we could add ROS-style transfer functions:
For example:
A transfer function for sensor positions are defined relative to the bounding box middle of the vehicles
A transfer function for the environment model origin is also defined relative to the bounding box middle.

This would enable a standardized conversion from any cosy to any other. Even for multiple vehicles e.g. for car2car communication/fusion.

**Comment by SoykaDaimler** [comment]
I think adding such transfer functions would significantly improve ease of use and clarity.

**Comment by nHirsenkorn** [comment]
I added a wiki article presenting the current coordinate systems and reference frames. Consider improving it.

[Coordinate System Wiki page](https://github.com/OpenSimulationInterface/open-simulation-interface/wiki/Coordinate-systems-and-reference-points)

**Comment by SoykaDaimler** [comment]
As discussed in PEGASUS UAP3.2.2 meeting (6.3.2017) we will not introduce additional fields describing the reference frames right now.

**Comment by CarloVanDriestenBMW** [comment]
@pmai having introduced more interfaces this could be useful again?

**Comment by CarloVanDriestenBMW** [comment]
place discussion in #51
