### ISSUE TITLE
Proposal  for object orientation and transformation

### ISSUE THREAD

**Issue by Markus-Philosys** [OpenSimulationInterface/open-simulation-interface#145]
@CarloVanDriestenBMW 

Since different simulators could use other transformation-sequence of yaw, pitch, roll than described in  OSI (see "message Orientation3d" in "osi_common.proto"), it could be useful proving a rotation-matrix instead of angles / additional to the angles.

This could avoid errors with transformation sequence and save cpu power for recalculating the angles in  OSI rotation order.

**Comment by CarloVanDriestenBMW** [comment]
see #51
