### ISSUE TITLE
Spherical3d Definition is Ambiguous

### ISSUE THREAD

**Issue by TimFrickeBMW** [OpenSimulationInterface/open-simulation-interface#148]
Azimuth and elevation are not exactly defined. Around which axes are these angles measured? Does the right-hand rule apply? In practical terms, the current definition does not tell me for instance what a positive azimuth angle means. Is the referenced point left or right of the sensor? And where is the sensor's left and right side, anyway? This is again an issue of coordinate system definitions, related to #14 , #42 and #51

**Comment by CarloVanDriestenBMW** [comment]
@TimFrickeBMW 
please comment in #51 does sticking to the ISO8855 solve your problem?
