### ISSUE TITLE
Measured time

### ISSUE THREAD

**Issue by CarloVanDriestenBMW** [OpenSimulationInterface/open-simulation-interface#149]
Do we have a double definition here?
```
optional Timestamp osi::DetectedObjectHeader::measurement_time = 2
optional Timestamp osi::SensorData::last_measurement_time = 8
```

On is in the header of each detected object, the other one in the sensorData encapsulation?

**Comment by carsten-kuebler** [comment]
It will also differ if you have sensor data from a sensor data fusion. In this case some detected objects may be approved only from a subset of sensors. In this case detected objects with different sensor subsets may have different DetectedObjectHeader::measurement_time.

**Comment by CarloVanDriestenBMW** [comment]
OK, thanks for the clarification!
