### ISSUE TITLE
Add polygon contour to Dimension3d

### ISSUE THREAD

**Issue by SoykaDaimler** [OpenSimulationInterface/open-simulation-interface#15]
Can we have an additional polygon base in Dimension3d? 
I'd like a sensor to be able to return an occluded shape different from a rectangle. 

We could implement it as a list of Vector2d or as Vector3d with z=0.

See reference below.

**Comment by nHirsenkorn** [comment]
If required we can add this, but not inside the Dimension3d. Dimension3d is intended for bounding boxes only. Instead you can open a new field.

Currently I don't known of a standard sensor describing a shapea other than a rectangle. Consider adding this polygon field to a certain sensor in  osi_sensorspecific.proto.

If the field was inteded for enabling some freespace description we should consider opening a new message type on the level as GroundTruth and SensorData. 
Sensor-models could then work like this:
GroundTruth -> Freespace
or like this:
GroundTruth -> SensorData -> Freespace

**Comment by TimoHankeBMW** [comment]
Is the use case of a polygon base to allow for "more sophisticated" occlusion calculation or should that type of bounding box be detected, i.e. output, by a sensor?

**Comment by SoykaDaimler** [comment]
Thanks for your comments!
The use case is occluded shapes as sensor outputs. Simple 2D sensor inputs should be rectangular bounding boxes. But the outputs can be any kind of 2D polygon. 
@TimoHankeBMW Your comment about the interface not being designed for that is a bit unclear too me. I thought our purpose within PEGASUS is to extend the interface in such a way that it meets our use cases. Therefore I thought we try to implement all the necessary data structures. 

@nHirsenkorn I have not thought about Freespace here, but within PEGASUS it is a use case. Therefore we do not freespace as an output, so we do need 2D polygons anyway. I think the interface has to be checked against all the definitions and use cases we came up with in PEGASUS anyway. This should be discussed in on of our next meetings -> @raueATconti

**Comment by TimoHankeBMW** [comment]
@SoykaDaimler Yes, the interface should definitely be extended to meet the required use cases. My point above was just meant as a caveat about geometric calculations. Detailed geometric calculations are the playing field for a proper scene graph or similiar specialized data structures.
If there is a specific use case, its fine to include additional geometric shapes for objects. As stated above I'd just advise caution that no one starts having ideas about implementing a depth map or even ray tracer against the OSI data structures.

**Comment by SoykaDaimler** [comment]
Agreed. Thanks for the clarification!

**Comment by KathaHo** [comment]
Hi there!
I was just added to this project by Carlo and have read through this issue. 
@SoykaDaimler do you need all kinds of polygons, or would convex polygons do work for you? I think if we can reduce the polygons to convex polygons it makes this issue easier.

**Comment by SoykaDaimler** [comment]
Hi Katha,
welcome to the project and thanks for your input!
Why do think that convex polygons would make the issue easier? 
Defining a general polygon, as I did it in the code, as a collection of 2D Vectors seems rather uncomplicated to me. I guess I'm missing something :-)
For the car shapes and occlusion calculations I guess convex polygons are sufficient. However for freespace polygons they can also be concave. Therefore I would propose the general definition without a restriction to concave or convex.

**Comment by KathaHo** [comment]
In general convex polygons are less error-prone (points do not have to be stored in a specific order). And if there is a data structure convex polygons, you can put several of convex polygons together to build a concave polygon. 
It is also possible to store a polygon as a set of "hyperplanes". This would be similar for convex and concave polygons
