### ISSUE TITLE
Major Version Todos: Renumber OSI message fields

### ISSUE THREAD

**Issue by carsten-kuebler** [OpenSimulationInterface/open-simulation-interface#163]
Todo for next major release.

**Comment by CarloVanDriestenBMW** [comment]
@carsten-kuebler I think we will do this as the last step before releasing tomorrow.

**Comment by carsten-kuebler** [comment]
And plural s...

**Comment by CarloVanDriestenBMW** [comment]
@carsten-kuebler  we will stick to singular now:
Reason: If we change a field from optional to repeated we do not have to cha nge the name and have compatibility! Kudos @pmai

**Comment by carsten-kuebler** [comment]
So I will renumber all messages. @CarloVanDriestenBMW @pmai Do we need fixed numbers for fields or can we renumber all messages?

**Comment by carsten-kuebler** [comment]
Renumbering done. 
Plural s not done.
Remove Landmarks - open PR.
Relevant xx - open PR.
Version in top-Level messages misses? FeatureData has its own Version message - change?

**Comment by carsten-kuebler** [comment]
all "open issues" are included in PR #200 (the final PR 🥇 )
