### ISSUE TITLE
Remove interface version in SensorDetectionHeader and SensorView

### ISSUE THREAD

**Issue by carsten-kuebler** [OpenSimulationInterface/open-simulation-interface#165]
Remove message field version from messages SensorDetectionHeader and SensorView.

**Comment by pmai** [comment]
I‘m not sure whether that is sensible for SensorView, since this could end up a top-level message, like Groundtruth.

**Comment by carsten-kuebler** [comment]
With this argument, SensorData should also get a version field?! 
@CarloVanDriestenBMW what do you think of Pierre's objections. It's about versioning and compatibility.

**Comment by pmai** [comment]
Yes, I think all potential top level messages should have the version field (I totally missed that it didn’t already), otherwise one would have to depend on e.g. GT being present to determine the version...

**Comment by carsten-kuebler** [comment]
Do you have a definition which messages could be top-level messages (GT, SensorData, SensorView, HostVehicle, ...)

**Comment by CarloVanDriestenBMW** [comment]
@carsten-kuebler for now: GT, SD, SensorView

objections @pmai ?

**Comment by pmai** [comment]
I'd add SensorInputConfiguration, since this is potentially exchanged prior to any of the other messages.

**Comment by carsten-kuebler** [comment]
@CarloVanDriestenBMW So we must add version to SD (not SensorDetectionHeader --> remove version field), and FeatureData?! and SensorInputConfiguration.

**Comment by CarloVanDriestenBMW** [comment]
Solved in #179
