### ISSUE TITLE
Add new message Landmark or Obstacle

### ISSUE THREAD

**Issue by carsten-kuebler** [OpenSimulationInterface/open-simulation-interface#166]
We should add a new message for traffic sign poles, traffic light poles and static landmarks. Traffic lights' etc. bounding boxes (BaseStationary) include no pole. The same applies to traffic signs...

**Comment by CarloVanDriestenBMW** [comment]
message StationaryObject can be used to model objects which have no traffic related information?

**Comment by carsten-kuebler** [comment]
@CarloVanDriestenBMW yes you are right. StationaryObjects could be poles or buildings (Landmarks and StationaryObjects are similar). There is no detection of StationaryObjects at the moment. We can move DetectedLandmark (and its submessages) to DetectedObject.proto and rename the message to DetectedStationaryObject. Does this proposal meet your expectations? (Sorry. I missed the message StationaryObject.
Maybe there should be a list of assigned lanes?

**Comment by carsten-kuebler** [comment]
@CarloVanDriestenBMW I add a new PR #176.
