### ISSUE TITLE
Reference coordinate system for BaseStationary

### ISSUE THREAD

**Issue by AhmedMzid** [OpenSimulationInterface/open-simulation-interface#173]
The description of `BaseStationary` sets the reference coordinate system to be the global ground truth coordinate system, which is not available for objects in `SensorData`.

This is also the case for `BaseMoving`, `Landmark`, `RoadMarking` and `TrafficSign`.

![ks-basestationary](https://user-images.githubusercontent.com/26384662/37829190-6b44e180-2e9e-11e8-949f-e860eb04c2f3.png)

**Comment by carsten-kuebler** [comment]
You are right, but not for Landmark, RoadMarking and TrafficSign. But for DetectedEntities...

**Comment by carsten-kuebler** [comment]
I add your feedback to PR #167.
