### ISSUE TITLE
Implementation of DetectedLaneBoundary

### ISSUE THREAD

**Issue by AhmedMzid** [OpenSimulationInterface/open-simulation-interface#174]
The implementation of DetectedLaneBoundary is a bit different from the implementation of other detected entities. In all other detected entities, we have a repeated field with all candidates and we assign a probability to each candidate, e.g. `CandidateSign` in `DetectedTrafficSign` or `ClassProbability` in `DetectedObject`.
In `DetectedLaneBoundary` we have a single `LaneBoundary` with a specific type and color then we give the confidence for the type and color classifications. Is there a specific reason for that?

**Comment by carsten-kuebler** [comment]
No, we have 2 different Detected... message classes.

DetectedObject, DetectedLane and DetectedLaneBoundary, DetectedOccupant
on one hand and on the other hand
DetectedTrafficSign, "DetectedSublementarySign", DetectedTrafficLight, ...

DetectedObject (DetectedLane, DetectedLaneBoundary) implements all actual requirements of the standardisation activities.
For all other entities there is no standardisation yet.

Should we change DetectedOccupant?

**Comment by CarloVanDriestenBMW** [comment]
@AhmedMzid thx for pointing that out!

@carsten-kuebler as discussed you can make a new PR and change the DetectedLane and DetectedLaneBoundary to the same schema as in e.g. DetectedTraficSign.

**Comment by carsten-kuebler** [comment]
@CarloVanDriestenBMW DetectedLaneBoundary should be done. I will adapt DetectedLane now...

**Comment by CarloVanDriestenBMW** [comment]
solved in #186
