### ISSUE TITLE
Vehicle Type definitions

### ISSUE THREAD

**Issue by marcin-piatek** [OpenSimulationInterface/open-simulation-interface#177]
I would like to propose an extension to `Vehicle` `Type ` enum with different types of cars and semi trailer. To full list of different vehicles types I would define that way:
- unknown
- other
- small car
- medium car
- compact car
- luxury car
- delivery van
- truck
- truck with semitrailer
- trailer
- motorbike
- bicycle

**Comment by CarloVanDriestenBMW** [comment]
@marcin-piatek could you state some proper definitions for the examples?
