### ISSUE TITLE
Enhance Doxygen Documentation with Images for Lane Model

### ISSUE THREAD

**Issue by CarloVanDriestenBMW** [OpenSimulationInterface/open-simulation-interface#185]
The new lane model has been introduced in #110 and the documentation has to be extended with proper pictures explaining the system in detail as well as to refine some cases as described in #156

**Comment by carsten-kuebler** [comment]
Or v3.0.1...

**Comment by LudwigFriedmannBMW** [comment]
@carsten-kuebler: Are there any updates on this issue?

**Comment by carsten-kuebler** [comment]
@LudwigFriedmannBMW I add Documentation-and-figures-3.0.1 without the figures. If you give me feedback, you or I will add the figures.

**Comment by LudwigFriedmannBMW** [comment]
@carsten-kuebler: Please add the pictures to the documentation.

**Comment by carsten-kuebler** [comment]
@LudwigFriedmannBMW  I add the figures to the PR.

**Comment by LudwigFriedmannBMW** [comment]
Issue solved with #266
