### ISSUE TITLE
Check RadarSensorView

### ISSUE THREAD

**Issue by CarloVanDriestenBMW** [OpenSimulationInterface/open-simulation-interface#190]
Could you please check if the configuration of a physical radar sensor and its values in RadarSensorView are fine for you (including comments). Thx!

**Comment by marcin-piatek** [comment]
RadarSensorView seems to be OK but I would prefer to use `range` and `range_rate` instead of  `time_of_flight` and `doppler_shift`. I got used to it and I think they are more generic and we do not have to use very small numbers.

**Comment by CarloVanDriestenBMW** [comment]
@hschoen after watching the "radar raw signal" sensor model for the new carmaker I was wondering if you could review the SensorView interface for radar detections?

**Comment by CarloVanDriestenBMW** [comment]
We will leave this one open because #250 states that there are no necessary changes for 3.0.1 but maybe we need some for further versions.
