### ISSUE TITLE
Wiki Page

### ISSUE THREAD

**Issue by CarloVanDriestenBMW** [OpenSimulationInterface/open-simulation-interface#2]
The wiki page should be updated in order to understand how the interface may be used.

Ideas:
1. Describe the interface and explain its scope (Automobile, robotics, etc ...)
2. Try to describe the group of users, which may benefit from it
3. Bring it in the context of current publications
4. Explain the context of PEGASUS

**Comment by nHirsenkorn** [comment]
1-3 is covered by the cited research article.
4 should be written by a member of the Pegasus-community.

Further documentation should be developed for messages where questions arise.

**Comment by TimoHankeBMW** [comment]
Concerning 4 I suggest we develop the documentation FAQ-style along with the actual questions that arise when people review and use the interface.
The major part of the documentation should be within the code itself (comments) and "meta-descriptions" (i.e. not message specific) should be covered by the OSI-description slides. We should update both according to feedback and suggestions.

**Comment by nHirsenkorn** [comment]
having a continuous task in the issues section does not make a lot of sense.
