### ISSUE TITLE
Bug in "proto2cpp" to show subclasses in Doxygen

### ISSUE THREAD

**Issue by CarloVanDriestenBMW** [OpenSimulationInterface/open-simulation-interface#206]
There is a problem with the proto2cpp because it incorrecly shows the following line:

`optional StationaryObject.Classification classification = 2;`

![grafik](https://user-images.githubusercontent.com/25304009/38722754-372b8c20-3eff-11e8-8525-e4a5315309ff.png)

**Comment by carsten-kuebler** [comment]
![image](https://user-images.githubusercontent.com/32508295/38876702-4ec6cd20-425d-11e8-86a7-9543395f3031.png)

Better :-) ?

(Dots aren't allowed for field names. They have to replaced with "::".)

**Comment by CarloVanDriestenBMW** [comment]
... Aren't allowed in Doxygen or in Protobuffer? So we have a bug in the current release?

**Comment by carsten-kuebler** [comment]
No, the bug is in proto2cpp. I add a replacement of the dots with :: in the wrapper script. The proto files are unchanged.
