### ISSUE TITLE
Update: Readme + PowerPoint slides

### ISSUE THREAD

**Issue by CarloVanDriestenBMW** [OpenSimulationInterface/open-simulation-interface#208]
For someone who is new to OSI it is hard to get into the topic. Therefore the structure of the readme has to be improved. The concept should be clear with just a few secondes to look at it and the purpose of OSI must be explained clearly.
What do you see here?
What is it for?
What problem does it solve?
What vison is behind this project?
Where doies it come from?
etc

**Comment by CarloVanDriestenBMW** [comment]
> Download the vg-1.5.0.zip. Unpack and copy the content of folder /vg-1.5.0/contrib/proto2cpp to your desired <path-to-proto2cpp.py>

The link in the Readme.md should be replaced with the new fork in the proto2cpp repository

**Comment by CarloVanDriestenBMW** [comment]
We removed the legacy slides explaining the OSI architecture from the TUM server and we have to replace them with a current version.

**Comment by carsten-kuebler** [comment]
Should we remove all infos from the wiki and merge it with the readme. We could add a link to the readme.

**Comment by carsten-kuebler** [comment]
Should I add the PPT slides (2.2 vs. 3.0) to the documentation?

**Comment by CarloVanDriestenBMW** [comment]
I think we can add them!
After the fix from @FabeleAltran for the installation we can update the install instructions in the wiki, or?
I like the online Documentation! :)

**Comment by carsten-kuebler** [comment]
@LudwigFriedmannBMW I add the presentation to this issue

[OSI 3_overview_github.pdf](https://github.com/OpenSimulationInterface/open-simulation-interface/files/2290245/OSI.3_overview_github.pdf)

**Comment by carsten-kuebler** [comment]
[osi_overview_v2.2_vs_v3.0.pdf](https://github.com/OpenSimulationInterface/open-simulation-interface/files/2297162/osi_overview_v2.2_vs_v3.0.pdf)
@LudwigFriedmannBMW  I copied the ppt in a word document and generated the pdf

**Comment by LudwigFriedmannBMW** [comment]
Referenced in the [wiki](https://github.com/OpenSimulationInterface/open-simulation-interface/wiki#changelog)

**Comment by LudwigFriedmannBMW** [comment]
Since the introduction to OSI is more in the wiki than in the readme file, i close this topic and refer to the further development in #246.
