### ISSUE TITLE
Modelling of Emergency-Lanes and emergency bays

### ISSUE THREAD

**Issue by StefanSudbrack** [OpenSimulationInterface/open-simulation-interface#218]
Hello,

a question / proposal arised modelling a driving scenario regarding Emergency Lanes (Standstreifen) and emergency bays (Nothaltebuchten).

As far as we understood in OSI 3  emgergency lanes / bays would be covered by an additional non-driving lane on the right with appropriate LaneBoundaries.

In order to differenciate more clearly we had the question if it would help to extend "lane types" in order to identify driving / non-Driving / drivable? Or identify emergency bays (Nothaltebuchten) by a separate type.

[Thanks](url)

**Comment by carsten-kuebler** [comment]
Non-driving or drivable (conditional driving) lanes are the same. The host vehicle uses these lanes only in exceptional circumstances. It depends on traffic signs, road markings, lane boundaries and they define under which circumstances a vehicle may use them. Is it trivial possible to classify the lane into these different categories or does it not depend more on the situation? 

Can you make a suggestion for an exact definition of this three types?

**Comment by LudwigFriedmannBMW** [comment]
I would not consider OSI to provide the information if a drivable lane is an emergency lane or not. This information might not be available in maps, either.
Therefore, I would suggest OSI provides information about traffic signs indicating this specific lane type, but not any information directly attached to the lane.

**Comment by LudwigFriedmannBMW** [comment]
If there are no further requests by the end of this week, I will close this issue.

**Comment by LudwigFriedmannBMW** [comment]
Issue closed
