### ISSUE TITLE
Sign 332 motorway exit announcement

### ISSUE THREAD

**Issue by StefanSudbrack** [OpenSimulationInterface/open-simulation-interface#221]
Hello,

a question / proposal arised modelling a driving scenario: We were looking for Sign 332 motorway exit announcement / Ausfahrttafel auf der Autobahn, but did not find it right away.

Is this sign missing, or should it rather be modelled based on another sign?

And based on that: If the sign shows that a highway exit ist closed or inaccessible (for instance with red bars over the sign), how is this to be modelled?

Thanks

**Comment by LudwigFriedmannBMW** [comment]
Hi @StefanSudbrack, these signs will be added by PR #258.

The case of "disabled" signs is not yet implemented. As this is a general topic that might all traffic signs, I'll create a new issue for that and close this issue.
