### ISSUE TITLE
Sign 439 direction sign (announcement)

### ISSUE THREAD

**Issue by StefanSudbrack** [OpenSimulationInterface/open-simulation-interface#222]
Hello,

a question / proposal arised modelling a driving scenario: We were looking for Sign 439 direction sign (announcement) /  "Gegliederter Vorwegweiser außerhalb von Autobahnen" , but did not find it right away.
Is this sign missing, or should it rather be modelled based on another sign?

Thanks

**Comment by LudwigFriedmannBMW** [comment]
Hi @StefanSudbrack, these signs will be added by PR #258.
Thus, I'll close this Issue.
