### ISSUE TITLE
Adjust description of centerline in osi_lane.proto

### ISSUE THREAD

**Issue by AndreHildebrandt** [OpenSimulationInterface/open-simulation-interface#225]
I think the center line as currently described is a bit outdated. The description should be adjusted.

Reason 1: The center line in the Ground Truth is described as ideal trajectory a vehicle should follow. However, on crossings no centerlines exist with the new lane model. This leads to the requirement for other models to be able handle situations without a center line, i.e. the center line is only a convenience feature and should be documented as such.
Reason 2: If a lane narrows (e.g. because of a cunstruction site), the center line highly depends on physical dimensions of the vehicles (mainly the width). It is questionable how reliable a center line then becomes.

**Comment by ppannusch** [comment]
I never read the documentation and didn't assume that it was meant to be the ideal line; now that I read the comment above I completely agree that it doesn't make sense.
The ideal trajectory highly depends on the situation. The name "center lane" suggests it is the center of the lane, what can be a helpful reference to localize within the lane and to find the ideal trajoctory.

In general, how exactly the center line looks like on narrowing, merging and splitting lanes is a little vague.

**Comment by ppannusch** [comment]
With the change from @carsten-kuebler, the whole center line comming from the simulator doesn't make sense anymore.
Especially 
// A vehicle must calculate this individually and depending on the 
// situation.
how should the simulator know this?

**Comment by CarloVanDriestenBMW** [comment]
This comment is correct for a "predicted" (meansurement state) lane in SensorData -> Camera would do this and predict a path over an intersection.

**Comment by CarloVanDriestenBMW** [comment]
@carsten-kuebler maybe we have to gather some example definitions?
[Road Centerline](http://www.richmondgov.com/GIS/documents/Centerlines_Documentation.pdf)

**Comment by carsten-kuebler** [comment]
@LudwigFriedmannBMW I made changes in the PR
