### ISSUE TITLE
Speed definition in ISO 23150 vs. OSI

### ISSUE THREAD

**Issue by CarloVanDriestenBMW** [OpenSimulationInterface/open-simulation-interface#234]
The OSI definition is the following:

> The relative velocity of the moving object w.r.t. its parent frame and parent velocity. The velocity becomes global/absolute if the parent frame does not move.
> 
> position (t) := position (t-dt)+ velocity *dt

The ISO says the following:

Parameter | Content | Data format | Unit
-- | -- | -- | --
X   velocity | Absolute velocity of the object   along the x-axis of the ego-vehicle coordinate system. |   | [m/s]
Y   velocity | Absolute   velocity of the object along the y-axis of the ego-vehicle coordinate system. |   | [m/s]
Z   velocity | Absolute   velocity of the object along the z-axis of the ego-vehicle coordinate system. |   | [m/s]
X acceleration | Absolute   acceleration of the object along the x-axis of the ego-vehicle coordinate   system. |   | [m/s²]
Y   acceleration | Absolute   acceleration of the object along the y-axis of the ego-vehicle coordinate   system. |   | [m/s²]
Z   acceleration | Absolute acceleration of the   object along the z-axis of the ego-vehicle coordinate system. |   | [m/s²]

**Comment by TimFrickeBMW** [comment]
It is important to note that the cited OSI definition relates to "optional Vector3d velocity" and that there is a corresponding "optional Vector3d acceleration". The OSI definitions clearly state that "velocity" and "acceleration" are both "relative".

The fact that the ISO (- which one are you referring to? I cannot find these definitions in ISO8855. - ) defines velocities and accelerations as "absolute" does not bother me. In fact, I find the term "absolute" too vague: absolute w.r.t. which frame? Which frame am I supposed to assume "inertial"?

Strictly speaking, two aspects need to be specified: the frame w.r.t. which each derivation d/dt is to be performed (e.g., acceleration is the position derived twice w.r.t. the host vehicle frame) and the frame in which the vector is noted. I think, both aspects are covered by the OSI definition, but I would nonetheless consider rephrasing in future releases for better clarity:

"The relative velocity of the moving object **w.r.t. the parent frame, noted in the parent frame**. The velocity becomes global/absolute if the parent frame does not move."

Apart from that, I wonder why the OSI definition continues with the following line:

"position (t) := position (t-dt)+ velocity *dt"

Does that mean that velocity is the position derived numerically with the finite difference method? Or that position is to be computed from velocity using the forward Euler method? I would scrap this definition. Depending on the simulation model, one may have access to velocity and acceleration themselves. This information is more valuable and reliable than the approximation with finite differences. Moreover, I don't think OSI is meant to specify methods of solving differential equations. If we think a formula is needed to exactly specify what the term "velocity" means here... well... I would not know how to put this in a readable form with ASCII text.

**Comment by CarloVanDriestenBMW** [comment]
ISO 23150

**Comment by TimFrickeBMW** [comment]
As I understand it, ISO 23150 ("Road vehicles -- Data communication between sensors and data fusion unit for automated driving functions -- Logical interface") is in development. To sum up, it specifies absolute velocities & accelerations, noted in the ego vehicle frame.

OSI specifies:
* For ground truth: absolute velocities & accelerations, noted in an inertial frame. ("All coordinates and orientations from ground truth objects are relative to the global ground truth frame." I am assuming here that the ground truth frame can be considered stationary, i.e., unaccelerated and not moving.)
* For detected objects: relative velocities & accelerations, noted in the ego vehicle frame. ("All coordinates and orientations (...) are relative to the host vehicle frame.")

In each case, only half of the OSI definition is consistent with ISO 23150.

No sensor can perceive absolute velocities and accelerations of foreign objects without information about its own movement. Absolute velocities and accelerations are therefore part of an ideal ground truth or the result of data fusion. So, to me, the OSI definition makes much more sense than the ISO 23150 definition.

(I should note, though, that I am not sure how, for example, an inertial measurement unit in the ego vehicle, which measures absolute accelerations, fits into this picture.)

**Comment by carsten-kuebler** [comment]
"Absolute velocity" in ISO 23150 means that the measurement method is not ambiguous. It is the relative velocity between vehicle and object (in the sensor frame) measured absolute and not relative/ambiguous (in the sensor frame). The definition will be adapted in ISO.

**Comment by carsten-kuebler** [comment]
@LudwigFriedmannBMW I recommend nothing to adjust in OSI. Do you agree?

**Comment by LudwigFriedmannBMW** [comment]
There are two reasons for the varying definitions:
- In OSI, we're using this definiton with respect to multiple reference frames
- The ISO definition of 'absolute' is not based on a inertial frame

In my opinion, the 'absolute' in the ISO definition should be either removed or replaced with 'relative'.

For OSI, I recommend extending the definition like proposed by @TimFrickeBMW:

"The relative velocity of the moving object w.r.t. the parent frame, noted in the parent frame. The velocity becomes global/absolute if the parent frame does not move."

**Comment by LudwigFriedmannBMW** [comment]
Fixed by PR #267
