### ISSUE TITLE
Double Definition: Curb and Curbstone

### ISSUE THREAD

**Issue by CarloVanDriestenBMW** [OpenSimulationInterface/open-simulation-interface#235]
Curb and Curbstone are defined in Lanes and StationaryObjects. I think it should only be in Lanes because it is a LaneBoundary?

**Comment by HendrikAmelunxen** [comment]
I don’t think that this is a bug. Of course, curbs along a lane should be defined as laneboundary. But for single objects, like curbstones at parking spaces, a curbstone border at trees or at narrow pedestrian crossings etc. it would be helpful to keep the curbstone definition in StationaryObjects either.

**Comment by ppannusch** [comment]
I agree to the example of curbstone around trees, probably important at some point in the future, and not always going to be a LaneBoundary..
