### ISSUE TITLE
Extension suggestion to support Innoviz scanning Lidar

### ISSUE THREAD

**Issue by kolodkin** [OpenSimulationInterface/open-simulation-interface#236]
Hi. 

attached is a recommendation for an extension for OSI which will provide support for Innoviz Lidar.
please review osi_invz_lidar.proto in attached.

about Innoviz:
Innoviz is a leading provider of cutting-edge LiDAR remote sensing solutions to enable the mass commercialization of autonomous vehicles. The company’s LiDAR products deliver superior performance at the cost and size required for mass market adoption. Available now, InnovizPro™ offers unrivaled angular resolution at the highest frame rate of any LiDAR solution currently on the market. The company’s automotive-grade LiDAR offering a comprehensive mass-market solution, InnovizOne™, will be available in 2019. Headquartered in Israel, the company was founded in January 2016 by former members of the elite technological unit of the Israeli Defense Forces with renowned expertise in the fields of electro-optics, computer vision, MEMS design and signal processing. Innoviz is backed by strategic partners and top-tier investors including Aptiv (Delphi Automotive), Magna International, Samsung Catalyst, SoftBank Ventures Korea, 360 Capital Partners, Glory Ventures, Naver, and others.
for more information -> https://www.innoviz.tech

[invz_osi_0.1.1.zip](https://github.com/OpenSimulationInterface/open-simulation-interface/files/2023700/invz_osi_0.1.1.zip)

Innoviz Lidar OSI extension recommendations for providing comparability of innoviz Lidar with OSI. 
The major changes vs existing implementation (OSI v3.0.1) are:
1. SensorViewConfiguration is not necessary. InvzSensorParams need to be read from the device. this data structure contains the scan raster direction and timing within each frame.
2. InvzLidarSensorView: suggested instead osi_sensorview.proto -> SensorView -> LidarSensorView
3. InvzLidarDetection: suggested instead osi_featureddata.proto -> LidarDetection -> LidarDetectionData

**Comment by CarloVanDriestenBMW** [comment]
Thank you very much for your contribution! We may have to find a way to format and discuss your proposal in a way it is more "generic". It would be hard to sell to other Lidar suppliers who should all in general use this generic interface to work on messages that are named *invz*. We will analyse it as fast as we can.

**Comment by LudwigFriedmannBMW** [comment]
Hi @kolodkin, is this PR still relevant?
I think we discussed to split it into smaller parts like #273.
Is this a way to go for you?
