### ISSUE TITLE
Double definition of data structurers

### ISSUE THREAD

**Issue by mbencik999** [OpenSimulationInterface/open-simulation-interface#240]
I the DetectedTrafficSign has 4 possible member objects are created through the definition in the protobuf.
                class DetectedTrafficSign
		class DetectedTrafficSign_DetectedMainSign
		class DetectedTrafficSign_DetectedMainSign_CandidateMainSign
		class DetectedTrafficSign_DetectedSupplementarySign
		class DetectedTrafficSign_DetectedSupplementarySign_CandidateSupplementarySign

The question that i have is it possible that the Supplementary Sign stands alone. If yes the OSI definition could stand, if no than the definition has unnecessary overhead. 

The traffic sign in that case can be thrown away and the Main traffic Sign can be the owner of the Supplementary Sign by this eliminating one level of indirection and a bit weird definition.

**Comment by LudwigFriedmannBMW** [comment]
Although supplementary signs cannot stand alone, they can still be recognized by the sensor without the associated main sign. Therefore, I would leave the definition as it is.
If no further questions arise by Friday 10 August, I would close this issue.

**Comment by LudwigFriedmannBMW** [comment]
After no further questions have been asked I close the issue.
