### ISSUE TITLE
Supplementary Sign Documentation

### ISSUE THREAD

**Issue by ecazaubon** [OpenSimulationInterface/open-simulation-interface#241]
Hello,
Would it be possible to update documentation for Supplementary Sign Types with StVO Indexes ?

Also what is this supplementary sign ? 
https://github.com/OpenSimulationInterface/open-simulation-interface/blob/c504e328410b1f0534bae9a559f6538eaa74aecd/osi_trafficsign.proto#L1133-L1135
Is this the StVO 1010-61 (Tractors and vehicles under 25 km/h may pass)?
The comment and enum name are confusing.

**Comment by LudwigFriedmannBMW** [comment]
This description is misleading. From the naming, I would guess it is  1049-11 (tractors may be passed).
In contrast, StVO 1010-61 would indicate that the main sign of this supplementary sign is valid only for tractors. This seems to be more appropriate concerning the entries before and after this entry.

However, a large enhancement for the osi_trafficsign.proto is planned for OSI 3.1.0.
Therefore, I will postpone this issue to this release.

**Comment by LudwigFriedmannBMW** [comment]
This issue will be solved by #258.
Thus, I'll close it.
