### ISSUE TITLE
Instalation of osi3 python bindings on Ubuntu

### ISSUE THREAD

**Issue by cszyszka** [OpenSimulationInterface/open-simulation-interface#242]
If someone needs to create python binding for osi3 he/she needs to modify setup.py to the example below. 

The key line in  `'--proto_path=/usr/include'`, as the compiler was not informed where descriptor.proto is located. 

Ideally the script should be modified to detect the location of the library independently form operation system. 

```
def run(self):
        for source in self.osi_files:
            sys.stdout.write('Protobuf-compiling ' + source + '\n')
            subprocess.check_call([self.find_protoc(),
                                   '--proto_path=.',
                                   '--proto_path=/usr/include',
                                   '--python_out=' + package_path,
                                   './' + source])

```
Found this fix on https://stackoverflow.com/questions/20069295/importing-google-protobuf-descriptor-proto-in-java-protocol-buffers

**Comment by CarloVanDriestenBMW** [comment]
@jr7 does this help you?

**Comment by jr7** [comment]
I think the above issue is more related to  the ubuntu setup, not python3 specific ?

**Comment by LudwigFriedmannBMW** [comment]
Since no one has spoken for almost two months, I will close the issue.
