### ISSUE TITLE
MPL header missing

### ISSUE THREAD

**Issue by raueATconti** [OpenSimulationInterface/open-simulation-interface#247]
- missing MPL header in source files; should it be added or is it considered to be sufficient putting the whole project under MPL?

**Comment by LudwigFriedmannBMW** [comment]
I think you're right. According to the website, the license header must be added to each source code file: https://www.mozilla.org/en-US/MPL/2.0/FAQ/

**Comment by LudwigFriedmannBMW** [comment]
According to [processwire](https://processwire.com/about/license/mpl/),

> If it is not possible or desirable to put the notice in a particular file, then You may include the notice in a location (such as a LICENSE file in a relevant directory) where a recipient would be likely to look for such a notice.

Therefore, this issue is obsolete and my be closed.
