### ISSUE TITLE
platform independent setup.py 

### ISSUE THREAD

**Issue by raueATconti** [OpenSimulationInterface/open-simulation-interface#252]
currently applying setup.py on windows doesn't work properly, due to chosen linux path delimiter inside the script (i.e. /).
In order to become platform independent (i.e. linux and windows) determination of os environment and setting the path delimiter accordingly would be desired.

**Comment by pmai** [comment]
Hmmm, as far as I can tell, setup.py is working for me on Windows (as far as the delimiters are concerned; for Python3 we still have the issue #243), since Python seems to handle the delimiter mapping?

**Comment by raueATconti** [comment]
after re-setup of system (incl. python) problem has disappeared; issue can be closed;
