### ISSUE TITLE
Installation And Running for the first time!

### ISSUE THREAD

**Issue by mshaheerm** [OpenSimulationInterface/open-simulation-interface#253]
Hello, I am new to OSI and have no idea what it is and how to install it and run. i installed few of the things but is there any proper "Getting Started" or "Quick Start"? Which file do i have to run and all. i am sorry for my so lame argument but i need OSI to use in my task and i have no idea what its all about.

**Comment by CarloVanDriestenBMW** [comment]
Hi,
we are currently working on making it more "first user friendly":
[Build Instructions](https://github.com/OpenSimulationInterface/open-simulation-interface/wiki/Building-and-installation)

[Online Documentation](https://opensimulationinterface.github.io/open-simulation-interface/)

[Readme for model types and packaging](https://github.com/OpenSimulationInterface/osi-sensor-model-packaging)

**Comment by mshaheerm** [comment]
![capture](https://user-images.githubusercontent.com/40594242/42496589-dc044932-8426-11e8-9c21-28eb31b48517.JPG)
when i try to build the protobuf.sln these errors occurs. what should i do?

**Comment by mshaheerm** [comment]
![capture](https://user-images.githubusercontent.com/40594242/42497107-6e5c3ad2-8428-11e8-8473-6f72105c482c.JPG)
these are the left ones. how to fix them?

**Comment by CarloVanDriestenBMW** [comment]
Define the value as statet in the warning. You can also use a newer protobuf version and check if this has been fixed.

**Comment by mshaheerm** [comment]
![capture](https://user-images.githubusercontent.com/40594242/42499671-ae70f08e-842f-11e8-9eb9-f48b382a87ec.JPG)
Thank you for your help. i did those errors fix as you said. but when i install osi these errors are thrown. how can i fix them

**Comment by mshaheerm** [comment]
what should i do now?

**Comment by pmai** [comment]
It looks like you are trying to link a 32-bit ProtoBuf lib into a 64-bit build... Don’t do that ;). Depending on what you are trying to achieve you will either have to use a 64-bit build of libprotobuf, or switch your OSI target to 32-bit (using either CMake or the VS settings).

**Comment by mshaheerm** [comment]
Thankyou for your help. i really appreciate it. i have done it and there were zero build errors. OSI is created.
![capture](https://user-images.githubusercontent.com/40594242/42558021-51191bd4-84f0-11e8-9170-ad463190706e.JPG)
what shall i do now? what shall i run now? i am so sorry i am completely new to this thats why i am being so lame.

**Comment by mshaheerm** [comment]
![capture](https://user-images.githubusercontent.com/40594242/42558650-312c56e0-84f2-11e8-8ad7-69802bedb701.JPG)
I tried to run it from Qt Creator but these errors are shown.

**Comment by mshaheerm** [comment]
@pmai  @CarloVanDriestenBMW  
can you please explain what is "desired <path-to-proto2cpp.py>" ?? where shall i copy the proto2cpp repo content in?
