### ISSUE TITLE
Proto to Python Compilation FAILED!!

### ISSUE THREAD

**Issue by mshaheerm** [OpenSimulationInterface/open-simulation-interface#256]
![capture](https://user-images.githubusercontent.com/40594242/42747978-b45cc802-88de-11e8-8b05-02744f82a783.JPG)

i am trying to convert the proto files but some of them are depending on one another. how can i build them? and when i compile osi_version.proto it throws the error above

**Comment by pmai** [comment]
The protofile you are missing is distributed with your protobuf installation, hence you need to include the path to google/protobuf/descriptor.proto with -I on the command line.

**Comment by mshaheerm** [comment]
yeah its done.. can be closed.
