### ISSUE TITLE
SensorView vs SensorData

### ISSUE THREAD

**Issue by AndreasStark** [OpenSimulationInterface/open-simulation-interface#262]
I didn't really find a good documentation on the conceptual difference between SensorView and SensorData except this: 

> [This commit completely seperates SensorView as the new input interface for sensor models from SensorData as the output interface for sensor models. ](https://github.com/OpenSimulationInterface/open-simulation-interface/pull/179/commits/2625821dd76074dbf7f0becb02d49d7afd1e6cd8)

It'd be great if someone with more insight could point out how these two interfaces differ. 

Thanks in advance

**Comment by LudwigFriedmannBMW** [comment]
Good morning, relevant information on **SensorView** may be found in osi_sensorview.proto or the corresponding [documentation](https://opensimulationinterface.github.io/open-simulation-interface/structosi3_1_1SensorView.html):

> The sensor view is derived from GroundTruth and used as input to sensor models. The sensor view information is supposed to provide input to sensor models for simulation of actual real sensors. All information regarding the environment is given with respect to the virtual sensor coordinate system specified in SensorView::mounting_position, except for the individual physical technology-specific data, which is given with respect to the physical sensor coordinate system specified in the corresponding physical sensor's mounting_position, and the global_ground_truth, which is given in global coordinates. When simulating multiple distinct sensors, each sensor can consume an individual copy of the SensorView interface. This allows an independent treatment of the sensors. Alternatively combined sensor models can also consume one combined SensorView, with either combined or separate SensorData outputs, depending on model architecture. 

**SensorData** is defined by osi_sensordata.proto. The [documentation](https://opensimulationinterface.github.io/open-simulation-interface/structosi3_1_1SensorData.html) states:

> The sensor information derived from GroundTruth and processed by sensor-models. The sensor information is supposed to imitate the output of real sensors. All information regarding the environment is given with respect to the virtual sensor coordinate system specified in SensorData::mounting_position, except for feature data, which is given with respect to the physical sensor coordinate system specified in the corresponding physical sensor's coordinate system. When simulating multiple distinct sensors, each sensor can produce an individual copy of the SensorData interface. This allows an independent treatment of the sensors. Sensor fusion models can consolidate multiple SensorData interfaces into one consolidated SensorData interface. This can happen either in seperate logical models, consuming and producing SensorData interfaces, or it can happen as part of a combined sensor/logical model, that consumes SensorView interfaces and directly produces one consolidated SensorData output. 

Please let me know if you need further information.

**Comment by AndreasStark** [comment]
Thanks for the fast reply. This is quite helpful. Digging around in the[ class diagram](https://opensimulationinterface.github.io/open-simulation-interface/structosi3_1_1SensorData.html) I see that the SensorData does reference repeated SensorView.

Just for sanity checking:
So in contrast to the [2017 presentation slide 4](https://www.hot.ei.tum.de/fileadmin/tueihot/www/Forschung/OSI_description.pdf) it's now more like
GroundTruth -> Converter -> SensorView -> Sensor Model -> SensorData -> Sensor fusion function -> SensorData

If it's a combined sensor model it can take in a SensorView and output combined or multiple SensorData.

Sensor fusion functions take in combined or multiple SensorData and consolidate into the fusion SensorData. Alternatively there could be a combined sensor and fusion model which takes in combined or multiple SensorView (and maybe also SensorData?) and consolidates into one SensorData.

Please let me know if these assumptions are correct.

Thanks in advance

**Comment by LudwigFriedmannBMW** [comment]
You're right, the model has changed.

As you described, in the data flow, the sensor data fusion or logic models is located "behind" the sensor models.

Input of one or more sensor models is SensorView (which is e.g. depending on the sensors' mounting position). Output of the sensor models is SensorData. The latter may be post-processed or fusioned into a new SensorData.
