### ISSUE TITLE
Proposal for the usage of arena allocation

### ISSUE THREAD

**Issue by mbencik999** [OpenSimulationInterface/open-simulation-interface#268]
My proposal is to use arena allocation in the Protobuf to speed up the allocation process for messages. The reason for that some users will create quite large messages 6Mb or more ad it would be good to have such a system in place.

**Comment by pmai** [comment]
Since the decision to use arena allocation or not is local to the user code, each OSI user can decide on its own which allocator and allocation scheme to use, optimizing for expected message sizes, etc.

**Comment by LudwigFriedmannBMW** [comment]
I share the opinion of @pmai. Performance optimization measures like arena allocation should be implemented rather in a user-specific than in a standardized way.
