### ISSUE TITLE
Proposal for the Protobuf replacement

### ISSUE THREAD

**Issue by mbencik999** [OpenSimulationInterface/open-simulation-interface#269]
Since protobuf is not flexible in respect of reading single fields from the messages, one option would be to use Cap'N Proto to replace Protobuf to read single fields from a message.

https://stackoverflow.com/questions/25187518/protobuf-file-reading-only-some-field

**Comment by pmai** [comment]
See discussion in #56; many of the replacements for Protobuffers would allow efficient access to single fields, some also efficient mutation of single fields, which in the context of sensor models would be a huge win (e.g. FlatBuffers). However a decision on this front will likely depend more on upcoming harmonization efforts across standards in this field...

**Comment by CarloVanDriestenBMW** [comment]
closing because of duplicate
