### ISSUE TITLE
Version indicator interferences

### ISSUE THREAD

**Issue by LudwigFriedmannBMW** [OpenSimulationInterface/open-simulation-interface#270]
It seems there are interferences between protobuf version indicators 'major' and 'minor' and C lib defines:

https://github.com/protocolbuffers/protobuf/issues/4654
https://github.com/protocolbuffers/protobuf/issues/3203

I'm aware that this is a protobuf related issue. Nevertheless, it would be good to come up with a solution.

**Comment by mbencik** [comment]
Well just change the name to something meaningful. That problem is not solvable because the google developers are adding new macros and deprecating stuff, so the best solution would be to change the names.

**Comment by CarloVanDriestenBMW** [comment]
Somebody must have used an old version of OSI because the issue has been resolved by renaming to e.g. "VERSION_MINOR". I am closing this issue for now.
