### ISSUE TITLE
Canceled/crossed-out traffic signs

### ISSUE THREAD

**Issue by ghost** [OpenSimulationInterface/open-simulation-interface#274]
"Disabled" traffic signs are not yet implemented. This might be the case e.g. when a highway exit ist closed or inaccessible (which is illustrated for instance with red bars over the sign). We have to find a way to model that.

**Comment by CezarySzyszkaAltran** [comment]
Both MainSign and SupplementarySign in osi_trafficsign.proto have field 
classification.variability of type TrafficSign::Variability.

My suggestion for solution of this issue would be to add to enum Variability 
```
 // Temporary or variable sign, e.g. on a sign bridge.
 //
VARIABILITY_DISABLED = 4;
// or VARIABILITY_SIGN_INACTIVE = 4;

```
My concern over this solution is if it is not abusing enum Variability type?

**Comment by CezarySzyszkaAltran** [comment]
I believe we can apply the same principle to the RoadMarking (file osi_roadmarking.proto) 

In case there is a road marking crossed over (example 1. ) we can indicate it with Boolean flag or similar enum type as in osi_trafficsign.proto. I'm not sure about the scenario when road markings are conflicting with each other (example 2.). Should we leave this for interpretation of OSI user to infer which road marking supersedes which? 

Possible solution would be to ass to osi_roadmarking.proto, message RoadMarking.Classification field 
```
// Flag indicating if a road marking is temporarily disabled 
// (e.g. due to construction site proximity )
//
optional bool is_disabled
// alternatively is_valid, is_inuse or  is_active

```

example 1.
![img_0170](https://user-images.githubusercontent.com/44769837/50151747-0f975e00-02c2-11e9-8d9c-e004aadead8d.jpg)

example 2.
![img_0171](https://user-images.githubusercontent.com/44769837/50151756-1c1bb680-02c2-11e9-9731-e6458e46be2d.jpg)

**Comment by CarloVanDriestenBMW** [comment]
@LudwigFriedmannBMW what do you think? if @CezarySzyszkaAltran proposes a PR until Thursday evening we can integrate it in the 3.1.0 release?

**Comment by LudwigFriedmannBMW** [comment]
Hi @CarloVanDriestenBMW , if it's not too late - I'd be fine with the solution proposed by @CezarySzyszkaAltran.

**Comment by CarloVanDriestenBMW** [comment]
@LudwigFriedmannBMW sorry I have to release now - we will do this in the next release!

**Comment by CezarySzyszkaAltran** [comment]
Sorry I didn't make it one time. If I should to propose a PR. To which branch? master?

**Comment by CarloVanDriestenBMW** [comment]
Give the branch a proper name and make a PR to the master referencing this issue in order to auto close it on merge.
