### ISSUE TITLE
Add angular acceleration to BaseMoving class in osi_common.h

### ISSUE THREAD

**Issue by TBreitenbergerConti** [OpenSimulationInterface/open-simulation-interface#279]
Second derivation in time of orientation is missing. I would suggest to add this as counterpart to accelleration for position. 
As suitable name I would propose orientation_acceleration, since something_with_rate_rate would be too confusing.

**Comment by LudwigFriedmannBMW** [comment]
Hi @TBreitenbergerConti, this sounds good to me, please set up a corresponding pull request. If this change is planned for OSI 3.1.0, the field number should be chosen larger than the largest existing field number. The coalescence of the fields can be corrected in OSI 4.0.0.

**Comment by LudwigFriedmannBMW** [comment]
Hi @TBreitenbergerConti, if you set up a corresponding PR within the next days, we can consider the issue for OSI 3.1.0. Otherwise, I'll postpone it to OSI 4.0.0.
