### ISSUE TITLE
ISO 23150 standard available

### ISSUE THREAD

**Issue by tik0** [OpenSimulationInterface/open-simulation-interface#280]
I want to dig into your OSI due to a sensor fusion related project. In your release messages, you write that you want want to narrow your approach to ISO 23150. Unfortunately, this standard is still in development and unable to obtain. Is there any possibility to get a draft of the standard to follow your approach?

**Comment by CarloVanDriestenBMW** [comment]
Hi, we have to ask @carsten-kuebler if there are drafts publically available. Otherwise the implementation here is the closest what you can currently get to easily grasp the upcoming standard :)

**Comment by LudwigFriedmannBMW** [comment]
Hi @carsten-kuebler, can you state something on this issue?

**Comment by CarloVanDriestenBMW** [comment]
@tik0 the information I got so far:
The standard is in the process of being formulated and released within the next ~2 years. The intermediate discussion is only available for the people participating in the work group. If the standard is released it can be bought the same way as all ISO standards. The current state would be: You have to trust that the Github represents the current state of the discussion (adding that @carsten-kuebler is a member) - I am sorry to have to give you this answer...
