### ISSUE TITLE
Add traffic signs to osi documentation

### ISSUE THREAD

**Issue by carsten-kuebler** [OpenSimulationInterface/open-simulation-interface#281]
Traffic sign images from 

https://www.bast.de/BASt_2017/DE/Verkehrstechnik/Fachthemen/v1-verkehrszeichen/vz-download.html;jsessionid=922FB16AE6C58C3FB8B4D3255965D060.live11293?nn=1817946

are free to use. 

Should we add this images to the osi repo. We got positive feedback from BAST to use the official german images. They are free from any copyright.

**Comment by CarloVanDriestenBMW** [comment]
@LudwigFriedmannBMW 
I think it would be a good idea? Can you link them dynamically in order to avoid copying all images into the repo?

**Comment by LudwigFriedmannBMW** [comment]
Hi @carsten-kuebler and @CarloVanDriestenBMW, I would definitely support an illustration of the documentation concerning traffic signs. It helps to avoid misunderstandings.
If there is a way to avoid copies, we should take advantage of it.

**Comment by CarloVanDriestenBMW** [comment]
- split images in subfolders for better overview
- add Readme to images folder with licence and reference explanations with rerlation to images
