### ISSUE TITLE
Unable to import generated.py from a folder

### ISSUE THREAD

**Issue by mshaheerm** [OpenSimulationInterface/open-simulation-interface#282]
I am working with a module.py which is present in `C:\Users\sham\newcarla\carla\PythonClient` and have copied all the generated proto_to_python.py in `C:\Users\sham\newcarla\carla\PythonClient\proto_generated` but there is an import error. i tried running the setup.py in `C:\Users\sham\Downloads\open-simulation-interface-master\open-simulation-interface-master`  and it created a folder `osi3` which just has __init__.py in it. How can i use it as a package for my imports? Thanks in advance

**Comment by pmai** [comment]
I can't tell you anything about carla/PythonClient, but the python files for osi can be generated normally using the python setup-tools approach, i.e. python setup.py build will build everything in build/lib/*, python setup.py sdist will create a software distribution in dist, and/or python setup.py install will do a full local install.

**Comment by pmai** [comment]
I'm not sure what you are trying to do: If you just want to import osi3 stuff, then once it has been installed via python setup.py install, it will already be on your python path, and available normally. If you want to create built distributions that you can distribute/install on other machines, it works the same way for all python packages using setuptools: python setup.py bdist_egg for an egg archive or python setup.py bdist_wheel for the newer whl archive format.

Maybe this is more of a question for carla/PythonClient (whatever that is)?

**Comment by mshaheerm** [comment]
The import problem still persists i am trying to import `osi_grountruth_pb2` in my `module.py` but still there's a problem in importing. even after adding `..\osi3` to the environment variable

**Comment by pmai** [comment]
Which version of Python are you using, how do you import the module, and what error message do you get? (Useful info to provide if something does not work...)

```
import osi3.osi_groundtruth_pb2
```

should work correctly if the package is installed and hence on the python path.

**Comment by mshaheerm** [comment]
@pmai  sorry for the late reply. this is how i am importing from `osi3`

```
import osi3.osi_groundtruth_pb2
import osi3.osi_grpc_pb2_grpc
```
and these are the errors generated when i try to run `osi_grpc_communication_module.py`
```
Traceback (most recent call last):
  File "C:/Users/sham/newcarla/carla/PythonClient/osi_grpc_communication_module.py", line 27, in <module>
    import osi3.osi_groundtruth_pb2
  File "C:\Users\sham\newcarla\carla\PythonClient\osi3\osi_groundtruth_pb2.py", line 18, in <module>
    from osi3 import osi_trafficsign_pb2 as osi3_dot_osi__trafficsign__pb2
  File "C:\Users\sham\newcarla\carla\PythonClient\osi3\osi_trafficsign_pb2.py", line 25, in <module>
    dependencies=[osi3_dot_osi__common__pb2.DESCRIPTOR,])
  File "C:\Users\sham\Anaconda3\lib\site-packages\google\protobuf\descriptor.py", line 878, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "osi_trafficsign.proto":
  osi_trafficsign.proto: Import "osi3/osi_common.proto" has not been loaded.
  osi3.TrafficSign.MainSign.Classification.assigned_lane_id: "osi3.Identifier" seems to be defined in "osi_common.proto", which is not imported by "osi_trafficsign.proto".  To use it here, please add the necessary import.
  osi3.TrafficSign.MainSign.base: "osi3.BaseStationary" seems to be defined in "osi_common.proto", which is not imported by "osi_trafficsign.proto".  To use it here, please add the necessary import.
  osi3.TrafficSign.SupplementarySign.Classification.assigned_lane_id: "osi3.Identifier" seems to be defined in "osi_common.proto", which is not imported by "osi_trafficsign.proto".  To use it here, please add the necessary import.
  osi3.TrafficSign.SupplementarySign.base: "osi3.BaseStationary" seems to be defined in "osi_common.proto", which is not imported by "osi_trafficsign.proto".  To use it here, please add the necessary import.
  osi3.TrafficSign.id: "osi3.Identifier" seems to be defined in "osi_common.proto", which is not imported by "osi_trafficsign.proto".  To use it here, please add the necessary import.
```

**Comment by mshaheerm** [comment]
it was a protobuf error. I fixed it using 
```
pip uninstall protobuf
pip install --no-binary=protobuf protobuf
```
