### ISSUE TITLE
Change CI process, old one is deprecated

### ISSUE THREAD

**Issue by ghost** [OpenSimulationInterface/open-simulation-interface#283]
![grafik](https://user-images.githubusercontent.com/25304009/47147601-e9a80a00-d2ce-11e8-9386-afe1a4a9297a.png)

**Comment by CarloVanDriestenBMW** [comment]
@carsten-kuebler this should be done this year. Please document the changes in the Wiki in order to replicate what you did and how you setup the documentation autobuild etc. Thank you!

**Comment by vkresch** [comment]
Closing since we now use travis-ci.
