### ISSUE TITLE
Question: protobuf file location

### ISSUE THREAD

**Issue by sebsonf** [OpenSimulationInterface/open-simulation-interface#304]
Hi, could you please tell me where can I find the remaining protobuf files mentioned in the doxygen documentation?

specifically I am looking for 
- osi3::RadarDetectionData
- osi3::RadarDetection

**Comment by pmai** [comment]
Those messages are defined in osi_featuredata.proto.

**Comment by CarloVanDriestenBMW** [comment]
It can always be seen at the bottom of the documentation:
![image](https://user-images.githubusercontent.com/25304009/51173501-d8629f80-18b5-11e9-9737-89b3d2de2ba6.png)

**Comment by sebsonf** [comment]
Thanks for the fast response!
