### ISSUE TITLE
Add velocity to LidarDetection

### ISSUE THREAD

**Issue by hansen-matt** [OpenSimulationInterface/open-simulation-interface#307]
`message LidarDetection` in [osi_featuredata.proto](https://github.com/OpenSimulationInterface/open-simulation-interface/blob/master/osi_featuredata.proto) does not currently support any way to report the velocity of a Lidar return. FMCW lidars give doppler velocity as part of the detection methodology; pulsed lidars may compute a 3d velocity.

I've just begun looking at this project; do you prefer issues like this or pull requests? There are several fields that would be useful to add for lidar support.

**Comment by LudwigFriedmannBMW** [comment]
Hi @hansen-matt, if you have a concrete idea concerning the implementation of the parameters, please feel free to start a pull request.

**Comment by LudwigFriedmannBMW** [comment]
Hi @hansen-matt, is this issue still of interest for you?
