### ISSUE TITLE
Doxygen: Multiple entries for enum types

### ISSUE THREAD

**Issue by ghost** [OpenSimulationInterface/open-simulation-interface#314]
The [link to online Doxygen Documentation](https://opensimulationinterface.github.io/open-simulation-interface/structosi3_1_1StationaryObject_1_1Classification.html) shows that the enum type entries have duplicates:

![grafik](https://user-images.githubusercontent.com/25304009/55536299-afce9280-56b9-11e9-9f72-ed76b89ef252.png)

**Comment by vkresch** [comment]
Resolved https://github.com/OpenSimulationInterface/open-simulation-interface/pull/340
