### ISSUE TITLE
Range of bool shape_classification_background

### ISSUE THREAD

**Issue by ainar** [OpenSimulationInterface/open-simulation-interface#327]
The attribute `shape_classification_background` of CameraDetection message type has an expected range in documentation, that is nonsense for a boolean that can only be 0 or 1. This may be an oversight.

https://github.com/OpenSimulationInterface/open-simulation-interface/blob/71310dd0f5c1ca0aac02d9e52db4f87640d0e26e/osi_featuredata.proto#L642

**Comment by CarloVanDriestenBMW** [comment]
#329 fixed this
