### ISSUE TITLE
"osi_lane.proto" comment clarification

### ISSUE THREAD

**Issue by CarloVanDriestenBMW** [OpenSimulationInterface/open-simulation-interface#33]
The comment may need some clairification :

    /// The lane's left adjacent lanes (w.r.t. intended driving direction).
    /// Example: The lane id 2.
    repeated Identifier left_adjacent_lane_id = 5;

    /// The lane's right adjacent lanes (w.r.t. intended driving direction).
    /// Example: The lane ids 4 and 7.
    repeated Identifier right_adjacent_lane_id = 6;

**Comment by TimoHankeBMW** [comment]
#44
