### ISSUE TITLE
Clarification: How to store OSI messages in a file

### ISSUE THREAD

**Issue by ghost** [OpenSimulationInterface/open-simulation-interface#330]
There is an issue in the OSI visualizer and I sometimes receive these questions regarding "how to store the messages in a file" [Link to existing issue](https://github.com/OpenSimulationInterface/osi-visualizer/issues/30).
We could consider providing a "best practice" for this in the readme?

**Comment by CarloVanDriestenBMW** [comment]
[Possible best practice](https://stackoverflow.com/questions/9148878/google-protocol-buffers-storing-messages-into-file)

**Comment by CarloVanDriestenBMW** [comment]
@mbencik what do you think?

**Comment by mbencik** [comment]
We can reference this as a possible solution int he documentation. But I would advise against it to integrate into OSI visualizer. It should stay purely a playback tool. One thing would be to write a very basic and primitive recording tool and to publish it, then everybody can modify it to his wishes.

**Comment by mbencik** [comment]
OSI is stored serialized, meaning that the messages do not have a beginning and a ending that is arbitrary. No type or version definition is visible from  outside unless we define it, again arbitrary. So the recording procedure is a arbitrary process regarding message delimiters and typification.

**Comment by vkresch** [comment]
Resolved https://github.com/OpenSimulationInterface/open-simulation-interface/pull/358
