### ISSUE TITLE
Critical section mark

### ISSUE THREAD

**Issue by mbencik** [OpenSimulationInterface/open-simulation-interface#336]
There have been some thoughts about introducing critical sections into the OSI standard. The reason is to mark a section of a scenario as critical. That in my case would mean that the individual messages can not be discarded and have to be processed. Now the problem with this idea is to what does this apply to in the OSI. My idea is that only the safety critical things can define a critical section. For example if a crash is about to happen.

**Comment by mbencik** [comment]
The possible solution 

message SensorView
{
    bool Critical_section;
}

or 

message SensorView
{
    enum critical_section status;
}

enum critical_section
        {
            // Started
            //
            START = 0;

            // Any other type of lane.
            //
            RUNNING = 1;

            // A normal lane.
            // Example: Lanes with IDs l1, l2, l3, l4 and l6 in image \ref
            // HighwayExit.
            //
            STOP = 2;
        }

One constraint that I would add that the critical section cannot be shorter than 200 ms, and the gap between two critical sections cannot be shorter than 200 ms.

**Comment by pmai** [comment]
I'm still unsure what the intent here is: Handling or not handling a message seems outside of the scope of the standard, similarly, I don't think this is information the sensor model should be processing. I'd rather assume that this is information for measuring/logging mechanisms, and hence maybe should be placed at the transport level or communicated using some other mechanism? Given that we do not even have portable mechanisms of triggering such things in scenario description languages, this seems like something that could be handled by user extensions, if people insist on putting that into the actual messages.

Could you provide some architectural description how this information is to be used (i.e. which part of the overall system would be using it for what purposes)?

**Comment by mbencik** [comment]
The whole purpose of this is not handling or not handling a message, and you cannot move this idea to some other level it is par of the scenario that it describes. The reason is one person is developing a scenario if he feel that some section has particular weight or significance he should be able to flag this. 
There can be a million reasons why this would happen. For example a crash is eminent or environment conditions on the road or thick fog or something else. This makes handling the scenarios between the different simulation tools not open to interpretation. If the tool misses something the in the critical section the simulation can be considered false and has to be repeated.
And that makes the rules of usage for all parties the same.

**Comment by jdsika** [comment]
It is very important to not mix the Scenario with OSI. An osi trace file e.g. is not a scenario, it is a timestamped series of "snapshots/scenes" defined by a section around a host vehicle. The sceanrio description may contain more information regarding the overall development and process of the initial situation as the time stamped series which has no claim of completeness.

Critical would also involve an evaluation of what is happening. The interpretation is very much depending on the observer. If you have very good brakes a time to collision may not be as crititcal as if you break flint stones style ;)
I am closing this issue and would recommend looking at the upcoming OpenSceanrio 1.0 release for marking specific sections of a sceanrio.
