### ISSUE TITLE
Duplicate entries in the doxygen documentation

### ISSUE THREAD

**Issue by vkresch** [OpenSimulationInterface/open-simulation-interface#339]
Currently there is a bug in the doxygen documentation in which enum types have duplicate display. See screenshot below from [here](https://opensimulationinterface.github.io/open-simulation-interface/structosi3_1_1EnvironmentalConditions.html):
![Selection_015](https://user-images.githubusercontent.com/14346967/63920719-bcc19900-ca41-11e9-84f3-c45462e64adb.png)

**Comment by vkresch** [comment]
Solution:
Exclude osi3 folder from doxygen generation since doxygen searches recursively for comments in open-simulation-interface folder and osi3 folder which was generated through the python setup build.
[Here](https://travis-ci.org/vkresch/open-simulation-interface/builds) are some test runs.

https://github.com/OpenSimulationInterface/open-simulation-interface/commit/586c3abc0e467664101d6585e88335c72dffea40

**Comment by vkresch** [comment]
Just to have an updated documentation I also suggest we use a newer dist to run the CI and add a treeview to the documentation for easier browsing through the fields. (See [here](https://vkresch.github.io/open-simulation-interface/index.html) example docu from m yrepo)

**Comment by jdsika** [comment]
Thank you @vkresch for the quick and efficient fix.
