### ISSUE TITLE
Readme not up to date: model_internal

### ISSUE THREAD

**Issue by jdsika** [OpenSimulationInterface/open-simulation-interface#341]
How to inject sensor errors has changed with OSI 3 and the Readme is still outdated. This must be fixed with the release of the sphinx documentation.

> Fault injection: how-to
> 
> Injection of pre-defined sensor errors should be handled by a specialized "fault injector" component that acts like a sensor model component, i.e. it takes a SensorData message as input and returns a modified SensorData message as output. Specific errors should be handled as follows:
> 
>     Ghost objects / false positive: An additional SensorDataObject is added to the list of objects in SensorData.object with SensorDataObject.model_internal_object.ground_truth_type set to kTypeGhost.
>     False negative: The object is marked as not seen by the sensor by setting the property SensorDataObject.model_internal_object.is_seen to false. The implementation of field-of-view calculation modules should respect this flag and never reset an object marked as not-seen to seen.

**Comment by jdsika** [comment]
The PR in osi-documentation mentioned the removal but I can still see it [here](https://opensimulationinterface.github.io/osi-documentation/osi/README.html) ? How can I check if the build system deployed correctly to gh-pages?

**Comment by vkresch** [comment]
@jdsika see again the documentation is now updated and deployed
