### ISSUE TITLE
Developer Certificate of Origin (DCO) integration in Github

### ISSUE THREAD

**Issue by jdsika** [OpenSimulationInterface/open-simulation-interface#344]
#### Describe the feature
As the OSI development will in future be driven by the ASAM e.V. I would like to suggest to lean to the best practices of the development process within the Linux kernel development. For OSS development to be broadly accepted in an industry community the most important part is the license: MPL 2.0
The next question would be "who was the contributor who developed a piece of code and was he/she allowed to contribute under those license terms?" 

#### Describe the solution you would like
This can be solved with a [Developer Certificate of Origin (DCO)](https://elinux.org/Developer_Certificate_Of_Origin) which ensures the distributed nature of the IP and identifies the contributor.

#### Describe alternatives you have considered
You can also use a [Contributor License Agreement (CLA)](https://en.wikipedia.org/wiki/Contributor_License_Agreement) which is more heavy weight and mostly puts broader rights to an organization. It feels to heavy weight and centralizes IP - as far as I understand it.

#### Describe the backwards compatibility
No impact because the current contributors are known.

**Comment by jdsika** [comment]
Have a look at [this](https://github.com/OpenSimulationInterface/open-simulation-interface/community) as well.

**Comment by engelben** [comment]
Addressed in #397
