### ISSUE TITLE
Modularity for test cases

### ISSUE THREAD

**Issue by vkresch** [OpenSimulationInterface/open-simulation-interface#347]
#### Describe the feature
Currently we validate compliance of `*.proto` files via `test_cases.py` and `test_cases_doc.py` in which multiple test cases are implemented. Because we have multiple test cases in one file we create one complex file which is not easy to maintain or add further test cases. So we need a modular design for the test cases. 

#### Describe the solution you would like
It would be beneficial to have a folder with tests. Each test case of `test_cases.py` and `test_cases_doc.py` would  be in a seperate file according to the [best practice](https://dzone.com/articles/unit-testing-best-practices-how-to-get-the-most-ou) for writing unit tests and the [single responsibility principle](https://en.wikipedia.org/wiki/Single_responsibility_principle). 

#### Describe alternatives you have considered
For refactoring to improve the maintainabilty of the project there are no alternatives. For further improvements the builtin [unit testing framework](https://docs.python.org/3/library/unittest.html) of python could be used if applicable.

#### Describe the backwards compatibility
No problem since it's only a refactoring of test cases.

#### Additional context
A good article on unit test best practices: https://dzone.com/articles/unit-testing-best-practices-how-to-get-the-most-ou

**Comment by jdsika** [comment]
I like the idea of trying to use an existing test case framework! It is an important feature to increase the quality
