### ISSUE TITLE
osi3::DetectedTrafficSign::DetectedMainSign::CandidateMainSign - What is probability in the public attributes?

### ISSUE THREAD

**Issue by WilliamGoncalvesGeiger** [OpenSimulationInterface/open-simulation-interface#348]
#### Describe the problem
I was trying to understand the meaning of "probability" that is a public parameter of osi3::DetectedTrafficSign::DetectedMainSign::CandidateMainSign and also appears in osi3::DetectedTrafficSign::DetectedSupplementarySign::CandidateSupplementarySign. 
1. Would it  be the probability of classification?
2. Is there any relation to "existence_probability"?

**Comment by jdsika** [comment]
for 1)
Yes, it is the probability of classification. It can be 60% a stop sign and 40% a warning sign
for 2)
The existance probability tells you how likely it is that the physical object exists and is not connected to probability of classification.

**Comment by WilliamGoncalvesGeiger** [comment]
![Documentation](https://user-images.githubusercontent.com/56591385/66840974-ce62ef80-ef60-11e9-93e5-5468f04ca3ae.PNG)
> for 1)
> Yes, it is the probability of classification. It can be 60% a stop sign and 40% a warning sign
> for 2)
> The existance probability tells you how likely it is that the physical object exists and is not connected to probability of classification.

for your answer in 2)
 - As you can see in the attached snipe-shot, the documentation in confusingly point to the existence probability, that is why I raised the question.

**Comment by jdsika** [comment]
"under the condition of..." hm ok let's see how this could be refrased?
It means that it is with e.g. 60% a red stop sign under the condition that the overall sign "existence_probability" for the physical sign itself is e.g. 80%.
