### ISSUE TITLE
Integrate rule definition into OSI fields which can be validated by the osi-validator

### ISSUE THREAD

**Issue by vkresch** [OpenSimulationInterface/open-simulation-interface#355]
#### Describe the feature
OSI fields need to comply to rules which should be defined in the comments of OSI messages (see [here](https://opensimulationinterface.github.io/osi-documentation/open-simulation-interface/doc/commenting.html#commenting-on-fields-and-enums) an example on how to comment on fields with rules) so that the addon [osi-validator](https://github.com/OpenSimulationInterface/osi-validation) can validate OSI messages in scenario files and report back errors and warnings which fields excatly don't comply. 

#### Describe the solution you would like
The rules from [yaml files](https://github.com/OpenSimulationInterface/osi-validation/tree/master/requirements-osi-3) should be migrated into the comment section of the OSI fields. The deafult rule defintion for fields would be no rules.

#### Describe alternatives you have considered
Set up a seperate rule database or just use the yaml files in accordance to OSI structure of messages and fields.

#### Describe the backwards compatibility
There should be no issue since the default behavior would be that if no rules are defined no rules are applied to the specific field.

#### Additional context
See more for related issues:
https://github.com/OpenSimulationInterface/open-simulation-interface/issues/332

**Comment by jdsika** [comment]
I am looking forward to this great feature!
