### ISSUE TITLE
Citation style

### ISSUE THREAD

**Issue by jdsika** [OpenSimulationInterface/open-simulation-interface#356]
#### Describe the bug
Every OSI message should be defined properly and have a well cited reference.
The documentation should state at ["if you want to state a reference"](https://opensimulationinterface.github.io/osi-documentation/open-simulation-interface/doc/commenting.html) the correct citation style. The references must be reworked for every message!
No Wikipedia!!!

#### Describe the expected behavior
We should consider looking at a guide like from [TUM](https://mediatum.ub.tum.de/doc/1236069/1236069.pdf).

#### Show some screenshots
![grafik](https://user-images.githubusercontent.com/11943343/68949016-787ca400-07b9-11ea-8982-2330cb9bb53c.png)

#### Additional context
All citations should be primary citations!

**Comment by jdsika** [comment]
@PhRosenberger can I leave this to you?

**Comment by PhRosenberger** [comment]
What is the deadline?
Probably we talk about it in the next phone call. I will concentrate on the comparison to ISO23150 first, or?

**Comment by jdsika** [comment]
Well, i thought it is a quick win for a researcher :)
I do not want to interfere with your agenda of course!

**Comment by PhRosenberger** [comment]
I agree to be assigned here, obviously it is a researcher‘s task. It‘s just about the priority of tasks. I will create an issue to track the activity on alignment with ISO 23150 now, so both of my tasks can be tracked now.

**Comment by PhRosenberger** [comment]
Should references be optional or mandatory?
@jdsika you wrote it **should** have a reference, what suggests mandatory, but I would like to clarify it.

**Comment by jdsika** [comment]
If a technical term is used the reference must be present or? Lidar Point Intensity and Reflectivity are two examples with proper reference missing. I think at best even a category like moving object types , car, lkw, etc should reference to some extend sources that tell us it is useful to chose those, right?

**Comment by PhRosenberger** [comment]
I agree, it was just for clarification.
My proposal for a citation style: PR #371
