### ISSUE TITLE
OSI and ISO23150 initiative alignment

### ISSUE THREAD

**Issue by PhRosenberger** [OpenSimulationInterface/open-simulation-interface#367]
#### Describe the feature
OSI should be synchronized with the ISO23150 initiative regularly, as both tackle perception sensors. OSI is the interface standardization for simulation models of actual hardware that is tackled by the ISO23150 initiative.

#### Describe the solution you would like
it should be done by a person that has access to both groups by conparison of the available documents. OSI should be adapted to the ISO23150.

**Comment by PhRosenberger** [comment]
As there is a commenting phase within the working group of ISO 23150 currently running until end of January, we should wait for the results there.

Proposal: Alignment will be done, when consolidation of actual commenting phase is done.

**Comment by jdsika** [comment]
ok, so you have to plan the two weeks between end of January and release before the OSI workshop for that  and we proceed with the citation topic

**Comment by jdsika** [comment]
@PhRosenberger the DIS of ISO23150 is distributed and the editorial version is available for purchaise on 22.05.2020. I think we can start here! :)

**Comment by PhRosenberger** [comment]
Is there support expected from anybody to split work here, or am I alone with this?

**Comment by jdsika** [comment]
This topic should be brought into the ASAM work group as a deliverable in the next version - I expect contributions from the group!

**Comment by ThomasNaderBMW** [comment]
the point of this issue is to assimiliate OSI and the ISO23150 regarding the sensor interface, right?
@PhRosenberger : Can you place this as an requirement for Use-Cases 1, 2.a, 2.b in the ASAM Project-Proposal? This should be the right place.

**Comment by PhRosenberger** [comment]
> the point of this issue is to assimiliate OSI and the ISO23150 regarding the sensor interface, right?
Yes.
> @PhRosenberger : Can you place this as an requirement for Use-Cases 1, 2.a, 2.b in the ASAM Project-Proposal? This should be the right place.
Would it be better to create a new use case for it?
Anyways, I see 16 (?) use cases there now so I am confused with the numbers. Can you give the titles of the use cases you mean?

**Comment by ThomasNaderBMW** [comment]
UC 1: Abstracted Object-Based Sensor Model
Therefore you or I could create a requirement and a workingpackage.
@pmai : What is your opinion?
I am not so deep into this topic so far, I have to mention.

**Comment by clemenshabedank** [comment]
As @ThomasNaderBMW , I am currently not able to estimate the effort, but probably an extra WP is reasonable, as @PhRosenberger suggests. I think we should also put it into the chapter "Relations to Other Standards or Organizations", right?

**Comment by pmai** [comment]
@PhRosenberger, @ThomasNaderBMW, @clemenshabedank I think a separate WP also seems reasonable. Probably on the order of 20 PDs?

**Comment by PhRosenberger** [comment]
After a first initial diskussion with AUTOSAR ADI experts, this issue could be changed to OSI - AUTOSAR ADI aligment, right?
We should further diskuss this in the CCB, I guess.

@pmai @clemenshabedank @kmeids @LukasElster @stefancyliax @ThomasNaderBMW 
Should I close this issue for now? And create a new one?

**Comment by kmeids** [comment]
I agree, I'll add this point to the CCB board.

**Comment by jdsika** [comment]
I will close this issue as we have a procedure to  "Align OSI and Autosar ADI" now.  @FlorianMueller87 is creating issues for every finding and they will be dealt with one by one in the next OSI project. example #643

**Comment by thomassedlmayer** [comment]
@jdsika @FlorianMueller87 Is there still interest in harmonization of OSI and AUTOSAR ADI? There are a lot of open issues/PRs now which don't have active assignees (see https://github.com/OpenSimulationInterface/open-simulation-interface/labels/AUTOSAR%20ADI). Should we close them?

**Comment by FlorianMueller87** [comment]
@thomassedlmayer Unfortunately, we are not longer contributing to AUTOSAR ADI anymore. We had to left for one and a half years ago. So I am not up to date.
