### ISSUE TITLE
Renaming OSI because of possible misunderstandings by duplication of the abbreviation?

### ISSUE THREAD

**Issue by PhRosenberger** [OpenSimulationInterface/open-simulation-interface#369]
#### Describe the problem
There is already a standard called ["Open Systems Interconnection model"](https://de.wikipedia.org/wiki/OSI-Modell) with the same abbreviation "OSI". Because of this duplication, we face some misunderstandings when talking about OSI with our industry partners.

Reference: [ISO/IEC standard 7498-1:1994](http://standards.iso.org/ittf/PubliclyAvailableStandards/s020269_ISO_IEC_7498-1_1994(E).zip)

#### Ask your question
We would like to ask, if there are plans to rename "our" standard to something different with unique abbreviation?

**Comment by jdsika** [comment]
A unique abbreviation with 3 letters... I know about this naming "clash" but I always say it is a joke because our OSI is also a "layered standard" ;)

**Comment by engelben** [comment]
Definitely a discussion we will need to continue at the ASAM kickoff workshop on the 21.02. AUTOSAR for example also has an OSI ;)

**Comment by PhRosenberger** [comment]
I think we actually forgot to discuss this. As it is still open, how can we continue with that tricky question?

**Comment by engelben** [comment]
Good point... I suggest we put it on the agenda for the project kickoff early June (date still TBD).

**Comment by ThomasSchloemicherAVL** [comment]
What about OpenDI (Open Data Interface)?

**Comment by jdsika** [comment]
I would never change the name

**Comment by engelben** [comment]
We will be sticking with OSI for now. Closing this.
