### ISSUE TITLE
Compare: OSI and OpenDrive

### ISSUE THREAD

**Issue by CarloVanDriestenBMW** [OpenSimulationInterface/open-simulation-interface#37]
As @AndreasVIRES  mentioned in the telko at 14.02.17 we should compare OSI and OpenDrive. This seems to be a bigger projekt and should be handled as a "project" with issues for smaller sub problems.

**Comment by ndunningbmw** [comment]
Have there been any updates regarding this topic? We are currently trying to handle complex junctions defined in OpenDrive, and how these should be represented in OSI is not clear.

**Comment by CarloVanDriestenBMW** [comment]
Will be handeled here: #110

OpenDrive deliveres detailed information on the maps and OSI is the view of the sensor - invisible lane structures will be removed in order to simplify and avoid recreating OpenDrive :)
