### ISSUE TITLE
Python OSITrace message_offset contains actual messages instead of lengths

### ISSUE THREAD

**Issue by tpajenkamp-dspace** [OpenSimulationInterface/open-simulation-interface#372]
#### Describe the bug
After calling "from_file", the attribute "message_offsets" contains the itneger 0 and a bunch of message objects.

#### Describe how to reproduce the bug
t = OSITrace()
t.from_file(myPath)

#### Describe the expected behavior
"message_offsets" contains the lengths of individual messages.

#### Additional context
In line 145 of retrieve_message(): ```self.message_offsets.append(message)``` is incorrect

**Comment by vkresch** [comment]
Can you share your script or a minimal reproducable example on when the bug appears? Which format are you using *.osi or *.txt?

**Comment by tpajenkamp-dspace** [comment]
I am using the *.osi format. Below is my sample code. I would expect something like ```[0, 32]``` to be printed instead of ```[0, global_ground_truth {
  version {
    version_major: 3
    version_minor: 1
    version_patch: 2
  }
  timestamp {
    seconds: 1
    nanos: 100000
  }
  moving_object {
    id {
      value: 114
    }
    vehicle_classification {
      type: TYPE_SMALL_CAR
    }
  }
}
]```. 

```python
from osi3.osi_sensorview_pb2 import SensorView
import struct
from OSITrace import OSITrace

def createDummyTrace(filePath):
    """Initialize SensorView"""
    f = open(filePath, "wb")
    sensorview = SensorView()

    sv_ground_truth = sensorview.global_ground_truth
    sv_ground_truth.version.version_major = 3
    sv_ground_truth.version.version_minor = 1
    sv_ground_truth.version.version_patch = 2

    sv_ground_truth.timestamp.seconds = 0
    sv_ground_truth.timestamp.nanos = 0

    moving_object = sv_ground_truth.moving_object.add()
    moving_object.id.value = 114

    # Generate 10 OSI messages for 9 seconds
    for i in range(2):

        # Increment the time
        sv_ground_truth.timestamp.seconds += 1
        sv_ground_truth.timestamp.nanos += 100000

        moving_object.vehicle_classification.type = 2

        """Serialize"""
        bytes_buffer = sensorview.SerializeToString()
        f.write(struct.pack("<L", len(bytes_buffer)) + bytes_buffer)

    f.close()

def main():
    tracePath = "test_trace.osi"

    # Create dummy file
    createDummyTrace(tracePath)

    # Read dummy file
    traceReader = OSITrace(tracePath, 'SensorView')
    traceReader.from_file(tracePath, 'SensorView', format_type=None)
    print(traceReader.message_offsets)

if __name__ == "__main__":
    main()
```

**Comment by vkresch** [comment]
You are right! `message_offsets` should contain offsets and not the actual deserialzed messages. I will create a PR to fix it. For a quick fix just replace `message` with the iterator `i`.
