### ISSUE TITLE
Header suggestion for osi files

### ISSUE THREAD

**Issue by mbencik** [OpenSimulationInterface/open-simulation-interface#373]
Currently there is no possibility to identify any osi file that is size delimited.  Also there is no possibility to identify the protobuf version and number of frames in the file. 

My suggestion would be to add a header at the begging of the file to identify the basic informations. 
OSI version
Protobuf Version
Number of frames

This would improve the file security since if it is not fitting with the file then the file is considered non valid. Since if a file is changed from txt to osi just by changing the extension there is no possibility to discover it. 

The backwards compatibility can be achieved with a converter.

**Comment by jdsika** [comment]
I like the idea! @pmai what do you think?

**Comment by jdsika** [comment]
My suggestion:
Define a naming convention for files with those information. Check the file name information by parsing the message and check for consistency

**Comment by vkresch** [comment]
Ok so how should the naming look like? See examples below:
```
Type = SensorView
OSI Version= 3.1.2
Protobuf Version = 3.0.0
Number of frames = 1523
Scenario name = highway
```
Example for the case above:
`SensorView_030102_030000_1523_highway.osi`?
or 
`SensorView_osi_030102_protoc_030000_frames_1523_highway.osi`?
or
`SV_osi_312_protoc_300_frames_1523_highway.osi`?
or
`sv_312_300_1523_highway.osi`?

Further suggestions are welcome :)

**Comment by jdsika** [comment]
hmm.... all small letters because caps is annoying in Linux I think.
It is hard to decide between too verbose and self explaining!
This looks clean but you need an explanation with it:
sv_312_300_1523_highway.osi

This looks pretty clean?
