### ISSUE TITLE
Can't install OSI in python, 'protoc not found' exception

### ISSUE THREAD

**Issue by ballascsaba** [OpenSimulationInterface/open-simulation-interface#384]
#### Describe the problem
Hi!
I have a problem which I can't get past for around a week now: Anytime and anyhow I want to install OSI, somehow it doesn't work. 

I use python (tried 2.* and 3.* too), and I followed the installation instructions in the ReadMe. When I issue the "python setup.py install" command (on Windows), I get the following message:

![image](https://user-images.githubusercontent.com/62758318/78565318-07986000-781e-11ea-8adf-a6997a955727.png)

This also happens on emulated linux environment. As You can see on the picture, I use virtual environment, on which I've installed protobuf and also protobuf-compiler (and all of its requirements). Here is a picture on all of the packages installed on the venv:

![image](https://user-images.githubusercontent.com/62758318/78565878-c81e4380-781e-11ea-8490-97cc82bf1d8e.png)

I would like to ask, how can I solve this installation problem? Have you had anything like it before? 

I thank You for Your answers in advance!
Kind Regards,
Csaba

**Comment by vkresch** [comment]
It seems an issue with protobuf. You need to install protobuf not only in the virtual environment but also globally on your machine ([Windows installation](https://github.com/protocolbuffers/protobuf/tree/master/python)). 

The same goes for Linux machines. Try to run this commands on linux:

`apt-get install libprotobuf-dev protobuf-compiler`

Hope this helps! Let me know if it worked.

**Comment by ballascsaba** [comment]
Thank you @vkresch, it worked like a charm! I copied the actual version of protobuf binary into my PATH, and after that, I could install OSI. You spared me many hours of trying, thank you again! :D

**Comment by vkresch** [comment]
@ballascsaba No problem glad I could help!
