### ISSUE TITLE
Missing fields for ray tracer config in radar and lidar sensor view config

### ISSUE THREAD

**Issue by ClemensLinnhoff** [OpenSimulationInterface/open-simulation-interface#389]
For ray tracer parametrization and optimization the fields
- max_range_per_ray
- max_range_per_pixel

are missing.
If they cannot be set, the ray tracing tool does not know when to terminate a ray.

**Comment by kmeids** [comment]
@PhRosenberger @ClemensLinnhoff can we close this issue now?

**Comment by PhRosenberger** [comment]
> @PhRosenberger @ClemensLinnhoff can we close this issue now?

I would say yes.
