### ISSUE TITLE
"osi_lane.proto" Boundary Point

### ISSUE THREAD

**Issue by WeiskopfDaimler** [OpenSimulationInterface/open-simulation-interface#39]
Which Reference Frame do I use for Boundary Points? Do I define them related to the lane reference line or in world coordinates?

**Comment by nHirsenkorn** [comment]
Short answer: world coordinates

Extended answer:
At the moment only two reference frames within OSI exist. Objective is to keep it as simple as possible:
1. world reference frame (all quantities which are part of groundtruth)
2. sensor reference frame (all quantities which are part of sensordata)

Therefore the answer depends:
If you are adding a lane to groundtruth use the word reference frame.
If you are adding a lane to detectedlane use the sensor reference frame.

**Comment by SoykaDaimler** [comment]
Here's another example for possible confusions regarding reference frame. As mentioned in #14 I think it would be good to give all coordinates an identifier describing their reference frame. 
A similar point came up in #15 
As @nHirsenkorn described above: the same quantities are used to describe data in the world or the sensor frame, depending on if they are part of groundtruth or sensordata. In my opinion this is very error prone.
