### ISSUE TITLE
OSI_Trace file generation 

### ISSUE THREAD

**Issue by Abhishek2011992** [OpenSimulationInterface/open-simulation-interface#391]
Hello ,
Am using C++ library for generating the OSI trace file. What i understood from the internet is that the OSI messages should be separated by "$$__$$" and i added the below code to write to file. But still the OSI file is not proper when i try to convert it to .osi using txt2osi.py. 

Can anyone help me understanding what is going wrong?

        std::string osi_string = sensor_view.SerializeAsString();
	osi_string.append("$$__$$");
	osi_trace_file<< osi_string;

**Comment by vkresch** [comment]
Can you show the error message when you run txt2osi.py? You can also serialize it into *.osi file directly in C++ by using:

```
unsigned int message_size = sensor_view.SerializeAsString().size();
unsigned char ch[4];
memcpy(ch, (char*)&message_size, sizeof(unsigned int));

osi_string += ch[0];
osi_string += ch[1];
osi_string += ch[2];
osi_string += ch[3];
osi_string += sensor_view.SerializeAsString();
```
See the implementation for output save in [OSI Visualizer](https://github.com/OpenSimulationInterface/osi-visualizer/blob/master/src/osiparser.cpp#L72) for more.

**Comment by Abhishek2011992** [comment]
Thank You for taking time and addressing my question. I have it working now.
