### ISSUE TITLE
Unable to install OSI for C++ on windows

### ISSUE THREAD

**Issue by vibhoraggarwal** [OpenSimulationInterface/open-simulation-interface#394]
#### Description
I am installing OSI for C++ on Windows. I am using all the information from [here](https://opensimulationinterface.github.io/osi-documentation/open-simulation-interface/doc/windows.html), but still receive errors. 

Until the following command (generating build files):
`cmake .. -G "Visual Studio 12 2013" -DCMAKE_INSTALL_PREFIX=C:/Libraries/open_simulation_interface` installation works fine.
But,
1. `cmake --build . [--config Release]` and 
2. `cmake --build . --target install` 

produce errors. Error produced with both commands are attached as text files below.

#### Things already done:
I have installed the following pre-requisites:

 [Protobuf ](https://github.com/protocolbuffers/protobuf) (`v2.6.1`)
CMake `v3.18.0-rc1`
Visual Studio 12 2013

#### Clarifying the question
1. Is there something that I am missing here, or doing wrong? 
2. Do you have any suggestions based on the error logs?

[command-install.txt](https://github.com/OpenSimulationInterface/open-simulation-interface/files/4813720/command-install.txt)
[command-config-release.txt](https://github.com/OpenSimulationInterface/open-simulation-interface/files/4813721/command-config-release.txt)

**Comment by vibhoraggarwal** [comment]
I was able to successfully install it by solving following issues.

1. I built the Protobuf using `Debug`; but, I am building `cmake` with `Release`. Both of them have to be built in the same configuration. 
2. As mentioned [here ](https://opensimulationinterface.github.io/osi-documentation/open-simulation-interface/doc/windows.html) in Section 3, `protoc.exe` executable and protobuf libraries have to be 64-bit (consistent with `cmake` installation in `OSI`)
3. The paths associated with the Environment variables have to be from the `Release` library in Protobuf.
4. During the final build file generation, and installing the build files, following commands need to run:
    a. 
`cmake .. -G "Visual Studio 12 2013" -DCMAKE_INSTALL_PREFIX=C:/Libraries/open_simulation_interface`

    b. `cmake --build . --config Release --target install`

**Comment by vkresch** [comment]
Hi @vibhoraggarwal thank you for reporting! Feel free to open a PR to update the [windows documentation](https://github.com/OpenSimulationInterface/open-simulation-interface/blob/master/doc/windows.rst) according to your procedure so that we can avoid this issue in the future. Thank you again ;)!
