### ISSUE TITLE
What is the scope of a single SensorView message?

### ISSUE THREAD

**Issue by caspar-ai** [OpenSimulationInterface/open-simulation-interface#396]
#### Problem
A `SensorView` defines as a top level field: `sensor_id` defined as "ID of the virtual sensor" - which implies a single `SensorView` message is required for each sensor.

However, a `SensorView` also defines `camera_sensor_view` which is a repeated field of `CameraSensorView`.  Inside _that_ message is a `CameraSensorViewConfiguration` which also contains a `sensor_id` (and a `mounting_position` etc.).  This allows a single `SensorView` to contain the information for multiple (potentially all) sensors being reported.

#### Question
The question is then what the intention of the `SensorView` message is?  Should it cover just a single sensor or multiple / all sensors?

#### Suggestion
Reporting all the sensors in a single top level message would seem more efficient and sensible, but then perhaps the `sensor_id` (and `mounting_position` etc.) should be deprecated from the top level of the `SensorView`?

**Comment by pmai** [comment]
While `SensorData` was intended to allow fusioned data from multiple sensors to be transported in one message, I don't think anyone had multiple sensors being provided the same `SensorView` in mind.

The reason that `SensorView` allows multiple technology specific sub-views is to enable two things:

- A logical sensor containing multiple physical detectors ("sensors"), e.g. a stereo camera, a radar with multiple antennas, ...

- A sensor model requiring multiple differently configured inputs to better model its characteristics, e.g. a narrow long-range beam and a wider short-range beam, or an RGGB and a luminance image, which is then processed to provide the actual sensor behaviour.

The set of technology-specific sub-views is configured through the `SensorViewConfiguration` entries for that technology.

**Comment by jdsika** [comment]
As @pmai stated:

> The virtual mounting position of the sensor (origin and orientation of the sensor coordinate system) given in vehicle coordinates [1]. The virtual position pertains to the sensor as a whole, regardless of the actual position of individual physical detectors, and governs the sensor-relative coordinates in detected objects of the sensor as a whole. Individual features detected by individual physical detectors are governed by the actual physical mounting positions of the detectors, as indicated in the technology-specific sub-views and sub-view configurations.

The top level "virtual mounting position" is needed to define the "reference point" of a multi sensor system. I agree that encapsulation can lead to confusion which is apparently the case here... The most important information from my side is:

You need to differentiate between the "physical" locations of sensors giving the reference point of single measurements (antenna, lense, etc) and the "virtual" mounting position of a component system.

Keeping this as a requirement we can change messages in order to be more comprehensive

**Comment by u21n80** [comment]
> As @pmai stated:
> 
> > The virtual mounting position of the sensor (origin and orientation of the sensor coordinate system) given in vehicle coordinates [1]. The virtual position pertains to the sensor as a whole, regardless of the actual position of individual physical detectors, and governs the sensor-relative coordinates in detected objects of the sensor as a whole. Individual features detected by individual physical detectors are governed by the actual physical mounting positions of the detectors, as indicated in the technology-specific sub-views and sub-view configurations.
> 
> The top level "virtual mounting position" is needed to define the "reference point" of a multi sensor system. I agree that encapsulation can lead to confusion which is apparently the case here... The most important information from my side is:
> 
> You need to differentiate between the "physical" locations of sensors giving the reference point of single measurements (antenna, lense, etc) and the "virtual" mounting position of a component system.
> 
> Keeping this as a requirement we can change messages in order to be more comprehensive

@jdsika does this mean that the top level mounting_position is [SensorData::mounting_position](https://opensimulationinterface.github.io/open-simulation-interface/structosi3_1_1SensorData.html)? If so is SensorData::mounting_position specified relative to host_vehicle_location and then SensorData::sensor_view[i]::mounting_position is specified relative to SensorData::mounting_position?
