### ISSUE TITLE
OSI Examples

### ISSUE THREAD

**Issue by clabom** [OpenSimulationInterface/open-simulation-interface#398]
I just started to play with OSI and everthing works fine for me. To understand it better, it would be graet to have some more examples. Is it possible to provide some more "real world" sensor view and sensor data .osi example traces?

**Comment by engelben** [comment]
Hi @clabom , I reccomend joining the crash course we are holding next week - https://www.linkedin.com/posts/benjamin-engel_asamosi-osi-asam-activity-6691243015249399808-2G3x

**Comment by kmeids** [comment]
@clabom, do have a look on the following pull request: https://github.com/OpenSimulationInterface/open-simulation-interface/pull/450

**Comment by PhRosenberger** [comment]
I would propose to close this issue with a hint towards OpenMSL: https://github.com/openMSL

**Comment by jdsika** [comment]
Good idea. Can you maybe coordinate with @engelben in what form a reference to a partner organization and project like OpenMSL is properly referenced here?

**Comment by PhRosenberger** [comment]
We just talked about it at the CCB meeting and @florianwallerer will take it to internal discussion with @engelben.
