### ISSUE TITLE
cmake project

### ISSUE THREAD

**Issue by CarloVanDriestenBMW** [OpenSimulationInterface/open-simulation-interface#4]
It should be considered to add a cmake project in order to integrate OSI in exitisting projects without platform or tool dependency?

**Comment by TimoHankeBMW** [comment]
It may be a good idea to provide a CMakeLists.txt that can easily be integrated in existing CMake projects.

Something like

> find_package(Protobuf 2.6.1 REQUIRED)
set(OSI_PROTO_FILES
    osi_common.proto
    osi_datarecording.proto
    osi_detectedlandmark.proto
    osi_detectedobject.proto
    osi_detectedoccupant.proto
    osi_detectedlane.proto
    osi_environment.proto
    osi_groundtruth.proto
    osi_landmark.proto
    osi_lowleveldata.proto
    osi_modelinternal.proto
    osi_object.proto
    osi_occupant.proto
    osi_lane.proto
    osi_sensordata.proto
    osi_sensorspecific.proto
)
PROTOBUF_GENERATE_CPP(PROTO_SRC PROTO_HEADER ${OSI_PROTO_FILES})
add_library(open_simulation_interface STATIC ${PROTO_SRC} ${PROTO_HEADER})
target_link_libraries(open_simulation_interface ${PROTOBUF_LIBRARY})
set (OSI_PROTOBUF_INCLUDE_PATH ${CMAKE_CURRENT_BINARY_DIR} CACHE INTERNAL "[OSI] Path to generated protobuf files for the open simulation interface.")

A calling script can then include OSI using

> add_subdirectory( open-simulation-interface )

taking care to call it before compiling any code that depends on the generated message headers that can be included using

> include_directories(${OSI_PROTOBUF_INCLUDE_PATH})

Using a Cache variable allows propagation of the location of the generated message headers while still externalizing the OSI compilation into its own library.

@pmai: How can this be integrated with the FMU compilation? An integrated template script would be great.

**Comment by pmai** [comment]
I'll split out the FMU example with a CMake script, so this could work as a template...
