### ISSUE TITLE
Missing Vehicle-Signals

### ISSUE THREAD

**Issue by ThomasNaderBMW** [OpenSimulationInterface/open-simulation-interface#400]
Hello everyone!

In this issue I would like to do a collection of signals regarding the vehicle, which are missing so far in OSI.
The issue comes out of the ASAM-Project and is mainly driven bei WP 14/15, but of course everybody can contribute!
Which interface is being touched should be left open and something we want to think about - based on this collection.
The focus should be on internal/external vehicle states and even the ad-function.
Road information until a specific depth (so please no trafficsign optimizations).

### Example:
_Name_: pedal_position_acceleration
_Description_: Position of the acceleration-pedal. 
_Unit_: [0-1] (Unpressed - fully pressed)
_Type_: Double
_Sender_: From Host-Vehicle (Mock-Up)
_Receiver_: Dynamic-/Vehicle-Modell

Thanks in advance for contribution! :)

**Comment by Krishna626** [comment]
Hello Everyone, I would like to have the following interfaces defined to simulate external dynamics in addition to the interface defined above:

Name: pedal_position_brake
> Description: Position of the brake-pedal.
> Unit: [0-1] (Unpressed - fully pressed)
> Type: Double
> Sender: From Host-Vehicle (Mock-Up)
> Receiver: Dynamic-/Vehicle-Model

Name: angle_steering_wheel
> Description: angular position of steering-wheel.
> Unit: [-pi-pi] (rotation)
> Type: Double
> Sender: From Host-Vehicle (Mock-Up)
> Receiver: Dynamic-/Vehicle-Model

Name: rpm_engine/E-motor
> Description: current engine/e-motor rpm
> Unit: [0-8000] (rotations per minute)
> Type: uint16
> Sender: From Host-Vehicle (Mock-Up)
> Receiver: Dynamic-/Vehicle-Model

Name: position_gear_lever
> Description: current gear lever position
> Unit: [-1to 8] (R: -1, D:5, N:4 etc.)
> Type: int8
> Sender: From Host-Vehicle (Mock-Up)
> Receiver: Dynamic-/Vehicle-Model

Name: z_position_wheel_contactpoints
> Description: z-value of wheel contact points from road surface
> Unit: [0-1000+] (meters)
> Type: uint8
> Sender: From Host-Vehicle (Mock-Up)
> Receiver: Dynamic-/Vehicle-Model

Name: friction_wheel_contactpoint
> Description: friction values of wheel contact points at road surface
> Unit: -
> Type: uint8
> Sender: From Host-Vehicle (Mock-Up)
> Receiver: Dynamic-/Vehicle-Modell

**Comment by ThomasNaderBMW** [comment]
Collection is done!
