### ISSUE TITLE
Required Protobuf version

### ISSUE THREAD

**Issue by SoykaDaimler** [OpenSimulationInterface/open-simulation-interface#41]
Hi,
do we really require protobuf 2.6.1 for compiling?
I only had 2.5.0 on my system and after changing the CMake file, it compiled just fine. 
So maybe we could loosen the requirements for the protobuf version a bit.
@pmai Did you write the CMake file? And can you maybe answer this question?
Thanks!

**Comment by CarloVanDriestenBMW** [comment]
[Release 2.6.x Info](https://github.com/google/protobuf/releases?after=v2.6.1)

> A new C++-backed extension module (aka "cpp api v2") that replaces the
> old ("cpp api v1") one. Much faster than the pure Python code. This one
> resolves many bugs and is recommended for general use over the
> pure Python when possible.
> Support for Python 3.

The python support ist much better in 2.6.0!

> Released memory allocated by InitializeDefaultRepeatedFields() and GetEmptyString(). Some memory sanitizers reported them as memory leaks.

They seemed to have fixed some bugs, too.

I recommend just using 2.6.1, also becaus it is the last stable and apperenty bug free version before the release of version 3.x.x. There is also the possibility of sharing memory between messages which has not been used yet, but in my opinion will be relevant in the future releases of OSI. Does that help?

**Comment by pmai** [comment]
IIRC I committed the makefile, but based on stuff from @TimoHankeBMW. As far as I'm aware 2.6.1 has been targetted for some time now, so I'm not sure how well-tested older releases would be.

**Comment by SoykaDaimler** [comment]
Thanks for the quick replies! So we just leave it at 2.6.1 then.
