### ISSUE TITLE
Rotational order of Orientation3d

### ISSUE THREAD

**Issue by AndreasVIRES** [OpenSimulationInterface/open-simulation-interface#42]
The comment for Orientation3d states rotational order as: "roll first, then the pitch, and finally the yaw". The usual convention is yaw -> pitch -> roll, as defined in e.g. DIN70000. 

`/// A 3D orientation, orientation rate or orientation acceleration.
/// Units are [rad] for orientation, [rad/s] for rates and [rad/s^2] for accelerations. The preferred angular range is
/// (-pi, pi]. See http://planning.cs.uiuc.edu/node102.html for a definition of the rotational order. The rotations are
/// to be performed roll first, then the pitch, and finally the yaw. Rotations are defined in the reference coordinate
/// frame around z (=yaw), y (=pitch) and x (=roll), not in the body frame of the object. Rotations with positive angles
/// are performed counter-clockwise.
///
/// Roll/Pitch are 0 if objects xy-plane corresponds it's parent xy-plane.
/// Yaw is 0 if the x axis is parallel to the x axis of it's parent coordinate system.
///
message Orientation3d
{`

**Comment by TimoHankeBMW** [comment]
Seems like we missed checking with DIN70000. I suggest going with the standard definition of the norm and changing to yaw -> pitch -> roll. Can't check with the norm right now. Can someone look-up the proper definition and wording used there?

**Comment by nHirsenkorn** [comment]
We were sticking to a definition common in robotics.
 http://planning.cs.uiuc.edu/node102.html
However you can change it, I don't care :)

**Comment by nHirsenkorn** [comment]
this is further discussed in #51

**Comment by JonathanSchmalhoferBMW** [comment]
How about switching to [quaternions](https://en.wikipedia.org/wiki/Conversion_between_quaternions_and_Euler_angles)? As long as one represents any orientation using only one quaternion, gimbal lock will not occur.

**Comment by martin-fzd** [comment]
Gimbal lock is an issue with these corrdinates, but not realy with non-flying vehicles. Let me know, if I'm wrong. I would propose to stick to ISO 8855 and DIN 70000, see the parallel discussion in #51 .
