### ISSUE TITLE
Lidar - Beam Divergence and Background Irradiance

### ISSUE THREAD

**Issue by WataruNakamura1** [OpenSimulationInterface/open-simulation-interface#422]
#### Describe the feature
The beam emitted from lidar diverges along with its flight length and the reflection point has a footprint. 
So the reflected beam includes the infrared ray from the sun lignt according to the area of the footprint. 
The infrared ray comming from the sun lignt is a noise for Lidar.
We need to take account of the beam divergence and the background irradiance at the reflection point  for the development of Lidar sensor model.

#### Describe the solution you would like
We want to add the following fields, 

- LidarSensorView.Reflection  
  - optional double background_irradiance [W/m^2] 

- LidarSensorViewConfiguration
  - optional double max_irradiation_distance [m]
  - optional double beam_divergence_horizontal [degree]
  - optional double beam_divergence_vertical [degree]

**Comment by kmeids** [comment]
@WataruNakamura1,
Could you please add some comments to your proposed fields?

Since the background_irradiance is something that's not related to the "ray-tracer" I am not sure if it should be added here or just a part of the sensor model, @PhRosenberger, what do you think?

**Comment by PhRosenberger** [comment]
I guess you could calculate an assumption from https://opensimulationinterface.github.io/open-simulation-interface/structosi3_1_1EnvironmentalConditions.html#a9af62398fb21a5314539815afa733d4b but getting the actual position of the sun would be more useful.

Nevertheless, I agree to @kmeids that self calculation from such environmental conditions gives you more control on this.

**Comment by PhRosenberger** [comment]
As of no further comments and activities for quite some time, I will close this now.
