### ISSUE TITLE
Unable to use osi2read.py to generate human readable file from trace file

### ISSUE THREAD

**Issue by vibhoraggarwal** [OpenSimulationInterface/open-simulation-interface#425]
#### Description
I have already generated some trace files (.txt) files. Now, I want to convert them into human readable form using the [osi2read.py](https://github.com/OpenSimulationInterface/open-simulation-interface/blob/master/format/osi2read.py) python script. But, I am unable to do so and instead receive errors mentioned below.

#### Setup used
Protocol buffer version: v2.6.1

#### Command used
`python osi2read.py -d sv_TraceGen_sv_sd.txt -f separated -o myreadableosifile`

#### Error received
```
Traceback (most recent call last):
  File "osi2read.py", line 10, in <module>
    from OSITrace import OSITrace
  File "C:\temp\OSITrace.py", line 9, in <module>
    from osi3.osi_sensorview_pb2 import SensorView
  File "C:\git\open-simulation-interface\osi3\osi_sensorview_pb2.py", line 7, in <module>
    from google.protobuf import reflection as _reflection
  File "c:\git\protobuf-2.6.1\python\google\protobuf\reflection.py", line 68, in <module>
    from google.protobuf.internal import python_message
  File "c:\git\protobuf-2.6.1\python\google\protobuf\internal\python_message.py", line 848
    except struct.error, e:
                       ^
SyntaxError: invalid syntax
```

#### Question
Can somebody reproduce the same error, or had received it in the past, and may have a work around?

#### Additional context
I used the scripts some time before, wherein my system could execute them perfectly. But, during some version changes (of protobuf) due to inconsistency with building some programs, I lost my system settings and could not trace them back.

**Comment by vkresch** [comment]
Protocol-buffer v2.6.1 does not support python3. You should upgrade to at least 3.0.0.
See here the discussion for more: https://github.com/protocolbuffers/protobuf/issues/882#issuecomment-170145798

**Comment by vibhoraggarwal** [comment]
@vkresch Thanks; will try it and post it here.

**Comment by vibhoraggarwal** [comment]
It was indeed the problem with the version. I used the protobuf version 3.12.2, and could successfully generate the files.

Thanks, closing the issue.

**Comment by vkresch** [comment]
@vibhoraggarwal thanks for the feedback! Glad I could help.
