### ISSUE TITLE
Rotation direction in Orientation3d

### ISSUE THREAD

**Issue by AndreasVIRES** [OpenSimulationInterface/open-simulation-interface#43]
The comment for Orientation3d states rotation direction as: "Rotations with positive angles are performed counter-clockwise".

What does "counter-clockwise" mean in this context?

**Comment by TimoHankeBMW** [comment]
Positive angles signify counter-clockwise rotation around the reference axis, i.e. rotation is given by the right-hand rule: https://en.wikipedia.org/wiki/Right-hand_rule

**Comment by AndreasVIRES** [comment]
Defining clockwise vs. counter-clockwise rotation only makes sense, if we also define the view point like the Wikipedia article does:
> **When viewed from the top** or Z axis the system is counter-clockwise.

In my opinion, defining the coordinate system as right handed coordinate system would be enough.

**Comment by nHirsenkorn** [comment]
As described in the comment: 
See http://planning.cs.uiuc.edu/node102.html
This should contain a complete definition.
