### ISSUE TITLE
Incomplete documentation of coordinate systems

### ISSUE THREAD

**Issue by u21n80** [OpenSimulationInterface/open-simulation-interface#445]
#### Description
The documentation of position and orientation fields does not name the frame in which the values are given in. This issue can be observed in various aspects:
a. The actual documentation of a field on the lowest level is missing the documentation. An example for this would be [DetectedMovingObject::base::position](https://opensimulationinterface.github.io/open-simulation-interface/structosi3_1_1BaseMoving.html#a189c6f025650f630b92adb277bf59db6) where it just specifies that it is the position of the bounding box center, but does not clearify in which frame this position is given in. We could specify it is given in the parent frame and specify the parent frame in a level above (in the example it would be the documentation of base), but some frame has to be written down.
b. Sometimes frames are referenced, but never defined. Example would be [DetectedMovingObject::base](https://opensimulationinterface.github.io/open-simulation-interface/structosi3_1_1DetectedMovingObject.html). Here the parent frame is specified to be the sensor's vehicle frame. This vehicle frame is never defined.

This lack of clean documentation has several implications:
1. It is unclear how hose_vehicle_location is defined for the following reasons: 
1.1. The parent frame of [host_vehicle_location is the sensor frame](https://opensimulationinterface.github.io/open-simulation-interface/structosi3_1_1SensorData.html#a7bacbcf1f521df6038d455a80baed870). If the sensor is mounted on the vehicle this would mean that the position host_vehicle_location would not change. I guess the parent frame was intended to be a global reference frame like ENU.
1.2. The reference point (see [documentation of position of BaseMoving](https://opensimulationinterface.github.io/open-simulation-interface/structosi3_1_1BaseMoving.html) and [sketch](https://opensimulationinterface.github.io/open-simulation-interface/structosi3_1_1BaseMoving.html)) is unclear. According to the field documentation the reference point is the center of the bounding box. But some figures contradict this documentation and use the center of the rear axle instead (see [DetectedLaneBoundary sketch](https://opensimulationinterface.github.io/open-simulation-interface/structosi3_1_1DetectedLaneBoundary.html), [DetectedStationaryObject sketch](https://opensimulationinterface.github.io/open-simulation-interface/structosi3_1_1DetectedStationaryObject.html)). This contradiction is also source for issue #388.
2. The position and orientation of [BaseMoving](https://opensimulationinterface.github.io/open-simulation-interface/structosi3_1_1BaseMoving.html) are given in different coordinate systems. From the transformation equation in documentation of field orientation in BaseMoving x_base = R * (x_parent - t)  <=> x_parent = R.inverse() * x_base +t. From this equation it can be deduced that the position t is the position of the base reference point in the parent frame. While the orientation is the orientation of the parent frame in the BaseMoving frame. This violates the documentation where it says that the orientation is the BaseMoving frame orientation in the parent frame.
3. Currently the host vehicle location is only specified in any cartesian coordinate system. If we were to use ISO8855 and the cartesian system is ENU (x: east, y: north, z: up), we need to specify additional information like geodetic reference coordinate and ellipsoid. If this information is not provided it is impossible to get the global position of detected objects. 

#### Expected behavior
@issue1: Detected objects are given relative to the host_vehicle_location (this means the reference point of host_vehicle_location specifies the coordinate system that is used as a parent frame for e.g. DetectedMovingObjects). The coordinate system would then be for example origin=host_vehicle_location reference point with x-axis pointing in host vehicle front direction, y to left and z up. The reference point of the host_vehicle_location is the center of the rear axle (since this is used a lot). If the reference point of the host_vehicle_location is still chosen to be the center of the bounding box then the offset from the center of the bounding box to the center of the rear axle needs to be transported in some other way, but this information is necessary.
@issue2: Both the orientation R and the position t shall be defined as reference point of BaseMoving in the parent frame. And therefore the transformation equation would then be x_parent = R * x_base + t. This would then also be in line with the transformation notation that is most commonly used.
@issue3: map_reference in GroundTruth could be used to provide a string that specifies the reference coordinate and the ellipsoid.

**Comment by ThomasSchloemicherAVL** [comment]
#388

**Comment by ThomasSchloemicherAVL** [comment]
@u21n80 can you please check if PR #456 fixes this issue and to which extend.
@kmeids FYI

**Comment by u21n80** [comment]
The fix establishes a relation between bounding box and the other coordinate frames. But the documentation is still not very clear e.g. [this description](https://opensimulationinterface.github.io/open-simulation-interface/structosi3_1_1MovingObject_1_1VehicleAttributes.html#a310be4844cd22fcd937ee65f865c8bc5)
> For all vehicles, including host vehicles, the position given in MovingObject::base . BaseMoving::position points to the center of the vehicle's bounding box. The vehicle object coordinates are defined as x-axis is the direction from rear to front of the vehicle, y-axis corresponds to rear axle and z-axis points to vehicle ceiling [1]. The coordinate system is right-handed. Therefore the positive y-axis points to the left of the vehicle.

Since y axis is the rear axle the origin can never be the center of the bounding box. Here the wording is misleading, what they try to say is that y is parallel with the rear axle. Also this frame is called vehicle object frame, but later on only a object frame is referenced e.g. in bbcenter_to_rear. I would suggest to use the same name at all times to avoid confusion or misunderstandings.

Also in general it should not be just an offset, but an affine transformation, since it is not always guaranteed that there is no rotation between the rear axle and the bounding box.

**Comment by kmeids** [comment]
@u21n80 This makes total sense.
We are starting up a working group to revisit the coordinate axis definitions/concept and documentation.
Would you also be interested in joining it and directly providing your feedback?

**Comment by PhRosenberger** [comment]
@LukasElster is this fixed by #607 and https://github.com/OpenSimulationInterface/osi-documentation/pull/48 ?

**Comment by LukasElster** [comment]
I will adapt the documentation with an example of a coordinate transformation between 2 OSI coordinate systems and this will fix Issue2

**Comment by ThomasNaderBMW** [comment]
Output CCB 16.05.2022: Problem seems to be solved, otherwise please contact one of us.
