### ISSUE TITLE
Change user guide to new information structure

### ISSUE THREAD

**Issue by paagkame** [OpenSimulationInterface/open-simulation-interface#449]
#### Describe the feature
Within the harmonization of OpenX standards the information architecture of all standards shall be aligned.
This includes the document structure.

#### Describe the solution you would like
Within this branch we want to restructure the documentation step by step. 
Once every chapter is done, it will be merged back into the master while this branch stays open until the restructuring is done.

#### Describe alternatives you have considered
None.

#### Describe the backwards compatibility
The User guide will not be backward compatible, but no impact on the technical realisation of the standard.

**Comment by max-rosin** [comment]
Created branch `migration` for bundling changes during migration to AsciiDoc.
