### ISSUE TITLE
SensorData: what is ego_vehicle_id used for?

### ISSUE THREAD

**Issue by AndreasVIRES** [OpenSimulationInterface/open-simulation-interface#45]
In message SensorData there is an "ego_vehicle_id" defined as follows:

```
// The id of the ego vehicle in the ground_truth data.
optional Identifier ego_vehicle_id = 4;
```
For what do we need that?

**Comment by nHirsenkorn** [comment]
It is required to get the properties (position, dimensions, ...) of the own vehicle from groundtruth.

**Comment by AndreasVIRES** [comment]
So this is the ID of the vehicle, the sensor is attached to? 
This not necessarily has to be Ego.

**Comment by nHirsenkorn** [comment]
Yes this is the ID ot the vehicle, the senors are attached to.
When simulating the sensors of multiple vehicles in detail, there will be multiple "ego" vehicles.
According to the comment in message Vehicle, he vehicles which have sensors attached have to be ego.
