### ISSUE TITLE
Travis CI auto-deploy of gh-pages is broken

### ISSUE THREAD

**Issue by pmai** [OpenSimulationInterface/open-simulation-interface#451]
It seems that the deploy step in the travis CI pipeline, that pushes the current documentation for master onto the gh-pages branch is broken (probably sometime since April 2020). This causes all master builds to fail.

This should be examined, and potentially fixed. However this depends on our documentation strategy going forward, and whether we might want to switch from Travis CI to GitHub Actions for the build/CI infrastructure anyway.

**Comment by kmeids** [comment]
Builds are going through, closing the issue.
