### ISSUE TITLE
Centralizing Issues

### ISSUE THREAD

**Issue by paagkame** [OpenSimulationInterface/open-simulation-interface#458]
#### Describe the problem
Issues are created per repository. We usually look through the open-simulation-interface repository issues. But we never viewed the issues of other repositories like osi-validator etc..
There is even an issue from 2018 that hasn't been worked on.

#### Describe what you have already tried
I was looking for centralized project issues from all repositories, but couldn't find any. 

#### Describe your research
none.

#### Ask your question
Is there a way of viewing all issues on top level?
Or should we put that on the agenda for CCB- and group meetings?
Should we centralize all issues in one repository?

#### Additional context
none.

**Comment by pmai** [comment]
If you go to https://github.com/issues you can see all issues across github for your account; if you want to filter to just OSI, but have all issues, make sure to remove author:paagkame from your filter and to add user:OpenSimulationInterface (the organization name) to your filter.
