### ISSUE TITLE
Clear Statement on Ground Clearance and Bounding Box needed?

### ISSUE THREAD

**Issue by PhRosenberger** [OpenSimulationInterface/open-simulation-interface#467]
#### Describe the problem
I found no statement at the bounding box documentation or in the ground clearance's about their relation.
Therefore, I am not sure, if everybody get this right
So, I would suggest to add it.

#### Proposal
In file osi_detectedobject.proto change lines 158 - 163 to:
```
// The base parameters of the moving object.
//
// \note The bounding box does NOT includes mirrors for vehicles.
// \note The parent frame of \c base is the sensor's vehicle frame.
// \note The height includes the ground_clearance, so always goes from top to ground.
//
optional BaseMoving base = 2;
```

And in file osi_object.proto change lines 432 - 438 to:
```
// Static minimal distance in m of under-body plane to ground
// surface plane (i.e. disregarding driving dynamic effects or road
// surface effects) under neutral load conditions. Can be useful to
// approximate the clear area under a vehicle that a sensor can see
// through.
// The bounding box itself includes the ground clearance within the height.
//
optional double ground_clearance = 6;
```

#### Additional context
Relates to #444

**Comment by pmai** [comment]
I like this proposal.

**Comment by kmeids** [comment]
> #### Describe the problem
> I found no statement at the bounding box documentation or in the ground clearance's about their relation.
> Therefore, I am not sure, if everybody get this right
> So, I would suggest to add it.
> 
> #### Proposal
> In file osi_detectedobject.proto change lines 158 - 163 to:
> 
> ```
> // The base parameters of the moving object.
> //
> // \note The bounding box does NOT includes mirrors for vehicles.
> // \note The parent frame of \c base is the sensor's vehicle frame.
> // \note The height includes the ground_clearance, so always goes from top to ground.
> //
> optional BaseMoving base = 2;
> ```
> 
> And in file osi_object.proto change lines 432 - 438 to:
> 
> ```
> // Static minimal distance in m of under-body plane to ground
**// Static minimal distance or space from the lowest point of the vehicle, under neutral load conditions,**
**// to the surface plane below it.**
(I don't want to mention **ground**, since in some cases we may have a 
speed bumper under the vehicle,  unless you don't want to take this into consideration)
> // (i.e. disregarding driving dynamic effects or road
> // surface effects) under neutral load conditions. Can be useful to
> // approximate the **clearance** area under a vehicle that a sensor can see
> // through.
> // The bounding box itself includes the ground clearance within the height.

 // \note \c ground_clearance is included in the bounding box height.
(I would include this as a note, this is in Dimension3D or?)

> //
> optional double ground_clearance = 6;
> ```
> 
> #### Additional context
> Relates to #444

**Comment by PhRosenberger** [comment]
> **// Static minimal distance or space from the lowest point of the vehicle, under neutral load conditions,**
> **// to the surface plane below it.**
> (I don't want to mention **ground**, since in some cases we may have a
> speed bumper under the vehicle, unless you don't want to take this into consideration)

Yes, I agree.

> // \note \c ground_clearance is included in the bounding box height.
> (I would include this as a note, this is in Dimension3D or?)

Yes, and yes.

**Comment by PhRosenberger** [comment]
@kmeids have you already startet a PR or should I?

**Comment by kmeids** [comment]
@PhRosenberger not yet, please go ahead a start one.

**Comment by max-rosin** [comment]
Reviewed documentation changes and simplified language a bit (remove brackets and abbreviations, split longer sentences).
