### ISSUE TITLE
Change structure of OSI::TrafficCommand 

### ISSUE THREAD

**Issue by clemenshabedank** [OpenSimulationInterface/open-simulation-interface#476]
As discussed in the Architecture Group, the structure of TrafficCommand shall be changed. However I think we didn't clarify how the nesting should look like exactly. 

What about this suggestion:

```
TrafficCommand
    InterfaceVersion 
    Timestamp
    Identifier 
    TrafficAction
         FollowTrajectoryAction
             ...
         FollowPathAction 
             ...
         ...
```
I think the following definitions should be reused in the TrafficActions: 
message ActionHeader, enum FollowingMode, enum DynamicsShape, message DynamicConstraints
Shall we write those on the level of the FollowTrajectoryAction, FollowPathAction, etc.?

@ThomasNaderBMW I think you "volunteered" us for implementing it ;) What do you think? 
@pmai or did you take it as a TODO? What do you think?
@kmeids FYI (if you have comments about it)

**Comment by kmeids** [comment]
@clemenshabedank Looks good from my side!
