### ISSUE TITLE
Discuss possible Precipitation states / definitions

### ISSUE THREAD

**Issue by SoykaDaimler** [OpenSimulationInterface/open-simulation-interface#48]
Hi all,
I suggested to include precipitation states as enums (see reference to branch below).
We should agree on which states we want to have or if we want to define them differently (e.g. rain intensity in cubic meters per hour).

**Comment by CarloVanDriestenBMW** [comment]
> +    // Atmospheric pressure in atm
> +    optional double atmospheric_pressure = 4;
However, I think we should use Pascal instead of atm as that is the SI unit for pressure.

> +    // Temperature in degrees celsius
> +    optional double temperature = 5;

I think we can include these two right away, because they are well defined

**Comment by pmai** [comment]
Since we are talking about SI units, shouldn't the temperature be in Kelvin?

**Comment by CarloVanDriestenBMW** [comment]
[Wikipedia](https://en.wikipedia.org/wiki/Rain#Measurement)
> Rainfall intensity is classified according to the rate of precipitation:
> 
>     Light rain — when the precipitation rate is < 2.5 mm per hour
>     Moderate rain — when the precipitation rate is between 2.5 mm - 7.6 mm or 10 mm per hour
>     Heavy rain — when the precipitation rate is > 7.6 mm per hour, or between 10 mm and 50 mm per hour
>     Violent rain — when the precipitation rate is > 50 mm per hour

I don't want to be that Wikipedia guy, but after checking the original reference we could do it like that?

@pmai Yes, Kelvin would be fine for me and actually SI

**Comment by CarloVanDriestenBMW** [comment]
The "Rain intensity enum" may be changed in future according to a more apropriate source of information, but maybe just in the comments
