### ISSUE TITLE
Extendend object classes

### ISSUE THREAD

**Issue by SoykaDaimler** [OpenSimulationInterface/open-simulation-interface#49]
Hi all,
I suggested to include extended object class definitions  (see reference to branch below).
We should check that we do not add classes which are not supported by the tools. So input from VIRES and IPG would be appreciated. @AndreasVIRES 
Originally we had a special hex coded scheme which allowed filtering in super and sub classes. However, hex encoding is not supported by protobuf. Maybe we could come up with an alternative scheme. Ideas are welcome!

**Comment by AndreasVIRES** [comment]
There is a definition in OpenSCENARIO:
- car
- van
- truck
- trailer
- semitrailer
- bus
- motorbike
- bicycle
- train
- tram
- pedestrian
- wheelchair
- animal
- barrier
- guard rail

**Comment by SoykaDaimler** [comment]
I'm just comparing it to the OSI types available so far.
I think van (currently part of car), semitrailer and bus are missing in vehicle types.
In moving object: wheelchair, tram and train are missing.
And in stationary object we don't have barrier or guard rail, but instead we have bridge, building, pylon, reflector post and delineator.
These types should be merged and OSI should have the same types as supported by the tools.

**Comment by AndreasVIRES** [comment]
There are more in OpenDRIVE (http://www.opendrive.org/docs/OpenDRIVEFormatSpecRev1.4H.pdf):

6.6 Object Types
The known keywords for the object type information are:

- none (i.e. unknown)
- obstacle (for anything not further categorized)
- car
- truck
- van
- bus
- trailer
- bike
- motorbike
- tram
- train
- pedestrian
- pole
- tree
- vegetation
- barrier
- building
- parkingSpace
- wind
- patch

6.7 Tunnel Types
The known keywords for the tunnel type information are:

- standard
- underpass (i.e. sides are open for daylight)

6.8 Bridge Types
The known keywords for the bridge type information are:

- concrete
- steel
- brick
- wood

**Comment by raueATconti** [comment]
just a side note: depends where you are, the interpretation of some of the above mentioned terms differs;
e.g. truck: US -> rather a sort of SUV; Germany -> heavy truck (LKW); 
perhaps we should add some comments to the existing terms to make it specific enough;

**Comment by CarloVanDriestenBMW** [comment]
bump: @carsten-kuebler maybe we can make a compare here too? I guess we should do this for 3.1.0 and research the differences to OpenScenario and OpenDrive

**Comment by CarloVanDriestenBMW** [comment]
done
