### ISSUE TITLE
Harmonisation: AUTOSAR

### ISSUE THREAD

**Issue by jdsika** [OpenSimulationInterface/open-simulation-interface#492]
I would like to put the topic of "Harmonisation with Autosar" on the agenda for future releases. There is a [document](https://www.autosar.org/fileadmin/user_upload/standards/adaptive/20-11/AUTOSAR_EXP_SensorInterfaces.pdf) which also complies with the ISO23150. I think we have to make sure to clearly mark the use cases for both standards.

**Comment by thempen** [comment]
Waiting for Memorandum of Understanding between ASAM e.V. and AUTOSAR

**Comment by stefancyliax** [comment]
Collaboration between AUTOSAR and ASAM is clarified. All OSI contributions are under MPLv2. 
For the Harmonization Florian Müller is appointed from BMW side.

**Comment by jdsika** [comment]
Closing with issues created by @FlorianMueller87 example #643
