### ISSUE TITLE
Harmonization of road mark colors with OpenDRIVE

### ISSUE THREAD

**Issue by stefancyliax** [OpenSimulationInterface/open-simulation-interface#504]
#### Harmonization of road mark colors with OpenDRIVE
OSI LaneBoundary and RoadMarking elements offer color VIOLET, which is not part of the OpenDRIVE definitions, while OpenDRIVE offers ORANGE, which is not part of the OSI definition.

According to BMW (Driesten, ...) violet is not used anywhere.
Related ticket in OpenDRIVE: https://code.asam.net/simulation/standard/opendrive/-/issues/35

#### Describe the solution you would like
- Removal of Violet to OSI
- Adding of Orange to OSI

#### Describe alternatives you have considered
-

#### Describe the backwards compatibility
Since violet is presumably not used anywhere, the removal should not be a problem.

**Comment by HendrikAmelunxen** [comment]
Outcome Harmonization 15.04.21
violet: mark as deprecated
orange: add to enum
=> Marcel Sachse will take care of it

**Comment by clemenshabedank** [comment]
@jdsika https://www.triflex.com/en/casestudy/bicycle-asphalt-marking ;)

**Comment by jdsika** [comment]
Haha, so we put it as a ticket into consideration for the next open drive version :D

**Comment by stefancyliax** [comment]
reopened the ticket in OpenDRIVE  😄
