### ISSUE TITLE
Centralize and unify color codings

### ISSUE THREAD

**Issue by HendrikAmelunxen** [OpenSimulationInterface/open-simulation-interface#512]
#### Describe the feature
Currently the color enumerations are distributed ("osi_roadmarking.proto", "osi_object.proto", "osi_lane.proto", "osi_featuredata.proto") and not aligned; e.g. COLOR_VIOLET = 5 (osi_object.proto) vs. COLOR_VIOLET = 8 (osi_lane.proto).

#### Describe the solution you would like
It would make sense to have a central definition of the color codings, e.g. in osi_common.proto.

#### Describe the backwards compatibility
Since the different codings are not aligned, the centralization and alignment would break backward compatibility; colors will be interpreted different.

**Comment by MarcelOliver** [comment]
At the moment, color is defined in four different files (osi_lane, osi_object, osi_featuredata and osi_roadmarking) as shown here:

osi_lane.proto:

    COLOR_UNKNOWN = 0;
    COLOR_OTHER = 1;
    COLOR_NONE = 2;
    COLOR_WHITE = 3;
    COLOR_YELLOW = 4;
    COLOR_RED = 5;
    COLOR_BLUE = 6;
    COLOR_GREEN = 7;
    COLOR_VIOLET = 8;
    COLOR_ORANGE = 9;

osi_object.proto:

    COLOR_UNKNOWN = 0;
    COLOR_OTHER = 1;
    COLOR_YELLOW = 2;
    COLOR_GREEN = 3;
    COLOR_BLUE = 4;
    COLOR_VIOLET = 5;
    COLOR_RED = 6;
    COLOR_ORANGE = 7;
    COLOR_BLACK = 8;
    COLOR_GREY = 9;
    COLOR_WHITE = 10;

osi_featuredata.proto:

    COLOR_UNKNOWN = 0;
    COLOR_OTHER = 1;
    COLOR_BLACK = 2;
    COLOR_GREY = 3;
    COLOR_WHITE = 4;
    COLOR_YELLOW = 5;
    COLOR_ORANGE = 6;
    COLOR_RED = 7;
    COLOR_VIOLET = 8;
    COLOR_BLUE = 9;
    COLOR_GREEN = 10;
    COLOR_REFLECTIVE = 11;

osi_roadmarking.proto:

    COLOR_UNKNOWN = 0;
    COLOR_OTHER = 1;
    COLOR_WHITE = 2;
    COLOR_YELLOW = 3;
    COLOR_BLUE = 5;
    COLOR_RED = 6;
    COLOR_GREEN = 7;
    COLOR_VIOLET = 8;
    COLOR_ORANGE = 9;

**Comment by HendrikAmelunxen** [comment]
From an ODR-OSI harmonization point of view, a central and unified enum for colors would be sufficient.
@kmeids Are there any additional requirements from a sensor-model point of view, e.g. describing colors via RGB values?

**Comment by kmeids** [comment]
@HendrikAmelunxen, currently there are no specific requirements from the sensor-model point of view.
If new requirements arise they can be currently handled with the "COLOR_OTHER" till a concrete request is provided.
