### ISSUE TITLE
Version 3.3.0 is still version 3.2.0

### ISSUE THREAD

**Issue by slietzau** [OpenSimulationInterface/open-simulation-interface#515]
#### Describe the bug
For Release 3.3.0 the version number was not increased, see here:
https://github.com/OpenSimulationInterface/open-simulation-interface/blob/v3.3.0/VERSION

#### Describe how to reproduce the bug
Install with pip:
```
pip install git+https://github.com/OpenSimulationInterface/open-simulation-interface@v3.3.0
```
Get the following output from `pip list`
```
open-simulation-interface 3.2.0
```

#### Describe the expected behavior
The version of the release tag should match the version in the package.

**Comment by stefancyliax** [comment]
You are correct. There was an overside. This will be fixed with https://github.com/OpenSimulationInterface/open-simulation-interface/pull/513 and release 3.3.1

**Comment by stefancyliax** [comment]
Fixed now. New Release 3.3.1 will include correct version.
