### ISSUE TITLE
OSI Matlab support

### ISSUE THREAD

**Issue by andreaslebherz** [OpenSimulationInterface/open-simulation-interface#524]
Hello,
I was wondering if there is any direct .osi support planned for Matlab? 

I am currently using a Matlab (2021a) toolbox (Driving Scenario Designer) to create and simulate traffic scenarios. The output are object detections, which I want to further process using filters and tracking-algorithms implemented in Python. As an interface for the sensor detections, I want to use the .osi file format. 

For this reason I need to export Matlab data to .osi files and am looking for a way to do so. The idea is that at some point I plan to replace the virtual-scenarios from Matlab with real data so a defined interface seems reasonable.

The only possibility I see currently is to export Matlab object-detections to Python and then export the data to .osi files. 

Any help is very much appreciated. Thanks in advance!

**Comment by thempen** [comment]
Hi @andreaslebherz,

the "direct Matlab support" is not in responsibility of the OSI working group. We are using Google ProtoBuf, therefore, the possibility to compile it to a certain language is within the repsonsibility of Google.

Nonetheless, the usage of OSI in Matlab is possible:
We tried to compile it to matlab script, without success. Many problems occured, we didn't want to solve.

So the way to go:
Matlab does support the usage of Java. Therefore we compiled it to Java an imported it to Matlab.
To compile it, you can use protec. Usually you can find the compiling tools on the protobuf page: https://github.com/protocolbuffers/protobuf

To use it, we made a Shell script to convert everything to a *.jar file. Afterwards you can import it to Matlab Simulink.
```
CONVERT_FOLDER="convert_java"
JAVAC_FOLDER="/usr/lib/jvm/java-8-openjdk-amd64/bin"
PROTOBUF_JAVA_FOLDER="/usr/share/java"
PROTOBUF_JAVA_NAME="protobuf-java-3.14.0.jar"
EXPORT_PROTO_FILENAME="EXPORT_PROTO_OSI.jar"
mkdir -p $CONVERT_FOLDER

# Compile proto messages for java
for f in osi_version.proto.in osi_*.proto
do
echo $f
protoc $f --java_out=./$CONVERT_FOLDER
done

# Generate class files from protoc-messages
cd $CONVERT_FOLDER
$JAVAC_FOLDER/javac osi3/*.java -cp $PROTOBUF_JAVA_FOLDER/$PROTOBUF_JAVA_NAME

# Pack class files
jar cvf ./$EXPORT_PROTO_FILENAME osi3/*.class
```

Best regards
Thomas

**Comment by andreaslebherz** [comment]
Thank you very much @thempen for this information and providing the script!
