### ISSUE TITLE
Reworking BoundingBoxes

### ISSUE THREAD

**Issue by thempen** [OpenSimulationInterface/open-simulation-interface#526]
This issue is corresponding to issue #444 and pull request #461 and is used as a reminder to discuss the topics for version 4.0.
For further details, please read the references.

Currently the BoundingBox is very strict according to its definition. The whole vehicle is included, except the side mirrors. 
This should be more flexible in the future.

Corresponding to that, the contour lane should be redefined. It is not clearly defined, e.g. if it contains the side mirrors.

Therefore a new concept for the BoundingBox and ContourLine should be defined.

Best regards
Thomas

**Comment by clemenshabedank** [comment]
It currently looks like the following attributes of vehicles will potentially not necessarily be static anymore in OpenSCENARIO v1.2, because an AnimationStateAction might be introduced: 
```
                <xsd:enumeration value="hood"/>
                <xsd:enumeration value="trunk"/>
                <xsd:enumeration value="doorFrontRight"/>
                <xsd:enumeration value="doorFrontLeft"/>
                <xsd:enumeration value="doorRearRight"/>
                <xsd:enumeration value="doorRearLeft"/>
                <xsd:enumeration value="windowFrontRight"/>
                <xsd:enumeration value="windowFrontLeft"/>
                <xsd:enumeration value="windowRearRight"/>
                <xsd:enumeration value="windowRearLeft"/>
                <xsd:enumeration value="sideMirrors"/>
                <xsd:enumeration value="sideMirrorLeft"/>
                <xsd:enumeration value="sideMirrorRight"/>
```
compare https://code.asam.net/simulation/openscenario-1/openscenario/-/issues/10

This probably is a good inspiration for the concept here @thempen @HendrikAmelunxen

**Comment by ndunningbmw** [comment]
Based on the conversation of the Working Group today (2022.10.10), it seems like a simple extension of the bounding box would introduce additional problems along with any it aims to solve. 

The image below shows the bounding box of a vehicle (in green) extended to the edges of the side mirrors (in blue). In this case, the rear-left corner of the bounding box would overlap with the neighboring lane even though no parts of the vehicle actually cross into said lane, and potentially leading to a false classification of where the bounds of the vehicle actually are.
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/20393110/194884475-efd45300-83a1-45c7-8192-02a5492eca9a.png">
