### ISSUE TITLE
Antecessor and successor definition for lanes 

### ISSUE THREAD

**Issue by FabianPfeufferCAP** [OpenSimulationInterface/open-simulation-interface#530]
#### Describe the problem
I'm currently working with OSI lanes and need some clarification on a part of the standard, that is unclear to me. 
It seems that the OSI standard doesn't clarify how antecessor_lane_id and successor_lane_id have to be set for non-driving lanes. 

#### Describe your research

From my understanding, for driving lanes, the antecessor_lane_id denotes the lane(s) at the beginning (first centerline point), the successor_lane_id the lane(s) at the end (last centerline point) of a given OSI lane. If the "centerline_is_driving_direction" attribute is false, the opposite is the case, i.e. the antecessor is connected to the OSI lane's last and the successor to its first centerline point.

I check the documentation for OSI lane pairing and OSI lanes in general, but couldn't find any information regarding this topic. However, the standard explicitly says that non-driving lanes should not have a centerline ( https://opensimulationinterface.github.io/open-simulation-interface/structosi3_1_1Lane_1_1Classification.html ) :

"... non-driving lanes do not have a center line. A vehicle must calculate this individually and depending on the situation."

#### Ask your question
So with neither the centerline, nor the centerline_is_driving_direction, how should the antecessor_lane_id and successor_lane_id be determined?
Does the lane boundary define the orientation for non-driving lanes, i.e. is the antecessor connected to the first and the successor connected to the last lane boundary point?

**Comment by HendrikAmelunxen** [comment]
Please see [https://github.com/OpenSimulationInterface/open-simulation-interface/issues/411](Issue 411) and [https://github.com/OpenSimulationInterface/open-simulation-interface/pull/460](PR 460)

Defining the left/right/antecessor/succesor lanes with regard to the intended driving direction was problematic/inconsistent for different reasons. That is why this has been changed for  OSI 3.3.

**Comment by clemenshabedank** [comment]
Closed. Arguments see https://github.com/OpenSimulationInterface/open-simulation-interface/pull/542.

**Comment by clemenshabedank** [comment]
Closed. Arguments see https://github.com/OpenSimulationInterface/open-simulation-interface/pull/542.

**Comment by clemenshabedank** [comment]
Closed. Arguments see https://github.com/OpenSimulationInterface/open-simulation-interface/pull/542.
