### ISSUE TITLE
Add environmental conditions to bring in line with OpenSCENARIO 1.x

### ISSUE THREAD

**Issue by caspar-ai** [OpenSimulationInterface/open-simulation-interface#544]
#### Describe the feature
Adding environmental conditions to OSI to match some of those already present in OpenSCENARIO 1.x.

Specifically, the following fields are present in the OSC [`Environment` structure](https://www.asam.net/static_downloads/modelDocumentation/content/Environment.html):

- [Sun azimuth, elevation, and intensity](https://www.asam.net/static_downloads/modelDocumentation/content/Sun.html)
    - Note this has some relation to the existing [OSI 'AmbientIllumination` field](https://github.com/OpenSimulationInterface/open-simulation-interface/blob/master/osi_environment.proto#L235)
- [Cloud state](https://www.asam.net/static_downloads/modelDocumentation/content/CloudState.html)
- [Fog bounding box](https://www.asam.net/static_downloads/modelDocumentation/content/Fog.html)
- [Precipitation type](https://www.asam.net/static_downloads/modelDocumentation/content/PrecipitationType.html)
    - Already covered by the existing #415 but mentioned here for completeness
- [Wind direction and speed](https://www.asam.net/static_downloads/modelDocumentation/content/Wind.html)

#### Describe the solution you would like
New fields added to the existing `EnvironmentalConditions` message.

#### Describe alternatives you have considered
Existing pattern so no other alternatives considered.

#### Describe the backwards compatibility
No issues for backwards compatibility, all new fields will be optional.

#### Additional context
This purpose of this ticket isn't to do full alignment, in particular there are existing disconnects between OSC and OSI where one uses a continuous value and the other uses an enum.  That is a more complicated discussion and is already covered by #255 and so is considered outside the scope of this issue.

**Comment by HendrikAmelunxen** [comment]
Closed; https://github.com/OpenSimulationInterface/open-simulation-interface/pull/593 is merged
