### ISSUE TITLE
Removal of repeated notes in all documentation

### ISSUE THREAD

**Issue by stefancyliax** [OpenSimulationInterface/open-simulation-interface#556]
I see this note repeated over and over again across all files. A quick search yields 70 hits for this exact phrase.

I do not know the original reason for including the note, but I suggest to just remove it. In my opinion, it is stating the obvious. The field is a repeated field and its name uses in fact singular. Furthermore, the above text makes it abundantly clear that there may be multiple IDs. 

However, I would also suggest to add this information to the [interface-conventions topic](https://github.com/OpenSimulationInterface/osi-documentation/blob/migration/contributing/naming_conventions.adoc) in the general documentation.

_Originally posted by @max-rosin in https://github.com/OpenSimulationInterface/open-simulation-interface/pull/491#discussion_r675601739_

**Comment by max-rosin** [comment]
To clarify, the note in question is:

`\note OSI uses singular instead of plural for repeated field names.`

It appears in the comments of the .proto files.

**Comment by PhRosenberger** [comment]
I would agree to @stefancyliax to just delete the note everywhere.
