### ISSUE TITLE
Add subType to VehicleClassification in alignment with OpenSCENARIO 1.2

### ISSUE THREAD

**Issue by adrianschultz** [OpenSimulationInterface/open-simulation-interface#584]
#### Describe the feature
In OpenSCENARIO there is a VehicleCategory (comparable to VehicleClassification/Type see: https://www.asam.net/static_downloads/modelDocumentation/content/VehicleCategory.html) to describe a Vehicle. This will be extended with a VehicleType for Vehicle, with values "Ambulance", "Fire", "Police", "Road assistance vehicle".

To align the standards in that regard, the VehicleType  could be added to VehicleClassification as SubType enum.

#### Describe the backwards compatibility
This should be fully backward compatible as it is only adding an optional enum to VehicleClassification .

**Comment by HendrikAmelunxen** [comment]
Output from a discussion during OIS-CCB meeting:
It would make sense to separate the classification of Fire, Police, Ambulance, etc. from the VehicleType. By this, combinations like police vehicles, police vans, police busses, fire semitrailers, fire trucks, etc. can be covered. Maybe this is also applicable for OSC?

**Comment by adrianschultz** [comment]
![VehicleRole](https://user-images.githubusercontent.com/82088730/150479200-11c71393-9029-4202-a73a-41d3aaf32a30.png)

This was implemented in OpenSCENARIO and will most probably be part of the 1.2 release.

Therfore I propose to add something similar to MovingObject in OSI. Then we would have the possibility to set a VehicleClassification and a VehicleRole like it was suggested in the CCB
