### ISSUE TITLE
Align TrafficLight with OpenDRIVE and OpenSCENARIO

### ISSUE THREAD

**Issue by adrianschultz** [OpenSimulationInterface/open-simulation-interface#611]
#### Describe the feature
In osi3::TrafficLight::Classification::Icon: the following fields are missing ICON_ARROW_LEFT_U_TURN, ICON_ARROW_RIGHT_U_TURN, ICON_BICYCLE_RIGHT, ICON_BICYCLE_LEFT and those for trams and buses
![Screenshot 2022-01-11 132704](https://user-images.githubusercontent.com/82088730/150482407-4780d37e-cca6-4fae-b49a-3edc6deed624.png)

The osi3::TrafficLight::Classification::Mode MODE_FLASHING should have a additional field for the frequency (or a durationOn and durationOff) like MODE_COUNTER has a double field counter. 

Would it make sense to deprecate osi3::TrafficLight::Classification::Color and therfore include a  osi3::TrafficLight::Classification::State or  osi3::TrafficLight::Classification::Phase including off, stop, attention, stop_attention, go, go_exclusive?

#### Describe the backwards compatibility
Just adding optional features.
For 4.0.0 we could rename it to TrafficSignal and discuss the handling of dynamics traffic signals in general (, e.g. the ones above highways or a lane closed etc) and not just traffic lights

**Comment by adrianschultz** [comment]
I added a PR (#614), which we can discuss in the group next week

**Comment by thempen** [comment]
OtherModels and Harmonization group meeting: Closed. See PR #614 .
