### ISSUE TITLE
Broken link for windows installation

### ISSUE THREAD

**Issue by jruebsam** [OpenSimulationInterface/open-simulation-interface#618]
Currently the link provided by this repository is broken and needs to be updated.  

https://opensimulationinterface.github.io/osi-documentation/open-simulation-interface/doc/windows.html

**Comment by jdsika** [comment]
thx, I think [this](https://opensimulationinterface.github.io/osi-documentation/#_installing_osi_for_c_on_windows) is the one you are searching for?

**Comment by jruebsam** [comment]
Yes looks like the right one.

**Comment by PhRosenberger** [comment]
@jdsika and @jruebsam Can we close this issue?
