### ISSUE TITLE
Unclear meaning of traffic sign - variability

### ISSUE THREAD

**Issue by HendrikAmelunxen** [OpenSimulationInterface/open-simulation-interface#623]
#### Describe the bug
The meaning of "variability" in the traffic sign is not clear.
The first description states that it should be used for objects which might change in position (for example temporary traffic signs in construction areas):
![image](https://user-images.githubusercontent.com/26961302/162473150-306330f4-c4e5-4660-9f6d-80c6b796af45.png)

The description in the enum states that it should be used for traffic signs which content might change (for example electronic traffic signs on a sign bridge):
![image](https://user-images.githubusercontent.com/26961302/162473565-c2254436-81b9-4319-a0f0-7b5d2fadfcc5.png)

The meaning of the variability property should be clarified.

**Comment by thempen** [comment]
The unclarity was merged. #671
