### ISSUE TITLE
Wiki: How to write correct Doxygen commets for OSI

### ISSUE THREAD

**Issue by CarloVanDriestenBMW** [OpenSimulationInterface/open-simulation-interface#63]
As proposed by @PhilippRoethigBMW a user needs a guideline to commet the osi proto files correctly.

**Comment by PhilippRoethigBMW** [comment]
Just added the wiki page on how to comment. @CarloVanDriestenBMW please have a look.

**Comment by CarloVanDriestenBMW** [comment]
Very good Wiki Page - Thnak you @PhilippRoethigBMW !
