### ISSUE TITLE
cmake: x86, x64, debug, release

### ISSUE THREAD

**Issue by CarloVanDriestenBMW** [OpenSimulationInterface/open-simulation-interface#66]
As a user I would like the Open Simulation Interface to be easily configured for different targets and build versions.
The cmake file should be configured accordingly and the install wiki needs an update afterwards.

**Comment by pmai** [comment]
Isn't that working correctly today already?

**Comment by CarloVanDriestenBMW** [comment]
Did you test all possibilies?

**Comment by pmai** [comment]
At least with the current (non-renamed) build system I had no problems building for x86/x64 both release and debug builds on windows and for linux x86/x64 as well. And I currently don't see anything special in the cmake files that should prevent this from working as designed. That said feel free to include more testing, I was just curious if there was a specific reason for this ticket...

**Comment by AhmedMzid** [comment]
After successfully testing different building configurations under windows and linux, I have updated the wiki page with some additional information about the building process.

**Comment by CarloVanDriestenBMW** [comment]
Thank you!
