### ISSUE TITLE
New vehicle classification in GroundTruth for stand-up scooters

### ISSUE THREAD

**Issue by schmidtlorenz** [OpenSimulationInterface/open-simulation-interface#673]
#### Describe the feature
OSI GroundTruth should have adequate vehicle classifications for all NCAP targets that already exist or will be added in the future. A new relevant target might be electric stand-up scooters. The current vehicle types do not include a fitting classification for stand-up scooters. A human-powered stand-up scooter would fit the classification as a pedestrian, while a motorized variant might better fit the bicycle classification, due to its higher velocity.

#### Describe the solution you would like
 I suggest adding a new enum for stand-up scooters in vehicle types.

`// Vehicle is a stand-up or kickboard scooter, including motorized variants.`
`TYPE_STANDUP_SCOOTER = 16;`

#### Describe alternatives you have considered
Alternative would be using an overarching category like personal light electric vehicle, personal/powered transporter or electric rideable which would include other vehicles, e.g. Segways, unicycles and electric skateboards. An argument against this classification follows: This overarching category would be for vehicles of significantly different shapes rendering this classification unfavorable for sensor recognition.

**Comment by jdsika** [comment]
Can be closed as completed
