### ISSUE TITLE
UML Diagramm / Visualization Tool

### ISSUE THREAD

**Issue by nHirsenkorn** [OpenSimulationInterface/open-simulation-interface#7]
An UML-style diagram for the proto messages would help to get a fast overview.
Other visualization types would also fit.

**Comment by CarloVanDriestenBMW** [comment]
@nHirsenkorn 
https://github.com/malisas/schema-uml

I don't have linux yet ...

**Comment by CarloVanDriestenBMW** [comment]
We do have a propper Doxygen documentation (see newest readme.md). Do you think the UML description of the messages is good this way? @nHirsenkorn

**Comment by CarloVanDriestenBMW** [comment]
Maybe @SchallerBMW could also check, if the diagrams are fine now, because you will eventually work through the documentation :) ?

**Comment by CarloVanDriestenBMW** [comment]
That seems to be solved by #95 , @carsten-kuebler ?

**Comment by carsten-kuebler** [comment]
We can change to an UML diagram look & feel with the configuration parameter "UML_LOOK = YES". Drawbacks: Doxygen for proto script doesn't support UML diagrams. 
1. You can't get the cardinality information 
    e.g. Protomessage: OSI:xxx … repeated OSI:yyy    -->  UMLdiagram: OSI:xxx 1 --------- 0..* OSI:yyy
2. Basic datatypes of attributes are not recognized.
3. Enums are not recognized.

I will show some diagrams and discuss the pro and cons (osi::LowLevelData) with the used **proto2cpp** script.

A)	Actual collaboration diagram (HIDE_UNDOC_RELATIONS=NO and UML_LOOK=NO):
 
![lowleveldata_hide_undoc_relations_no_uml_look_no](https://user-images.githubusercontent.com/32508295/34828213-1aaa4ef2-f6dd-11e7-8e7b-7f9e45ba404b.png)

Pro: all attributes are visualized.
Con: No UML-class diagram; repeated attributes aren’t included.


B)	A simpler collaboration diagram (HIDE_UNDOC_RELATIONS=YES and UML_LOOK=NO) used in previous osi documents:
 
![lowleveldata_hide_undoc_relations_yes_uml_look_no](https://user-images.githubusercontent.com/32508295/34828240-302ff0a6-f6dd-11e7-9e40-848a72e620dd.png)

Pro: -
Con: No UML-class diagram; repeated attributes aren’t included, attributes to basic datatypes or repeated attributes aren’t visualized.

If we change from collaboration diagram to UML-diagrams:

C)	Actual collaboration diagram (HIDE_UNDOC_RELATIONS=YES and UML_LOOK=YES):
 
![lowleveldata_hide_undoc_relations_yes_uml_look_yes](https://user-images.githubusercontent.com/32508295/34828329-8555191c-f6dd-11e7-8fcd-5dae60f74838.png)

Pro: Attributes to basic datatypes or repeated attributes are included. 
Con: Cardinalities between RadarReflection and RadarReflectionList are missing; basic datatypes are missing; repeated attributes are missing (eg. reflection  RadarReflection is missing or x,y,z  double is not mentioned)
![radarreflection_hide_undoc_relations_yes_uml_look_yes](https://user-images.githubusercontent.com/32508295/34828440-dacc99f6-f6dd-11e7-95d0-657b54717e4e.png)


D)	Actual collaboration diagram (HIDE_UNDOC_RELATIONS=NO and UML_LOOK=YES):

![lowleveldata_hide_undoc_relations_no_uml_look_yes](https://user-images.githubusercontent.com/32508295/34828341-8fa22784-f6dd-11e7-915f-02e24edfb015.png)

Pro: Repeated attributes are included. 
Con: Cardinalities between RadarReflection and RadarReflectionList are missing; repeated attributes are missing (eg. RadarReflection is missing). UML attribute fields are empty.


Enumerations aren’t visualized at all (eg. LidarPoint reflection_type):

A) ![lidarpoint_hide_undoc_relations_no_uml_look_no](https://user-images.githubusercontent.com/32508295/34828468-f19cab62-f6dd-11e7-9955-45b1bb89c02f.png)

B) ![lidarpoint_hide_undoc_relations_yes_uml_look_no](https://user-images.githubusercontent.com/32508295/34828476-f533cca6-f6dd-11e7-88ed-67934dd00dfb.png)

C) ![lidarpoint_hide_undoc_relations_yes_uml_look_yes](https://user-images.githubusercontent.com/32508295/34828482-f93be676-f6dd-11e7-9a8b-2fcff4d9867a.png)

D) ![lidarpoint_hide_undoc_relations_no_uml_look_yes](https://user-images.githubusercontent.com/32508295/34828490-fc9b4e1a-f6dd-11e7-830f-2e14c4c0f23e.png)


The mentioned PYTHON script **https://github.com/malisas/schema-uml** has also some drawbacks...
 
![uml](https://user-images.githubusercontent.com/32508295/34828522-246e3c4a-f6de-11e7-9a87-be0485999e70.png)

Pro: Enums are visualized; package graph is included; repeated attributes are visualized
Con: Script visualize complete proto files and not every proto message; aggregation links has no cardinalities; overlapping visualization; basic datatypes are missing.


**Resume: I think the diagrams are ok. If we want to change to UML diagrams we have no benefit.**

**Comment by CarloVanDriestenBMW** [comment]
@carsten-kuebler thank you very much for this detailled answer! I would then go with your recommendation and not support the change to UML. What do you think @pmai

**Comment by pmai** [comment]
I completely agree, closing this issue accordingly.
