### ISSUE TITLE
Traffic Lights

### ISSUE THREAD

**Issue by IgorBelyakovIntel** [OpenSimulationInterface/open-simulation-interface#70]
Hi,
I have two questions regarding traffic lights in OSI specification:
1. How to code horizontal traffic light. Can orientation parameter from BaseStationary structure be used here?
2. How to code number of lights in the traffic light (1 or 2 or 3).

Igor

**Comment by PhilippRoethigBMW** [comment]
I agree with you on the first question. You can use BaseStationary (Orientation3d) to position the traffic light the way you want it to be.

But neither does OSI define the physical number of lights nor the exact position of every single light bulb. What it does it describes the logical state of your entire traffic light.
So for example if your traffic light has only two lights (green and red) you exclusively use the states GREEN and RED.

**Comment by CarloVanDriestenBMW** [comment]
Is this OK for you @IgorBelyakovIntel or do you need something else?

**Comment by CarloVanDriestenBMW** [comment]
![grafik](https://user-images.githubusercontent.com/25304009/35442709-7cb1ef48-02a8-11e8-89cc-42fc9631e717.png)

Because of the standardization proposal there might be a change - to be discussed!

**Comment by carsten-kuebler** [comment]
@CarloVanDriestenBMW the standardization proposal is still a draft version. Additional feedback from sensor manufacturer is still missing.

**Comment by ecazaubon** [comment]
I do not know if you want to go to full international yet or not, but there are some traffic lights (I checked they exist at least in France and Belgium but are illegal in Germany) with the color pattern Red-Yellow-Yellow and which cycle is Red -> Blinking lower yellow light (means go carefully) -> Middle Yellow Light -> Red. 
Problem is with current OSI version a working traffic light with this cycle when in "go carefully" state (Bottom light blinking) has the same state as an out of order traffic light (Middle light blinking). 
Am I correct ?

**Comment by ecazaubon** [comment]
@CarloVanDriestenBMW  That is the issue I talked to you about.

**Comment by ppannusch** [comment]
@CarloVanDriestenBMW 
@carsten-kuebler 

Proposal for new definition of traffic lights:
TrafficLight does not describe the whole object containing different lights, but describes every light "box" as single object. Like this you can easily shift positions, have only 2 or just 1 light etc.

TrafficLight:
- repeated assigned lane
- type: normal, pedestrian, bicycle, tram/bus, tram, bus, pedestrian/bicycle, taxi
- colors: remove red_yellow (only one bulb), add white, blue
- mode: rename blinking to flashing
- shape: add pedestrian, bicycle, pedestrian/bicycle, .. -> create issue for tram shapes; add shape CountDown and optional value field in LightState if this shape is used
- remove GreenArrowPresence as it's either another light or a traffic sign

**Comment by carsten-kuebler** [comment]
@ppannusch do we need type and shape? We get the same information for type from assigned lane and shape.

**Comment by CarloVanDriestenBMW** [comment]
@carsten-kuebler , I guess we do not have this many types for lanes, but we could consider adding the types in the lane types and take the information from there? What do you think @ppannusch ?
The shapes are related to the "pictures" seen in traffic light - the question is e.g.: Does every traffic light for pedestrians have the pedestrian "picture"? Is that a rule? Does it apply for all countries?

**Comment by carsten-kuebler** [comment]
Yes, we do not have all types of lanes, but if we have traffic lights (which a vehicle has to regard) the traffic lights should be assigned to the "ego/host" lane. No pedestrian light assigned to a crosswalk should be assigned to the driving lane. If we do not model the crossswalk lane as an orthogonal pedestrian lane in GT, the pedestrian traffic light should be assigned to no lane. In my opinion a crosswalk could be a nondriving lane which cross/superpose driving lanes.

I sketched two possible GTs.

1. Superpose
![trafficsignlane1](https://user-images.githubusercontent.com/32508295/37147386-093b8e4a-22c7-11e8-997d-3f74ebf2ec9b.jpg)

2. Intersection
![trafficsignlane2](https://user-images.githubusercontent.com/32508295/37147393-0c23e1f2-22c7-11e8-9a48-3ba1baaa0822.jpg)

**Comment by ppannusch** [comment]
@CarloVanDriestenBMW The shape needs to be defined somewhere, e.g. in the map file. Otherwise you cannot just imply the shape because, as you stated, not every light in the real world actually has the corresponding "picture" on it.
@carsten-kuebler and @CarloVanDriestenBMW I agree that we could leave out the type here and take it from the assigned lane; but then assigned lane cannot be an array (or the array must not contain different lane types, as Carsten implicitly stated). Also we need to define more specific types than "nondriving".
I also agree with introducing the crosswalk lane (non-drivable, like the pedestrian way next to the road), because this is definetively an important information for the host vehicle. Do we need any changes to allow those lanes (except the new lane types)?

**Comment by carsten-kuebler** [comment]
@ppannusch Do you have an example? I can imagine only traffic light combinations which are unambiguous.

One open issue may be: Do lanes need to know superposing lanes (same problem for narrow lanes -> see issue #156)

**Comment by carsten-kuebler** [comment]
@IgorBelyakovIntel the BaseStationary of each traffic light defines the layout of the traffic lights. In OSI 3.0 a traffic light modells only one "bulb" and not the "box".
