### ISSUE TITLE
WinError 5 when trying to install open-simulator-interface

### ISSUE THREAD

**Issue by ntscheppe** [OpenSimulationInterface/open-simulation-interface#716]
Hey, 
so when trying to install open-simulator-interface using 
`python -m pip install git+https://github.com/OpenSimulationInterface/open-simulation-interface`
I get the followin error output. Any suggestions on how to fix this?

Collecting git+https://github.com/OpenSimulationInterface/open-simulation-interface
  Cloning https://github.com/OpenSimulationInterface/open-simulation-interface to c:\temp\pip-req-build-teq59xjl
  Running command git clone --filter=blob:none --quiet https://github.com/OpenSimulationInterface/open-simulation-interface 'C:\Temp\pip-req-build-teq59xjl'
  Resolved https://github.com/OpenSimulationInterface/open-simulation-interface to commit f52aeb32e63c6aca21ba16dfc18a28f196668050
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Requirement already satisfied: protobuf in c:\users\u24p72\appdata\local\programs\python\python39\lib\site-packages (from open-simulation-interface==3.5.0) (4.21.12)
Building wheels for collected packages: open-simulation-interface
  Building wheel for open-simulation-interface (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_py
      error: [WinError 5] Zugriff verweigert
      Protobuf-compiling osi_common.proto
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for open-simulation-interface
  Running setup.py clean for open-simulation-interface
Failed to build open-simulation-interface
Installing collected packages: open-simulation-interface
  Running setup.py install for open-simulation-interface ... error
  error: subprocess-exited-with-error

  × Running setup.py install for open-simulation-interface did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running install
      running build
      running build_py
      error: [WinError 5] Zugriff verweigert
      Protobuf-compiling osi_common.proto
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> open-simulation-interface

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by felixfroehling** [comment]
Hey, are you still having this problem?
For me this worked out:

I have added the PROTOC Path to the Windows Environment variables.
Then made the following change in the setup.py file:
![grafik](https://github.com/OpenSimulationInterface/open-simulation-interface/assets/63063096/7a61a19c-a1b8-498c-8d9e-e70289583d89)

the command "self.find_protoc" gives you only the folder and in my case i had to add the function call "\protoc.exe"

I hope this helps you out. :D

**Comment by DerBaertige** [comment]
I think, it's not a bug, as the PROTOC is not a path-variable as the variable to the binary of the protoc-compiler.
In Windows, you schould set the variable to `...\protoc.exe`.

The problem should be solved then, if the reference is set correcly.
