### ISSUE TITLE
OSI for Simulation and Stimulation on Real Sensor [ENABLE-S3]

### ISSUE THREAD

**Issue by HannesSchneiderAVL** [OpenSimulationInterface/open-simulation-interface#74]
Hello!

For the ENABLE-S3 test environment we would like to use OSI in a HIL environment. E.g. a physical sensor will be stimulated with the simulation over a co-simulation environment and a special FMI will then convert the data from the Sensor to OSI so that it can be compared with the Ground Truth data from the simulation. [see ppt file]
We have defined a mapping table (see Excel sheet) for mapping physical values to OSI. During the discussion we found out that we would need some extra fields in OSI (see Excel sheet attached).

[ObjectList Proposal v4.xlsx](https://github.com/OpenSimulationInterface/open-simulation-interface/files/1091520/ObjectList.Proposal.v4.xlsx)

[ENABLE-S3_SWP35_OpenSimulationInterface.pdf](https://github.com/OpenSimulationInterface/open-simulation-interface/files/1091522/ENABLE-S3_SWP35_OpenSimulationInterface.pdf)

We would like to discuss how this additional information can be transmitted or if it makes sense to add them to the specification of OSI.

BR
Hannes

**Comment by CarloVanDriestenBMW** [comment]
@AhmedMzid could you please check the list of attributes with the current implementation?

**Comment by sadrihakki** [comment]
Hi Hannes, Hi Carlo,
exactly, that's our first proposal for extension and clarification of the output interfaces of a logical model of a perception sensor we would like to discuss.
I totally support this request.

**Comment by AhmedMzid** [comment]
A first discussion regarding the different implementation possibilities took place. Some fields need indeed to be added to OSI or to be more accurately defined. Other fields need a further discussion or a clarification of your side. More details can be found in the last column of the Excel sheet. Your feedback would be greatly appreciated.
[ObjectList.Proposal.v4.xlsx](https://github.com/OpenSimulationInterface/open-simulation-interface/files/1119404/ObjectList.Proposal.v4.xlsx)

**Comment by CarloVanDriestenBMW** [comment]
Did you see our response, @HannesSchneiderAVL @sadrihakki ?

**Comment by HannesSchneiderAVL** [comment]
Thank you for your response. We have our regular meeting tomorrow and will discuss your feedback there.

**Comment by sadrihakki** [comment]
Hello Ahmed,
Hello Carlo,

Thank you for your valuable response, we did a short review in the team meeting today that decided that we'll adapt our proposal to your feedback in the next days an elaborate an agreement on a workshop that's planned about mid of August. So the moment we found an agreement we'll push the update here and inform you.
BR Sadri

**Comment by CarloVanDriestenBMW** [comment]
@sadrihakki we considered that you split the different topics into separat issues. When can we expect your input?

**Comment by HannesSchneiderAVL** [comment]
Hello,
We had a meeting today and took some decissions:

Regarding the age in the Excel sheet we think that its not relevant for us on a object level but since it is available in OSI anyway it is ok for us.

I will add the other issues as separate items.

**Comment by carsten-kuebler** [comment]
If all open PR are included, the following comments should be valid.

![image](https://user-images.githubusercontent.com/32508295/37532001-14760e0c-293e-11e8-9c71-4c615c20b493.png)

@CarloVanDriestenBMW: I would add the field age to all messages (DetectedObject has already this field)

**Comment by carsten-kuebler** [comment]
mount_... is the vector between vehicle's reference point and each sensor's mounting_position.

@HannesSchneiderAVL Is the proposal ok?

**Comment by HannesSchneiderAVL** [comment]
Yes it is ok for us!
