### ISSUE TITLE
Unit of measurement for Ambient Illumination

### ISSUE THREAD

**Issue by ndunningbmw** [OpenSimulationInterface/open-simulation-interface#75]
We should try to assign a scientific unit to the Ambient Illumination (lux for example), rather than the loosely defined ambient illumination index.

**Comment by CarloVanDriestenBMW** [comment]
Can you make a proposal @ndunningbmw ?

[Maybe like this?](https://www.noao.edu/education/QLTkit/ACTIVITY_Documents/Safety/LightLevels_outdoor+indoor.pdf)

**Comment by ndunningbmw** [comment]
Yes the provided suggestion would be good, as it also provides a standardized value calculation.

Is the value for Ambient Light calculated at the current position where the Ground Truth is filled? I think this is logical but it does not state anywhere in the osi_environment file that this is the case.

**Comment by Sheema60** [comment]
I have added a short report of some research on the definition, units and classification of ambient lighting. For the classification I decided to stick to measurements based on illuminance as that appears to be more generally used. I also made an initial classification and added it to the osi_environment.proto file as a first step. Feedback and comments would be appreciated. 


[Ambient Lighting_part1.pdf](https://github.com/OpenSimulationInterface/open-simulation-interface/files/1306489/Ambient.Lighting_part1.pdf)

**Comment by ndunningbmw** [comment]
Thanks for the update; as far as my use case is concerned, the proposed update to the osi environment would be a good and acceptable solution.

**Comment by CarloVanDriestenBMW** [comment]
@AhmedMzid could you please check the proposal, so that we can discuss it tomorrow?

**Comment by Sheema60** [comment]
I would like to remove the Media College reference as their copyright policies are a little ambiguous and in any case the wording for the definition of ambient light is our own and does not rely solely on this website. I'll make another push. I will leave the report as is, because it is just a source of information in case anyone needs it.

**Comment by Sheema60** [comment]
I added one level and pushed the change. Here is the
[Ambient Lighting_part1_edited.pdf](https://github.com/OpenSimulationInterface/open-simulation-interface/files/1318493/Ambient.Lighting_part1_edited.pdf)
 edited report.
