### ISSUE TITLE
Deprecate lzma encoding/decoding

### ISSUE THREAD

**Issue by vkresch** [OpenSimulationInterface/open-simulation-interface#757]
We are updating OSI validator (https://github.com/OpenSimulationInterface/osi-validation/pull/48) and removing the lzma encoding/decoding.
Thus we should also deprecate this encoding/decoding in [OSI format folder](https://github.com/OpenSimulationInterface/open-simulation-interface/tree/master/format), too.

**Comment by jdsika** [comment]
I vote against it:
https://github.com/OpenSimulationInterface/osi-validation/issues/55

**Comment by pmai** [comment]
LZMA support has been retained and osi-validator will be adjusted to use osi3trace module.
