### ISSUE TITLE
No rule to make target 'install'

### ISSUE THREAD

**Issue by ViktorShum** [OpenSimulationInterface/open-simulation-interface#76]
During the installation of the OSI from the latest source code provided on OSI repository, I found the issue related to the installation step. I've got the error for 'sudo make install':
make: *** No rule to make target 'install'. Stop.
And it is true. There is no 'install' target in Makefile. It was not generated because in CMakeLists.txt no installation instructions.
Building steps done without any errors.
Environment:
Ubuntu 16.04
cmake 3.8.2
make 4.1

**Comment by PhilippRoethigBMW** [comment]
In the current master branch of osi there is no install configured. All instructions regarding the installation process are defined in the rename-files branch, which has not been merged yet.

**Comment by ViktorShum** [comment]
Ok, I see. Thank you.

**Comment by ViktorShum** [comment]
Ok, I see. Thank you.

**Comment by CarloVanDriestenBMW** [comment]
@pmai got the same question here again - can we provide that fot the next version?

**Comment by pmai** [comment]
Should be fixed with PR #134...
