### ISSUE TITLE
Test scripts undocumented

### ISSUE THREAD

**Issue by ClemensLinnhoff** [OpenSimulationInterface/open-simulation-interface#763]
#### Describe the bug
The python unit tests in the tests/ folder are undocumented.
There is a [documentation page](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/V3.5.0/interface/architecture/test_scripts.html) but it is practically empty and can only be found via the search and not via the navigation bar on the left.

#### Describe the expected behavior
A general description of the tests is needed (how to run them, where they are run in the pipeline) and a description for every individual test is needed.

And the documentation page needs to be accessible via the navigation bar.

**Comment by PhRosenberger** [comment]
@philipwindecker @florianwallerer probably we should discuss this in our next CCB meeting?

**Comment by florianwallerer** [comment]
> @philipwindecker @florianwallerer probably we should discuss this in our next CCB meeting?

I will first check with Ben if we can invest the hours to do the documentation work. I hope, I have an answer until the next CCb meeting.

**Comment by PhRosenberger** [comment]
Thx! (This was part of the discussion I planed.)

**Comment by PhRosenberger** [comment]
@florianwallerer as there seems to be no budget in the current OSI project for docu, how do we continue here?

**Comment by florianwallerer** [comment]
> @florianwallerer as there seems to be no budget in the current OSI project for docu, how do we continue here?

I am still in discussion with Ben. He has a lot on his table these days. We can aim for a "small budget" project. This means, the ASAM Office can contract someone without the TSC. But this is of course in Ben's hands. I will bring this up again, probably tomorrow or on Friday.

Topic is not closed, I try to find a solution.

**Comment by pmai** [comment]
Has been adressed by OpenSimulationInterface/osi-documentation#73.
