### ISSUE TITLE
Typo in osi3::TrafficAction::EndActionsAction documentation

### ISSUE THREAD

**Issue by ClemensLinnhoff** [OpenSimulationInterface/open-simulation-interface#773]
#### Describe the bug

There is a typo in the [detailed documentation of osi3::TrafficAction::EndActionsAction](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/V3.5.0/gen/structosi3_1_1TrafficAction_1_1EndActionsAction.html#_detailed_description): "exection" instead of "execution".

**Comment by ClemensLinnhoff** [comment]
@philipwindecker I was not aware of that.

@florianwallerer is there someone else currently responsible for the documentation?

**Comment by florianwallerer** [comment]
Hi Clemens,
responsible for the documentation ist the project. (ASAM OSI). As Philip, said, there is no documentation service provider available for ASAM OSI currently.

So probably the best way to fix this is, if you or @PhRosenberger create a pull request for this typo.

**Comment by philipwindecker** [comment]
> @philipwindecker I was not aware of that.
> 
> @florianwallerer is there someone else currently responsible for the documentation?

No problem. I just wanted to make sure this issue does not sink to the bottom of the Backlog because of this. :)
