### ISSUE TITLE
Use of RFC 2119 terms in documentation and comments

### ISSUE THREAD

**Issue by jdsika** [OpenSimulationInterface/open-simulation-interface#804]
#### Describe the problem
While I was reviewing PRs for v3.7.0 I stumbled across this description:

>     // Route segments that form the route of an agent.
>     //
>     // Consecutive segments should be connected without gaps, meaning that the
>     // two of them should form a continuous area.
>     //
>     repeated RouteSegment route_segment = 2;

#### Ask your question
SHALL we use or RECOMMEND the use of terms derived from [The Dublin Core, RFC 2413](https://www.ietf.org/rfc/rfc2413.txt).

The key words “MUST”, “MUST NOT”, “REQUIRED”, “SHALL”, “SHALL NOT”, “SHOULD”, “SHOULD NOT”, “RECOMMENDED”, “MAY”, and “OPTIONAL” in this document are to be interpreted as described in [RFC 2119](https://www.ietf.org/rfc/rfc2119.txt).

**Comment by pmai** [comment]
ASAM uses more or less the ISO conventions (see https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/specification/general_docs/conventions.html for OSI), which, while I think ISO's rules on MUST vs. SHALL are misguided, is OK enough to me, and the current ASAM approach.
