### ISSUE TITLE
Doc: Protobuffer vesion

### ISSUE THREAD

**Issue by jdsika** [OpenSimulationInterface/open-simulation-interface#807]
OSI Documentation still mentions protobuf > 3.0.0

**Comment by ClemensLinnhoff** [comment]
And that should be changed to >= 2.6.1?

**Comment by jdsika** [comment]
@pmai do we have a decision here from the CCB?

**Comment by pmai** [comment]
CCB 2024-05-13: Fix with PR that changes the two references in doc/setup/installing_prerequisites.adoc to 2.6.1. @pmai to create PR and merge today.
