### ISSUE TITLE
TrafficCommandUpdate missing from trace file name documentation

### ISSUE THREAD

**Issue by ClemensLinnhoff** [OpenSimulationInterface/open-simulation-interface#816]
#### Describe the bug

The trace file naming convention in the [documentation](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/V3.6.0-rc1/interface/architecture/trace_file_naming.html) lists possible types of top-level messages. However, the TrafficCommandUpdate is missing. I propose to use 'tcu' as an abbreviation.

#### Show some screenshots

![image](https://github.com/OpenSimulationInterface/open-simulation-interface/assets/27010086/dcc6f3ba-ccfc-4820-9147-d1efee904fa1)

**Comment by ClemensLinnhoff** [comment]
The TrafficCommandUpdate is also missing from section 2.2.2 of the documentation:

![image](https://github.com/OpenSimulationInterface/open-simulation-interface/assets/27010086/580c4cd3-4bc3-4c5d-973c-c67a9181b846)

**Comment by xuanyuxin** [comment]
I have a similar question. Why does 2.2.2 Top-level interfaces only have these classes i.e. how to include other classes mentioned in [classes](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/gen/annotated.html) so that I can have these msg available in the trace file. Thanks!

**Comment by ClemensLinnhoff** [comment]
Chapter 2.2.2 only lists possible top-level messages. Other messages listed in the classes are contained in these top-level messages. Also, top-level messages can contain other messages, that can also be used as top-level messages. For example: A SensorData message can contain a SensorView message. But you could also use SensorView by its own.

This is also reflected in the possible trace file types, described [here](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/interface/architecture/trace_file_naming.html). To give an example: You can have a GroundTruth trace file containing MovingObjects. But you cannot have a MovingObject trace file.
