### ISSUE TITLE
Support more top-level messages in OSITrace

### ISSUE THREAD

**Issue by ClemensLinnhoff** [OpenSimulationInterface/open-simulation-interface#817]
#### Describe the feature
Currently only SensorData, SensorView and GroundTruth are supported as top-level messages. We should implement also the other top-level messages, e.g. TrafficUpdate, TrafficCommand and TrafficCommandUpdate.

#### Describe the solution you would like
Add the missing top-level messages to the type selection in OSITrace.

#### Describe the backwards compatibility
Would be just an addition, so no issues.

**Comment by jdsika** [comment]
@pmai thats something for the next patch version?
