### ISSUE TITLE
Using OSI pip installer in venv leads to errors for pre-releases.

### ISSUE THREAD

**Issue by thempen** [OpenSimulationInterface/open-simulation-interface#822]
Currently the PyPi is is deployed to https://test.pypi.org/legacy/.

This leads to missing dependencies for ProtoBuf by default, which is not available in the test.pypi listing. 
So testing the pip usage right now is not possible. You have to install the dependencies manually for the venv.

**Comment by pmai** [comment]
Actually it works but you have to use the option that only uses test.pypi.org for the package you explicitly mention, not for the dependencies. I stumbled across this, too, as test.pypi.org suggests the other option, which does not work in our case.

**Comment by thempen** [comment]
OK, got it, thank you. So for everybody who has the same issue, this worked for me:
```
python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple open-simulation-interface
```
