### ISSUE TITLE
Lane driving direction

### ISSUE THREAD

**Issue by solosito** [OpenSimulationInterface/open-simulation-interface#84]
- Is the supposed driving direction indicated somewhere? I haven't seen it.
- In case it doesn't, why not?
- In case it wasn't considered, would it makes sense to add it?

It could be added to the OSI::Lane, something like this:

```
message Lane
{
    // The rest of the Lane message
    //
    {...}

    // A lane direction describes the supposed driving direction of the lane.
    //
    optional LaneDrivingDirection lane_driving_direction = 10;
    
    // Definition of available lane driving direction types.
    //
    enum LaneDrivingDirection
    {
        // Lane of unknown driving direction (must not be used in ground truth).
        //
        LANE_DRIVING_DIRECTION_UNKNOWN = 0;
        
        // Other (unspecified but known) lane driving direction.
        //
        LANE_DRIVING_DIRECTION_OTHER = 1;
        
        // The lane driving direction is right.
        //
        LANE_DRIVING_DIRECTION_RIGHT_WAY = 2;
        
        // The lane driving direction is wrong.
        //
        LANE_DRIVING_DIRECTION_WRONG_WAY = 3;
    }
}
```

**Comment by CarloVanDriestenBMW** [comment]
Thank you for your suggestion. We will investigate it!

**Comment by JonathanSchmalhoferBMW** [comment]
In [Issue 80](https://github.com/OpenSimulationInterface/open-simulation-interface/issues/80) I assumed that the driving direction is implicitly defined by the direction of the ascending order of LaneBoundary-Points and CenterLine-Points in their respective array.

This is of course not mandatory and makes conversion from OSI-Messages for right-hand-traffic to left-hand-traffic complicated. A flag as proposed by @solosito would therefore be much easier to handle.

**Comment by solosito** [comment]
I have been thinking about this matter and how to define the lane driving direction. The problem is that the lane driving direction it is relative data and not absolute. It depends on the point of view of the observer. A first approximation led me to think about defining it regarding the sensor mounting data, but this assumption would be wrong because it could not be used in the ground truth due to its relativity.

From my point of view, the only plausible solution would be defining it respecting the direction of the vector defining the lane's center line. This would make much easier to handle right-hand and left-hand   traffic systems as point by @JonathanSchmalhoferBMW.

**Comment by CarloVanDriestenBMW** [comment]
The driving direction must be the "intended driving direction" in the GT. I do not think it should be relative to the ego vehicle.

**Comment by CarloVanDriestenBMW** [comment]
> Well, if I want to use the same (simulation) world and want to drive right and left-hand traffic over it, then you would have to reverse the order of the center_line points, i. e. effort. Alternatively, I can "just" adjust the flag. Either way, I would have to create the GTs new/different, because I don't see the difference sooo huge, but surely there is.
> With the flag you have of course also the extra effort to check it and if necessary turn the directional vectors or re-sort the list, depending on what you use the info for.
> 
> As always, it is a trade-off: easier to use compared to error susceptibility. Is a preference decision rather than a content decision in my opinion, i. e. relatively unimportant as long as consistent (and binding!) 
> 

A comment from @TimoHankeBMW

**Comment by carsten-kuebler** [comment]
I made a proposal in pull request #110 (regarding issue #80)
