### ISSUE TITLE
Definition of Timestamp

### ISSUE THREAD

**Issue by AhmedMzid** [OpenSimulationInterface/open-simulation-interface#86]
The current definition of timestamp in GroundTruth does not precise how the zero time must be defined. In this way, it can be different from the starting time point of the simulation. 
However, the zero time point of Timestamp in GT must - in certain circumstances - coincide with the starting time of the simulation in order to be able to reproduce the real behavior of sensor models (latency, update rate..). The problem occurs especially when a particular part of a scenario should be resimulated without replaying the complete scenario.
The need for a further specification on the definition of Timestamp in GT should be discussed.

**Comment by haoyuanying** [comment]
A possible solution can be found at the document. 
[zerotime solution.pdf](https://github.com/OpenSimulationInterface/open-simulation-interface/files/1382566/zerotime.solution.pdf)

**Comment by CarloVanDriestenBMW** [comment]
solved by #130
