### ISSUE TITLE
Reduction of duplicated data

### ISSUE THREAD

**Issue by ndunningbmw** [OpenSimulationInterface/open-simulation-interface#93]
In order to make the OSI Ground Truth messages smaller in size and contain less duplicated data, I would suggest that a change be made to how lanes are defined.

Current, a lane consists of a series of points for the left and right edges. When were are many neighboring lanes running together for a long distance, each of these boundaries must be described twice; the left-edge for one lane is the right-edge for an other.

I would therefore suggest that a collection of boundaries be send for each Ground Truth message, and have these referenced by ID in the Lane.

**Comment by CarloVanDriestenBMW** [comment]
#110
