### ISSUE TITLE
Doxygen Collaboration Diagram extension

### ISSUE THREAD

**Issue by carsten-kuebler** [OpenSimulationInterface/open-simulation-interface#94]
Hi all,

all collaboration diagrams show no attributes with basic datatypes (eg double) and repeated messages. To visualize these attributes I propose a change in doxygen_config.cmake.in:

add option
`HIDE_UNDOC_RELATIONS = NO`

**Comment by CarloVanDriestenBMW** [comment]
I agree, please update the file and make a pull request

**Comment by CarloVanDriestenBMW** [comment]
resolved by #95
